/**
 * BUSINESS RULE LIBRARY
 * ------------------------------------------------------------------
 * Each rule: id, domain, required facts, a readable condition, severity, an insight template,
 * and recommendation templates. Rules never touch the UI and never invent numbers:
 * they read facts computed from the dataset.
 *
 * Families (growth, streak, concentration, segment movement...) are generated by small factories
 * so thresholds stay consistent and easy to tune. To add a one-off rule, push into EXPLICIT_RULES.
 */
import type { Domain, L10n, Role } from '@/types/core'
import type { FocusItem, Param, Severity } from '@/types/analysis'
import { ROLE_META } from '../dictionaries/roles'
import { RATIO_METRICS } from '../analysis/ratioFacts'

export type Facts = Record<string, number>
export type Labels = Record<string, string>

export interface RuleDef {
  id: string
  domain: Domain | 'generic'
  requires: string[]
  condition: string
  severity: Severity
  template: string
  recommendations: string[]
  metric: string
  when: (f: Facts, l: Labels) => boolean
  params: (f: Facts, l: Labels) => Record<string, Param>
  /** extra fact keys to show as evidence (requires are always included) */
  evidence?: string[]
  current?: (f: Facts) => Param
  comparison?: (f: Facts) => Param
  focus?: FocusItem['page']
  suppresses?: string[]
  /** magnitude used to rank hits within a severity */
  magnitude?: (f: Facts) => number
}

// ---------------------------------------------------------------- param helpers
const ml = (r: string): Param => ({ t: lower(ROLE_META[r as Role]?.label ?? { vi: r, en: r }) })
const mlCap = (r: string): Param => ({ t: ROLE_META[r as Role]?.label ?? { vi: r, en: r } })
const pct = (v: number, signed = false): Param => ({ v, f: 'percent', signed })
const pp = (v: number): Param => ({ v, f: 'pp', signed: true })
const ppAbs = (v: number): Param => ({ v: Math.abs(v), f: 'pp' })
const fmtM = (r: string, v: number): Param => ({ v, f: ROLE_META[r as Role]?.format ?? 'number' })
const int = (v: number): Param => ({ v, f: 'integer' })
const lower = (x: L10n): L10n => ({ vi: x.vi.toLowerCase(), en: x.en.toLowerCase() })
export const PERIOD_PARAM = '__period__'
export const MEASURE_PARAM = '__measure__'
/** period label placeholder resolved by the engine (localized) */
const per = (): Param => PERIOD_PARAM

function abs(v: number) {
  return Math.abs(v)
}

const RULES: RuleDef[] = []
const add = (r: RuleDef) => RULES.push(r)

// ---------------------------------------------------------------- growth families (higher is better)
interface GoodMeasureOpts {
  domain: Domain | 'generic'
  code: string
  down: number
  downSharp: number
  up: number
  upStrong: number
  full: boolean
  recDown: string[]
  recUp: string[]
}

function goodMeasureFamily(m: Role, o: GoodMeasureOpts) {
  const g = `g.${m}`
  const base = (f: Facts) => ({ measure: mlCap(m), chg: pct(abs(f[g])), cur: fmtM(m, f[`last.${m}`]), prev: fmtM(m, f[`prev.${m}`]), cur_period: per() })
  add({ id: `${o.code}-001`, domain: o.domain, requires: [g, `last.${m}`, `prev.${m}`], condition: `${g} <= -${o.downSharp * 100}%`, severity: 'critical', template: 'metric_decline_sharp', recommendations: o.recDown, metric: m, when: (f) => f[g] <= -o.downSharp, params: base, current: (f) => fmtM(m, f[`last.${m}`]), comparison: (f) => fmtM(m, f[`prev.${m}`]), suppresses: [`${o.code}-002`], magnitude: (f) => abs(f[g]), focus: 'dashboard' })
  add({ id: `${o.code}-002`, domain: o.domain, requires: [g, `last.${m}`, `prev.${m}`], condition: `${g} <= -${o.down * 100}%`, severity: 'warning', template: 'metric_decline', recommendations: o.recDown, metric: m, when: (f) => f[g] <= -o.down, params: base, current: (f) => fmtM(m, f[`last.${m}`]), comparison: (f) => fmtM(m, f[`prev.${m}`]), magnitude: (f) => abs(f[g]), focus: 'dashboard' })
  add({ id: `${o.code}-003`, domain: o.domain, requires: [g, `last.${m}`, `prev.${m}`], condition: `${g} >= +${o.upStrong * 100}%`, severity: 'positive', template: 'metric_growth_strong', recommendations: o.recUp, metric: m, when: (f) => f[g] >= o.upStrong, params: base, suppresses: [`${o.code}-004`], magnitude: (f) => f[g], focus: 'dashboard' })
  add({ id: `${o.code}-004`, domain: o.domain, requires: [g, `last.${m}`, `prev.${m}`], condition: `${g} >= +${o.up * 100}%`, severity: 'positive', template: 'metric_growth', recommendations: o.recUp, metric: m, when: (f) => f[g] >= o.up, params: base, magnitude: (f) => f[g], focus: 'dashboard' })
  add({ id: `${o.code}-005`, domain: o.domain, requires: [`decl.${m}`, `last.${m}`], condition: `decl.${m} >= 3`, severity: 'warning', template: 'consecutive_decline', recommendations: o.recDown, metric: m, when: (f) => f[`decl.${m}`] >= 3, params: (f) => ({ measure: mlCap(m), n: int(f[`decl.${m}`]), cur: fmtM(m, f[`last.${m}`]) }), magnitude: (f) => f[`decl.${m}`] / 10, focus: 'dashboard' })
  add({ id: `${o.code}-006`, domain: o.domain, requires: [`incr.${m}`, `last.${m}`], condition: `incr.${m} >= 3`, severity: 'positive', template: 'consecutive_growth', recommendations: o.recUp, metric: m, when: (f) => f[`incr.${m}`] >= 3, params: (f) => ({ measure: mlCap(m), n: int(f[`incr.${m}`]), cur: fmtM(m, f[`last.${m}`]) }), magnitude: (f) => f[`incr.${m}`] / 10 })
  add({ id: `${o.code}-007`, domain: o.domain, requires: [`g3.${m}`], condition: `g3.${m} <= -10%`, severity: 'warning', template: 'quarter_decline', recommendations: o.recDown, metric: m, when: (f) => f[`g3.${m}`] <= -0.1, params: (f) => ({ measure: ml(m), chg: pct(abs(f[`g3.${m}`])) }), magnitude: (f) => abs(f[`g3.${m}`]) })
  add({ id: `${o.code}-008`, domain: o.domain, requires: [`g3.${m}`], condition: `g3.${m} >= +10%`, severity: 'positive', template: 'quarter_growth', recommendations: o.recUp, metric: m, when: (f) => f[`g3.${m}`] >= 0.1, params: (f) => ({ measure: ml(m), chg: pct(f[`g3.${m}`]) }), magnitude: (f) => f[`g3.${m}`] })
  if (!o.full) return
  add({ id: `${o.code}-009`, domain: o.domain, requires: [`trend.${m}.slope`, `trend.${m}.r2`], condition: `trend slope <= -3%/period AND R² >= 0.5`, severity: 'watch', template: 'downtrend', recommendations: ['monitor_trend', ...o.recDown], metric: m, when: (f) => f[`trend.${m}.slope`] <= -0.03 && f[`trend.${m}.r2`] >= 0.5, params: (f) => ({ measure: ml(m), slope: pct(abs(f[`trend.${m}.slope`])), r2: { v: f[`trend.${m}.r2`], f: 'score' } }), magnitude: (f) => abs(f[`trend.${m}.slope`]) })
  add({ id: `${o.code}-010`, domain: o.domain, requires: [`trend.${m}.slope`, `trend.${m}.r2`], condition: `trend slope >= +3%/period AND R² >= 0.5`, severity: 'positive', template: 'uptrend', recommendations: o.recUp, metric: m, when: (f) => f[`trend.${m}.slope`] >= 0.03 && f[`trend.${m}.r2`] >= 0.5, params: (f) => ({ measure: ml(m), slope: pct(f[`trend.${m}.slope`]), r2: { v: f[`trend.${m}.r2`], f: 'score' } }), magnitude: (f) => f[`trend.${m}.slope`] })
  add({ id: `${o.code}-011`, domain: o.domain, requires: [`cv.${m}`, 'periods'], condition: `cv.${m} >= 35% AND periods >= 6`, severity: 'watch', template: 'volatile', recommendations: ['smooth_volatility'], metric: m, when: (f) => f[`cv.${m}`] >= 0.35 && f.periods >= 6, params: (f) => ({ measure: mlCap(m), cv: pct(f[`cv.${m}`]) }), magnitude: (f) => f[`cv.${m}`] / 2 })
  add({ id: `${o.code}-012`, domain: o.domain, requires: [`is_peak.${m}`, `last.${m}`, 'periods'], condition: `latest period is the highest AND periods >= 6`, severity: 'positive', template: 'record_high', recommendations: ['sustain_growth'], metric: m, when: (f) => f[`is_peak.${m}`] === 1 && f.periods >= 6, params: (f) => ({ measure: mlCap(m), cur: fmtM(m, f[`last.${m}`]), cur_period: per(), n: int(f.periods) }), magnitude: () => 0.2 })
  add({ id: `${o.code}-013`, domain: o.domain, requires: [`is_low.${m}`, `last.${m}`, 'periods'], condition: `latest period is the lowest AND periods >= 6`, severity: 'warning', template: 'record_low', recommendations: o.recDown, metric: m, when: (f) => f[`is_low.${m}`] === 1 && f.periods >= 6, params: (f) => ({ measure: mlCap(m), cur: fmtM(m, f[`last.${m}`]), cur_period: per(), n: int(f.periods) }), magnitude: () => 0.3 })
  add({ id: `${o.code}-014`, domain: o.domain, requires: [`accel.${m}`, g], condition: `growth slowed by >= 15pp`, severity: 'watch', template: 'deceleration', recommendations: ['monitor_trend'], metric: m, when: (f) => f[`accel.${m}`] <= -0.15 && f[g] > -o.down, params: (f) => ({ measure: ml(m), accel: pp(abs(f[`accel.${m}`])) }), magnitude: (f) => abs(f[`accel.${m}`]) / 2 })
  add({ id: `${o.code}-015`, domain: o.domain, requires: [`accel.${m}`, g], condition: `growth accelerated by >= 15pp AND growth > 0`, severity: 'opportunity', template: 'acceleration', recommendations: ['sustain_growth'], metric: m, when: (f) => f[`accel.${m}`] >= 0.15 && f[g] > 0, params: (f) => ({ measure: ml(m), accel: pp(f[`accel.${m}`]) }), magnitude: (f) => f[`accel.${m}`] / 2 })
  add({ id: `${o.code}-016`, domain: o.domain, requires: [`yoy.${m}`], condition: `yoy.${m} <= -10%`, severity: 'warning', template: 'yoy_decline', recommendations: o.recDown, metric: m, when: (f) => f[`yoy.${m}`] <= -0.1, params: (f) => ({ measure: mlCap(m), chg: pct(abs(f[`yoy.${m}`])), cur_period: per() }), magnitude: (f) => abs(f[`yoy.${m}`]) })
  add({ id: `${o.code}-017`, domain: o.domain, requires: [`yoy.${m}`], condition: `yoy.${m} >= +10%`, severity: 'positive', template: 'yoy_growth', recommendations: o.recUp, metric: m, when: (f) => f[`yoy.${m}`] >= 0.1, params: (f) => ({ measure: mlCap(m), chg: pct(f[`yoy.${m}`]), cur_period: per() }), magnitude: (f) => f[`yoy.${m}`] })
  add({ id: `${o.code}-018`, domain: o.domain, requires: [`last_vs_avg.${m}`, 'periods'], condition: `latest period >= 20% below average`, severity: 'watch', template: 'below_average', recommendations: o.recDown, metric: m, when: (f) => f[`last_vs_avg.${m}`] <= -0.2 && f.periods >= 4, params: (f) => ({ measure: mlCap(m), chg: pct(abs(f[`last_vs_avg.${m}`])), cur_period: per() }), magnitude: (f) => abs(f[`last_vs_avg.${m}`]) / 2 })
  add({ id: `${o.code}-019`, domain: o.domain, requires: [`last_vs_avg.${m}`, 'periods'], condition: `latest period >= 20% above average`, severity: 'positive', template: 'above_average', recommendations: o.recUp, metric: m, when: (f) => f[`last_vs_avg.${m}`] >= 0.2 && f.periods >= 4, params: (f) => ({ measure: mlCap(m), chg: pct(f[`last_vs_avg.${m}`]), cur_period: per() }), magnitude: (f) => f[`last_vs_avg.${m}`] / 2 })
}

goodMeasureFamily('revenue', { domain: 'generic', code: 'REV', down: 0.1, downSharp: 0.2, up: 0.08, upStrong: 0.2, full: true, recDown: ['investigate_decline'], recUp: ['sustain_growth'] })
goodMeasureFamily('profit', { domain: 'finance', code: 'PRF', down: 0.1, downSharp: 0.25, up: 0.1, upStrong: 0.25, full: true, recDown: ['decompose_margin'], recUp: ['sustain_growth'] })
goodMeasureFamily('output', { domain: 'manufacturing', code: 'OUT', down: 0.08, downSharp: 0.2, up: 0.08, upStrong: 0.2, full: true, recDown: ['capacity_plan'], recUp: ['sustain_growth'] })
goodMeasureFamily('lead', { domain: 'marketing', code: 'LED', down: 0.15, downSharp: 0.3, up: 0.15, upStrong: 0.3, full: true, recDown: ['optimize_channels'], recUp: ['lead_followup'] })
goodMeasureFamily('quantity', { domain: 'sales', code: 'QTY', down: 0.1, downSharp: 0.25, up: 0.1, upStrong: 0.25, full: false, recDown: ['investigate_decline'], recUp: ['sustain_growth'] })
goodMeasureFamily('orders', { domain: 'marketing', code: 'ORD', down: 0.12, downSharp: 0.3, up: 0.12, upStrong: 0.3, full: false, recDown: ['lead_followup'], recUp: ['sustain_growth'] })
goodMeasureFamily('actual', { domain: 'finance', code: 'ACT', down: 0.15, downSharp: 0.3, up: 0.15, upStrong: 0.3, full: false, recDown: ['monitor_trend'], recUp: ['monitor_trend'] })

// ---------------------------------------------------------------- risk measures (higher is worse)
function riskMeasureFamily(m: Role, domain: Domain | 'generic', code: string, rise: number, surge: number, rec: string[]) {
  const g = `g.${m}`
  const base = (f: Facts) => ({ measure: mlCap(m), chg: pct(abs(f[g])), cur: fmtM(m, f[`last.${m}`]), prev: fmtM(m, f[`prev.${m}`]), cur_period: per() })
  add({ id: `${code}-001`, domain, requires: [g, `last.${m}`, `prev.${m}`], condition: `${g} >= +${surge * 100}%`, severity: 'critical', template: m === 'downtime' ? 'downtime_rising' : 'metric_rise_critical', recommendations: rec, metric: m, when: (f) => f[g] >= surge, params: base, suppresses: [`${code}-002`], magnitude: (f) => f[g], focus: 'dashboard' })
  add({ id: `${code}-002`, domain, requires: [g, `last.${m}`, `prev.${m}`], condition: `${g} >= +${rise * 100}%`, severity: 'warning', template: m === 'downtime' ? 'downtime_rising' : m === 'expense' ? 'expense_growth' : 'metric_rise_risk', recommendations: rec, metric: m, when: (f) => f[g] >= rise, params: base, magnitude: (f) => f[g], focus: 'dashboard' })
  add({ id: `${code}-003`, domain, requires: [g, `last.${m}`, `prev.${m}`], condition: `${g} <= -${rise * 100}%`, severity: 'positive', template: 'metric_fall_good', recommendations: ['sustain_growth'], metric: m, when: (f) => f[g] <= -rise, params: base, magnitude: (f) => abs(f[g]) })
  add({ id: `${code}-004`, domain, requires: [`incr.${m}`, `last.${m}`], condition: `incr.${m} >= 3`, severity: 'warning', template: 'risk_streak', recommendations: rec, metric: m, when: (f) => f[`incr.${m}`] >= 3, params: (f) => ({ measure: mlCap(m), n: int(f[`incr.${m}`]), cur: fmtM(m, f[`last.${m}`]) }), magnitude: (f) => f[`incr.${m}`] / 10 })
}
riskMeasureFamily('cost', 'generic', 'CST', 0.12, 0.3, ['review_costs'])
riskMeasureFamily('expense', 'finance', 'EXP', 0.15, 0.35, ['budget_control'])
riskMeasureFamily('defect', 'manufacturing', 'DEF', 0.2, 0.5, ['quality_rootcause'])
riskMeasureFamily('downtime', 'manufacturing', 'DWT', 0.25, 0.6, ['maintenance'])
riskMeasureFamily('returns', 'retail', 'RET', 0.2, 0.5, ['reduce_returns'])
riskMeasureFamily('duration', 'operations', 'DUR', 0.15, 0.4, ['process_review'])
riskMeasureFamily('response_time', 'customer_service', 'RSP', 0.15, 0.4, ['service_capacity'])

// ---------------------------------------------------------------- segment families
interface SegOpts {
  domain: Domain | 'generic'
  code: string
  topShare?: number
  topSeverity?: Severity
  topTemplate?: string
  top5?: number
  pareto?: boolean
  rec: string[]
}
function segmentFamily(d: Role, o: SegOpts) {
  const s = `seg.${d}`
  const dimP = (): Param => ({ t: lower(ROLE_META[d].label) })
  const measureP = (_l: Labels): Param => MEASURE_PARAM
  if (o.topShare !== undefined) {
    add({ id: `${o.code}-001`, domain: o.domain, requires: [`${s}.top_share`, `${s}.count`], condition: `${s}.top_share >= ${o.topShare * 100}%`, severity: o.topSeverity ?? 'watch', template: o.topTemplate ?? 'top_entity_concentration', recommendations: o.rec, metric: d, when: (f) => f[`${s}.top_share`] >= o.topShare! && f[`${s}.count`] >= 3, params: (f, l) => ({ dim: dimP(), top: l[`${s}.top`] ?? '', share: pct(f[`${s}.top_share`]), measure: measureP(l), lead: { v: f[`${s}.lead_ratio`] ?? NaN, f: 'ratio' } }), evidence: [`${s}.top5_share`, `${s}.lead_ratio`], magnitude: (f) => f[`${s}.top_share`], focus: 'dashboard' })
  }
  if (o.top5 !== undefined) {
    add({ id: `${o.code}-002`, domain: o.domain, requires: [`${s}.top5_share`, `${s}.count`], condition: `${s}.top5_share >= ${o.top5 * 100}% AND count >= 10`, severity: 'watch', template: 'top5_concentration', recommendations: o.rec, metric: d, when: (f) => f[`${s}.top5_share`] >= o.top5! && f[`${s}.count`] >= 10, params: (f, l) => ({ dim: dimP(), share: pct(f[`${s}.top5_share`]), measure: measureP(l) }), magnitude: (f) => f[`${s}.top5_share`] / 1.5 })
  }
  if (o.pareto) {
    add({ id: `${o.code}-003`, domain: o.domain, requires: [`pareto.${d}.share80`, `pareto.${d}.top20`], condition: `pareto.${d}.share80 <= 20%`, severity: 'watch', template: 'pareto_concentration', recommendations: ['review_portfolio'], metric: d, when: (f) => f[`pareto.${d}.share80`] <= 0.2, params: (f, l) => ({ dim: dimP(), share80: pct(f[`pareto.${d}.share80`]), top20: pct(f[`pareto.${d}.top20`]), measure: measureP(l) }), magnitude: (f) => 1 - f[`pareto.${d}.share80`], focus: 'dashboard' })
    add({ id: `${o.code}-004`, domain: o.domain, requires: [`pareto.${d}.top20`, `pareto.${d}.count`], condition: `top 20% >= 75% AND count >= 20`, severity: 'opportunity', template: 'long_tail', recommendations: ['focus_tail'], metric: d, when: (f) => f[`pareto.${d}.top20`] >= 0.75 && f[`pareto.${d}.count`] >= 20, params: (f, l) => ({ dim: dimP(), count: int(f[`pareto.${d}.count`]), top20: pct(f[`pareto.${d}.top20`]), measure: measureP(l) }), magnitude: (f) => f[`pareto.${d}.top20`] / 3 })
  }
  add({ id: `${o.code}-005`, domain: o.domain, requires: [`${s}.worst_chg`, `${s}.worst_share`], condition: `worst ${d} change <= -20% AND share >= 5%`, severity: 'warning', template: 'segment_decline', recommendations: ['review_segment'], metric: d, when: (f) => f['meta.polarity'] === 1 && f[`${s}.worst_chg`] <= -0.2 && f[`${s}.worst_share`] >= 0.05, params: (f, l) => ({ dim: dimP(), worst: l[`${s}.worst`] ?? '', chg: pct(abs(f[`${s}.worst_chg`])), share: pct(f[`${s}.worst_share`]), measure: measureP(l), cur_period: per() }), magnitude: (f) => abs(f[`${s}.worst_chg`]) * (0.5 + f[`${s}.worst_share`]), focus: 'dashboard' })
  add({ id: `${o.code}-006`, domain: o.domain, requires: [`${s}.best_chg`, `${s}.best_share`], condition: `best ${d} change >= +25% AND share >= 5%`, severity: 'opportunity', template: 'segment_growth', recommendations: ['scale_winner'], metric: d, when: (f) => f['meta.polarity'] === 1 && f[`${s}.best_chg`] >= 0.25 && f[`${s}.best_share`] >= 0.05, params: (f, l) => ({ dim: dimP(), best: l[`${s}.best`] ?? '', chg: pct(f[`${s}.best_chg`]), share: pct(f[`${s}.best_share`]), measure: measureP(l), cur_period: per() }), magnitude: (f) => f[`${s}.best_chg`] * (0.5 + f[`${s}.best_share`]) })
  add({ id: `${o.code}-007`, domain: o.domain, requires: [`${s}.decliners_share`, `${s}.avg_chg`, `${s}.count`], condition: `>= 70% of ${d} declining AND avg <= -5%`, severity: 'warning', template: 'broad_decline', recommendations: ['investigate_decline'], metric: d, when: (f) => f['meta.polarity'] === 1 && f[`${s}.decliners_share`] >= 0.7 && f[`${s}.avg_chg`] <= -0.05 && f[`${s}.count`] >= 4, params: (f, l) => ({ dim: dimP(), share: pct(f[`${s}.decliners_share`]), avg: pct(f[`${s}.avg_chg`], true), measure: measureP(l) }), magnitude: (f) => f[`${s}.decliners_share`] })
  add({ id: `${o.code}-008`, domain: o.domain, requires: [`${s}.decliners_share`, `${s}.avg_chg`, `${s}.count`], condition: `<= 20% of ${d} declining AND avg >= +5%`, severity: 'positive', template: 'broad_growth', recommendations: ['sustain_growth'], metric: d, when: (f) => f['meta.polarity'] === 1 && f[`${s}.decliners_share`] <= 0.2 && f[`${s}.avg_chg`] >= 0.05 && f[`${s}.count`] >= 4, params: (f, l) => ({ dim: dimP(), share: pct(1 - f[`${s}.decliners_share`]), avg: pct(f[`${s}.avg_chg`], true), measure: measureP(l) }), magnitude: (f) => f[`${s}.avg_chg`] })
  add({ id: `${o.code}-010`, domain: o.domain, requires: [`${s}.best_chg`, `${s}.best_share`, 'meta.polarity'], condition: `cost-like measure: best ${d} change >= +25% AND share >= 5%`, severity: 'warning', template: 'segment_cost_surge', recommendations: ['review_costs'], metric: d, when: (f) => f['meta.polarity'] === -1 && f[`${s}.best_chg`] >= 0.25 && f[`${s}.best_share`] >= 0.05, params: (f, l) => ({ dim: dimP(), top: l[`${s}.best`] ?? '', chg: pct(f[`${s}.best_chg`]), share: pct(f[`${s}.best_share`]), measure: measureP(l), cur_period: per() }), magnitude: (f) => f[`${s}.best_chg`] * (0.5 + f[`${s}.best_share`]), focus: 'dashboard' })
  add({ id: `${o.code}-011`, domain: o.domain, requires: [`${s}.worst_chg`, `${s}.worst_share`, 'meta.polarity'], condition: `cost-like measure: worst ${d} change <= -20% AND share >= 5%`, severity: 'positive', template: 'segment_cost_drop', recommendations: ['sustain_growth'], metric: d, when: (f) => f['meta.polarity'] === -1 && f[`${s}.worst_chg`] <= -0.2 && f[`${s}.worst_share`] >= 0.05, params: (f, l) => ({ dim: dimP(), top: l[`${s}.worst`] ?? '', chg: pct(abs(f[`${s}.worst_chg`])), share: pct(f[`${s}.worst_share`]), measure: measureP(l), cur_period: per() }), magnitude: (f) => abs(f[`${s}.worst_chg`]) * (0.5 + f[`${s}.worst_share`]) })
  add({ id: `${o.code}-009`, domain: o.domain, requires: [`${s}.spread`, `${s}.best_chg`, `${s}.worst_chg`], condition: `best − worst growth >= 60pp`, severity: 'watch', template: 'segment_divergence', recommendations: ['review_segment'], metric: d, when: (f) => f[`${s}.spread`] >= 0.6 && f[`${s}.worst_chg`] < 0 && f[`${s}.best_chg`] > 0, params: (f, l) => ({ dim: dimP(), best: l[`${s}.best`] ?? '', worst: l[`${s}.worst`] ?? '', best_chg: pct(f[`${s}.best_chg`], true), worst_chg: pct(f[`${s}.worst_chg`], true), spread: pct(f[`${s}.spread`]) }), magnitude: (f) => f[`${s}.spread`] / 3 })
}
segmentFamily('customer', { domain: 'sales', code: 'CUS', topShare: 0.4, topSeverity: 'warning', top5: 0.7, pareto: true, rec: ['diversify_customers', 'protect_key_accounts'] })
segmentFamily('product', { domain: 'sales', code: 'PRD', topShare: 0.5, pareto: true, rec: ['review_portfolio'] })
segmentFamily('region', { domain: 'sales', code: 'RGN', topShare: 0.6, topTemplate: 'dim_dominance', rec: ['review_segment'] })
segmentFamily('branch', { domain: 'retail', code: 'BRN', topShare: 0.5, topTemplate: 'dim_dominance', pareto: true, rec: ['review_segment'] })
segmentFamily('salesperson', { domain: 'sales', code: 'SLP', topShare: 0.35, topTemplate: 'salesperson_dependency', rec: ['sales_coaching'] })
segmentFamily('channel', { domain: 'marketing', code: 'CHN', topShare: 0.7, topTemplate: 'dim_dominance', rec: ['optimize_channels'] })
segmentFamily('category', { domain: 'retail', code: 'CAT', topShare: 0.6, topTemplate: 'dim_dominance', rec: ['review_portfolio'] })
segmentFamily('department', { domain: 'finance', code: 'DPT', topShare: 0.45, topTemplate: 'dept_overrun', rec: ['budget_control'] })
segmentFamily('campaign', { domain: 'marketing', code: 'CMP', topShare: 0.6, pareto: true, rec: ['optimize_channels'] })
segmentFamily('supplier', { domain: 'inventory', code: 'SUP', topShare: 0.5, topTemplate: 'supplier_dependency', rec: ['review_costs'] })
segmentFamily('line', { domain: 'manufacturing', code: 'LIN', rec: ['capacity_plan'] })
segmentFamily('machine', { domain: 'manufacturing', code: 'MCH', rec: ['maintenance'] })

// ---------------------------------------------------------------- ratio hotspots (segment-level KPIs)
let ratioSeq = 0
for (const def of RATIO_METRICS) {
  for (const dim of def.dims) {
    const p = `ratio.${def.id}.${dim}`
    const code = `RAT-${String(++ratioSeq).padStart(3, '0')}`
    const dimP: Param = { t: lower(ROLE_META[dim].label) }
    const metricP: Param = { t: def.label }
    const domain: Domain | 'generic' = ['defect_rate', 'downtime_avg', 'output_ach'].includes(def.id) ? 'manufacturing' : ['roas', 'cpl', 'ctr'].includes(def.id) ? 'marketing' : ['absence', 'salary_avg', 'performance_avg'].includes(def.id) ? 'hr' : ['response_avg', 'satisfaction_avg'].includes(def.id) ? 'customer_service' : def.id === 'duration_avg' ? 'operations' : def.id === 'budget_util' ? 'finance' : def.id === 'target_ach' ? 'sales' : 'retail'
    const recs: Record<string, string[]> = {
      defect_rate: ['quality_rootcause'], downtime_avg: ['maintenance'], output_ach: ['capacity_plan'], roas: ['optimize_channels'], cpl: ['optimize_channels', 'creative_test'], ctr: ['creative_test'],
      margin: ['decompose_margin', 'review_pricing'], absence: ['attendance_review'], salary_avg: ['payroll_review'], performance_avg: ['performance_program'], return_rate: ['reduce_returns'],
      response_avg: ['service_capacity'], duration_avg: ['process_review'], satisfaction_avg: ['service_quality'], target_ach: ['close_target_gap'], budget_util: ['budget_control'],
    }
    const badIsHigh = def.better === 'low'
    // the "bad" extreme: highest for bad-high metrics, lowest for good-high metrics
    if (badIsHigh) {
      add({ id: code, domain, requires: [`${p}.max`, `${p}.avg`, `${p}.n`], condition: `highest ${def.id} by ${dim} >= 1.5 × average`, severity: 'watch', template: 'ratio_hotspot', recommendations: recs[def.id] ?? ['review_segment'], metric: def.id, when: (f) => f[`${p}.avg`] > 0 && f[`${p}.max`] >= 1.5 * f[`${p}.avg`] && f[`${p}.n`] >= 2, params: (f, l) => ({ dim: dimP, top: l[`${p}.max`] ?? '', metric: metricP, value: { v: f[`${p}.max`], f: def.format }, avg: { v: f[`${p}.avg`], f: def.format } }), magnitude: (f) => f[`${p}.max`] / f[`${p}.avg`] / 4, focus: 'dashboard' })
    } else {
      add({ id: code, domain, requires: [`${p}.min`, `${p}.avg`, `${p}.n`], condition: `lowest ${def.id} by ${dim} <= 0.7 × average`, severity: 'watch', template: 'ratio_low', recommendations: recs[def.id] ?? ['review_segment'], metric: def.id, when: (f) => f[`${p}.avg`] > 0 && f[`${p}.min`] <= 0.7 * f[`${p}.avg`] && f[`${p}.n`] >= 2, params: (f, l) => ({ dim: dimP, top: l[`${p}.min`] ?? '', metric: metricP, value: { v: f[`${p}.min`], f: def.format }, avg: { v: f[`${p}.avg`], f: def.format } }), magnitude: (f) => (1 - f[`${p}.min`] / f[`${p}.avg`]) / 2, focus: 'dashboard' })
      add({ id: `${code}B`, domain, requires: [`${p}.max`, `${p}.avg`, `${p}.n`], condition: `highest ${def.id} by ${dim} >= 1.4 × average`, severity: 'opportunity', template: 'ratio_best', recommendations: ['scale_winner'], metric: def.id, when: (f) => f[`${p}.avg`] > 0 && f[`${p}.max`] >= 1.4 * f[`${p}.avg`] && f[`${p}.n`] >= 3, params: (f, l) => ({ dim: dimP, top: l[`${p}.max`] ?? '', metric: metricP, value: { v: f[`${p}.max`], f: def.format }, avg: { v: f[`${p}.avg`], f: def.format } }), magnitude: (f) => f[`${p}.max`] / f[`${p}.avg`] / 5 })
    }
  }
}

// ---------------------------------------------------------------- explicit rules
const k = (id: string) => `kpi.${id}`
add({ id: 'GEN-001', domain: 'generic', requires: ['g.revenue', 'g.cost'], condition: 'g.revenue <= -3% AND g.cost >= +3%', severity: 'critical', template: 'cost_pressure', recommendations: ['decompose_margin', 'review_costs'], metric: 'profit', when: (f) => f['g.revenue'] <= -0.03 && f['g.cost'] >= 0.03, params: (f) => ({ rev_chg: pct(abs(f['g.revenue'])), cost_chg: pct(f['g.cost']) }), evidence: ['margin.chg_pp'], suppresses: ['GEN-002'], magnitude: (f) => f['g.cost'] - f['g.revenue'], focus: 'dashboard' })
add({ id: 'GEN-002', domain: 'generic', requires: ['g.revenue', 'g.cost'], condition: 'g.cost − g.revenue >= 8pp AND g.cost > 0', severity: 'warning', template: 'cost_outpacing', recommendations: ['review_costs'], metric: 'cost', when: (f) => f['g.cost'] - f['g.revenue'] >= 0.08 && f['g.cost'] > 0, params: (f) => ({ rev_chg: pct(f['g.revenue'], true), cost_chg: pct(f['g.cost'], true) }), magnitude: (f) => f['g.cost'] - f['g.revenue'] })
add({ id: 'GEN-003', domain: 'generic', requires: ['margin.decl', 'margin.cur', 'margin.chg_pp'], condition: 'margin declined >= 3 consecutive periods', severity: 'warning', template: 'margin_compression', recommendations: ['decompose_margin'], metric: 'margin', when: (f) => f['margin.decl'] >= 3, params: (f) => ({ n: int(f['margin.decl']), margin: pct(f['margin.cur']), chg_pp: pp(f['margin.chg_pp']) }), suppresses: ['GEN-004'], magnitude: (f) => f['margin.decl'] / 6 })
add({ id: 'GEN-004', domain: 'generic', requires: ['margin.chg_pp', 'margin.cur', 'margin.prev'], condition: 'margin change <= -3pp', severity: 'warning', template: 'margin_drop', recommendations: ['decompose_margin'], metric: 'margin', when: (f) => f['margin.chg_pp'] <= -0.03, params: (f) => ({ prev: pct(f['margin.prev']), cur: pct(f['margin.cur']), chg_pp: ppAbs(f['margin.chg_pp']) }), magnitude: (f) => abs(f['margin.chg_pp']) * 5 })
add({ id: 'GEN-005', domain: 'generic', requires: ['margin.chg_pp', 'margin.cur', 'margin.prev'], condition: 'margin change >= +3pp', severity: 'positive', template: 'margin_expansion', recommendations: ['sustain_growth'], metric: 'margin', when: (f) => f['margin.chg_pp'] >= 0.03, params: (f) => ({ prev: pct(f['margin.prev']), cur: pct(f['margin.cur']), chg_pp: pp(f['margin.chg_pp']) }), magnitude: (f) => f['margin.chg_pp'] * 5 })
add({ id: 'GEN-006', domain: 'generic', requires: [k('gross_margin'), k('profit')], condition: 'profit margin < 0', severity: 'critical', template: 'negative_margin', recommendations: ['decompose_margin', 'review_pricing'], metric: 'profit', when: (f) => f[k('gross_margin')] < 0, params: (f) => ({ profit: { v: f[k('profit')], f: 'currency' }, margin: pct(f[k('gross_margin')]) }), magnitude: () => 1 })
add({ id: 'GEN-007', domain: 'generic', requires: [k('gross_margin')], condition: '0 <= margin < 8%', severity: 'watch', template: 'thin_margin', recommendations: ['review_pricing', 'cost_benchmark'], metric: 'margin', when: (f) => f[k('gross_margin')] >= 0 && f[k('gross_margin')] < 0.08, params: (f) => ({ margin: pct(f[k('gross_margin')]) }), magnitude: (f) => 0.08 - f[k('gross_margin')] })
add({ id: 'GEN-008', domain: 'generic', requires: [k('gross_margin'), k('revenue')], condition: 'margin >= 25%', severity: 'positive', template: 'healthy_margin', recommendations: ['sustain_growth'], metric: 'margin', when: (f) => f[k('gross_margin')] >= 0.25, params: (f) => ({ margin: pct(f[k('gross_margin')]), revenue: { v: f[k('revenue')], f: 'currency' } }), magnitude: (f) => f[k('gross_margin')] / 3 })
add({ id: 'GEN-009', domain: 'generic', requires: [k('cost_ratio')], condition: 'cost / revenue >= 85% (and < 100%)', severity: 'watch', template: 'high_cost_ratio', recommendations: ['cost_benchmark', 'review_costs'], metric: 'cost', when: (f) => f[k('cost_ratio')] >= 0.85 && f[k('cost_ratio')] < 1, params: (f) => ({ ratio: pct(f[k('cost_ratio')]) }), magnitude: (f) => f[k('cost_ratio')] - 0.8 })
add({ id: 'GEN-010', domain: 'generic', requires: ['dq.score'], condition: 'data quality score < 70', severity: 'watch', template: 'data_quality_low', recommendations: ['data_cleanup'], metric: 'data_quality', when: (f) => f['dq.score'] < 70, params: (f) => ({ score: int(f['dq.score']) }), focus: 'health', magnitude: (f) => (70 - f['dq.score']) / 50 })
add({ id: 'GEN-011', domain: 'generic', requires: ['anom.count', 'anom.high'], condition: 'anomalies detected >= 1 (incl. high severity)', severity: 'watch', template: 'anomalies_found', recommendations: ['check_anomalies'], metric: 'anomalies', when: (f) => f['anom.high'] >= 1, params: (f) => ({ count: int(f['anom.count']), high: int(f['anom.high']) }), focus: 'anomalies', magnitude: (f) => Math.min(1, f['anom.high'] / 4) })
// sales
add({ id: 'SAL-001', domain: 'sales', requires: [k('target_achievement'), k('target_gap')], condition: 'target achievement < 80%', severity: 'critical', template: 'target_miss_severe', recommendations: ['close_target_gap', 'review_targets'], metric: 'target', when: (f) => f[k('target_achievement')] < 0.8, params: (f) => ({ ach: pct(f[k('target_achievement')]), gap: { v: abs(f[k('target_gap')]), f: 'currency' } }), suppresses: ['SAL-002'], magnitude: (f) => 1 - f[k('target_achievement')] })
add({ id: 'SAL-002', domain: 'sales', requires: [k('target_achievement'), k('target_gap')], condition: 'target achievement < 95%', severity: 'warning', template: 'target_miss', recommendations: ['close_target_gap'], metric: 'target', when: (f) => f[k('target_achievement')] < 0.95, params: (f) => ({ ach: pct(f[k('target_achievement')]), gap: { v: abs(f[k('target_gap')]), f: 'currency' } }), magnitude: (f) => 1 - f[k('target_achievement')] })
add({ id: 'SAL-003', domain: 'sales', requires: [k('target_achievement'), k('target_gap')], condition: 'target achievement >= 105%', severity: 'positive', template: 'target_exceeded', recommendations: ['review_targets'], metric: 'target', when: (f) => f[k('target_achievement')] >= 1.05, params: (f) => ({ ach: pct(f[k('target_achievement')]), gap: { v: f[k('target_gap')], f: 'currency' } }), magnitude: (f) => f[k('target_achievement')] - 1 })
add({ id: 'SAL-004', domain: 'sales', requires: [k('target_achievement')], condition: '95% <= target achievement < 100%', severity: 'watch', template: 'target_near', recommendations: ['close_target_gap'], metric: 'target', when: (f) => f[k('target_achievement')] >= 0.95 && f[k('target_achievement')] < 1, params: (f) => ({ ach: pct(f[k('target_achievement')]) }), magnitude: () => 0.1 })
add({ id: 'SAL-005', domain: 'sales', requires: [k('target_achievement.chg'), k('target_achievement.cur')], condition: 'target achievement change <= -5pp', severity: 'warning', template: 'target_trend_down', recommendations: ['close_target_gap'], metric: 'target', when: (f) => f[k('target_achievement.chg')] <= -0.05, params: (f) => ({ cur: pct(f[k('target_achievement.cur')]), chg: ppAbs(f[k('target_achievement.chg')]), cur_period: per() }), magnitude: (f) => abs(f[k('target_achievement.chg')]) * 3 })
add({ id: 'SAL-006', domain: 'sales', requires: [k('aov.chg'), k('aov.cur'), k('aov.prev')], condition: 'AOV change <= -10%', severity: 'watch', template: 'aov_decline', recommendations: ['upsell'], metric: 'aov', when: (f) => f[k('aov.chg')] <= -0.1, params: (f) => ({ chg: pct(abs(f[k('aov.chg')])), cur: { v: f[k('aov.cur')], f: 'currency' }, prev: { v: f[k('aov.prev')], f: 'currency' } }), magnitude: (f) => abs(f[k('aov.chg')]) })
add({ id: 'SAL-007', domain: 'sales', requires: [k('aov.chg'), k('aov.cur'), k('aov.prev')], condition: 'AOV change >= +10%', severity: 'positive', template: 'aov_growth', recommendations: ['sustain_growth'], metric: 'aov', when: (f) => f[k('aov.chg')] >= 0.1, params: (f) => ({ chg: pct(f[k('aov.chg')]), cur: { v: f[k('aov.cur')], f: 'currency' }, prev: { v: f[k('aov.prev')], f: 'currency' } }), magnitude: (f) => f[k('aov.chg')] })
add({ id: 'SAL-008', domain: 'sales', requires: [k('customers.chg'), k('customers.cur'), k('customers.prev')], condition: 'active customers change <= -10%', severity: 'warning', template: 'customer_base_shrink', recommendations: ['retention'], metric: 'customers', when: (f) => f[k('customers.chg')] <= -0.1, params: (f) => ({ chg: pct(abs(f[k('customers.chg')])), cur: int(f[k('customers.cur')]), prev: int(f[k('customers.prev')]) }), magnitude: (f) => abs(f[k('customers.chg')]) })
add({ id: 'SAL-009', domain: 'sales', requires: [k('customers.chg'), k('customers.cur'), k('customers.prev')], condition: 'active customers change >= +10%', severity: 'positive', template: 'customer_base_growth', recommendations: ['retention'], metric: 'customers', when: (f) => f[k('customers.chg')] >= 0.1, params: (f) => ({ chg: pct(f[k('customers.chg')]), cur: int(f[k('customers.cur')]), prev: int(f[k('customers.prev')]) }), magnitude: (f) => f[k('customers.chg')] })
add({ id: 'SAL-010', domain: 'sales', requires: [k('cancel_rate')], condition: 'cancellation rate >= 8%', severity: 'warning', template: 'cancel_rate_high', recommendations: ['reduce_cancellations'], metric: 'status', when: (f) => f[k('cancel_rate')] >= 0.08, params: (f) => ({ rate: pct(f[k('cancel_rate')]) }), magnitude: (f) => f[k('cancel_rate')] * 3 })
add({ id: 'SAL-011', domain: 'sales', requires: [k('status_return_rate')], condition: 'returned order rate >= 5%', severity: 'warning', template: 'return_rate_high', recommendations: ['reduce_returns'], metric: 'status', when: (f) => f[k('status_return_rate')] >= 0.05, params: (f) => ({ rate: pct(f[k('status_return_rate')]) }), magnitude: (f) => f[k('status_return_rate')] * 3 })
add({ id: 'SAL-012', domain: 'sales', requires: [k('completion_rate')], condition: 'completion rate < 75%', severity: 'warning', template: 'completion_low', recommendations: ['process_review'], metric: 'status', when: (f) => f[k('completion_rate')] < 0.75 && f[k('completion_rate')] > 0, params: (f) => ({ rate: pct(f[k('completion_rate')]) }), magnitude: (f) => 1 - f[k('completion_rate')] })
add({ id: 'RTL-001', domain: 'retail', requires: [k('discount_rate')], condition: 'discount rate >= 15%', severity: 'watch', template: 'discount_heavy', recommendations: ['review_pricing'], metric: 'discount', when: (f) => f[k('discount_rate')] >= 0.15, params: (f) => ({ rate: pct(f[k('discount_rate')]) }), magnitude: (f) => f[k('discount_rate')] })
add({ id: 'RTL-002', domain: 'retail', requires: [k('discount_rate.chg')], condition: 'discount rate change >= +2pp', severity: 'watch', template: 'discount_rising', recommendations: ['review_pricing'], metric: 'discount', when: (f) => f[k('discount_rate.chg')] >= 0.02, params: (f) => ({ chg: pp(f[k('discount_rate.chg')]) }), magnitude: (f) => f[k('discount_rate.chg')] * 5 })
add({ id: 'RTL-003', domain: 'retail', requires: [k('return_rate')], condition: 'return rate >= 5%', severity: 'warning', template: 'return_rate_high', recommendations: ['reduce_returns'], metric: 'returns', when: (f) => f[k('return_rate')] >= 0.05, params: (f) => ({ rate: pct(f[k('return_rate')]) }), magnitude: (f) => f[k('return_rate')] * 3 })
// finance
add({ id: 'FIN-001', domain: 'finance', requires: [k('budget_utilization'), k('budget_variance')], condition: 'budget utilisation >= 120%', severity: 'critical', template: 'budget_overrun_severe', recommendations: ['budget_control'], metric: 'budget', when: (f) => f[k('budget_utilization')] >= 1.2, params: (f) => ({ util: pct(f[k('budget_utilization')]), variance: { v: abs(f[k('budget_variance')]), f: 'currency' } }), suppresses: ['FIN-002'], magnitude: (f) => f[k('budget_utilization')] - 1 })
add({ id: 'FIN-002', domain: 'finance', requires: [k('budget_utilization'), k('budget_variance')], condition: 'budget utilisation >= 103%', severity: 'warning', template: 'budget_overrun', recommendations: ['budget_control'], metric: 'budget', when: (f) => f[k('budget_utilization')] >= 1.03, params: (f) => ({ util: pct(f[k('budget_utilization')]), variance: { v: abs(f[k('budget_variance')]), f: 'currency' } }), magnitude: (f) => f[k('budget_utilization')] - 1 })
add({ id: 'FIN-003', domain: 'finance', requires: [k('budget_utilization'), k('budget_variance')], condition: 'budget utilisation <= 85%', severity: 'opportunity', template: 'budget_underuse', recommendations: ['budget_reallocate'], metric: 'budget', when: (f) => f[k('budget_utilization')] <= 0.85, params: (f) => ({ util: pct(f[k('budget_utilization')]), variance: { v: abs(f[k('budget_variance')]), f: 'currency' } }), magnitude: (f) => 1 - f[k('budget_utilization')] })
add({ id: 'FIN-004', domain: 'finance', requires: [k('net_income')], condition: 'revenue − expense < 0', severity: 'critical', template: 'net_negative', recommendations: ['budget_control', 'review_costs'], metric: 'net_income', when: (f) => f[k('net_income')] < 0, params: (f) => ({ value: { v: f[k('net_income')], f: 'currency' } }), magnitude: () => 1 })
add({ id: 'FIN-005', domain: 'finance', requires: [k('expense_ratio')], condition: 'expense / revenue >= 90%', severity: 'warning', template: 'high_cost_ratio', recommendations: ['cost_benchmark'], metric: 'expense', when: (f) => f[k('expense_ratio')] >= 0.9, params: (f) => ({ ratio: pct(f[k('expense_ratio')]) }), magnitude: (f) => f[k('expense_ratio')] - 0.8 })
// marketing
add({ id: 'MKT-001', domain: 'marketing', requires: [k('ctr')], condition: 'CTR < 1%', severity: 'watch', template: 'ctr_low', recommendations: ['creative_test'], metric: 'ctr', when: (f) => f[k('ctr')] < 0.01, params: (f) => ({ rate: pct(f[k('ctr')]) }), magnitude: (f) => 0.01 - f[k('ctr')] })
add({ id: 'MKT-002', domain: 'marketing', requires: [k('roas')], condition: 'ROAS < 2', severity: 'warning', template: 'roas_low', recommendations: ['optimize_channels'], metric: 'roas', when: (f) => f[k('roas')] < 2, params: (f) => ({ roas: { v: f[k('roas')], f: 'ratio' } }), magnitude: (f) => (2 - f[k('roas')]) / 2 })
add({ id: 'MKT-003', domain: 'marketing', requires: [k('roas')], condition: 'ROAS >= 4', severity: 'positive', template: 'roas_strong', recommendations: ['optimize_channels'], metric: 'roas', when: (f) => f[k('roas')] >= 4, params: (f) => ({ roas: { v: f[k('roas')], f: 'ratio' } }), magnitude: (f) => f[k('roas')] / 20 })
add({ id: 'MKT-004', domain: 'marketing', requires: [k('cpl.chg'), k('cpl.cur')], condition: 'CPL change >= +15%', severity: 'warning', template: 'cpl_rising', recommendations: ['optimize_channels', 'creative_test'], metric: 'cpl', when: (f) => f[k('cpl.chg')] >= 0.15, params: (f) => ({ cur: { v: f[k('cpl.cur')], f: 'currency' }, chg: pct(f[k('cpl.chg')]), cur_period: per() }), magnitude: (f) => f[k('cpl.chg')] })
add({ id: 'MKT-005', domain: 'marketing', requires: [k('lead_conversion')], condition: 'lead conversion < 5%', severity: 'watch', template: 'lead_conversion_low', recommendations: ['lead_followup'], metric: 'conversion', when: (f) => f[k('lead_conversion')] < 0.05, params: (f) => ({ rate: pct(f[k('lead_conversion')]) }), magnitude: (f) => 0.05 - f[k('lead_conversion')] })
// hr
add({ id: 'HR-001', domain: 'hr', requires: [k('absence_rate')], condition: 'absence rate >= 6%', severity: 'warning', template: 'absence_high', recommendations: ['attendance_review'], metric: 'absence', when: (f) => f[k('absence_rate')] >= 0.06, params: (f) => ({ rate: pct(f[k('absence_rate')]) }), magnitude: (f) => f[k('absence_rate')] * 4 })
add({ id: 'HR-002', domain: 'hr', requires: [k('largest_department_cost_share')], condition: 'largest department payroll share >= 40%', severity: 'watch', template: 'payroll_concentration', recommendations: ['payroll_review'], metric: 'salary', when: (f) => f[k('largest_department_cost_share')] >= 0.4, params: (f, l) => ({ top: l['seg.department.top'] ?? '', share: pct(f[k('largest_department_cost_share')]) }), magnitude: (f) => f[k('largest_department_cost_share')] / 2 })
add({ id: 'HR-003', domain: 'hr', requires: [k('avg_tenure')], condition: 'average tenure < 1.5 years', severity: 'watch', template: 'tenure_low', recommendations: ['retention'], metric: 'tenure', when: (f) => f[k('avg_tenure')] < 1.5, params: (f) => ({ years: { v: f[k('avg_tenure')], f: 'number' } }), magnitude: () => 0.3 })
add({ id: 'HR-004', domain: 'hr', requires: ['ratio.salary_avg.department.max', 'ratio.salary_avg.department.min'], condition: 'max/min department average salary >= 2.5×', severity: 'watch', template: 'ratio_gap', recommendations: ['payroll_review'], metric: 'salary', when: (f) => f['ratio.salary_avg.department.min'] > 0 && f['ratio.salary_avg.department.max'] / f['ratio.salary_avg.department.min'] >= 2.5, params: (f, l) => ({ metric: { t: { vi: 'lương bình quân', en: 'average salary' } }, dim: { t: { vi: 'phòng ban', en: 'departments' } }, top: l['ratio.salary_avg.department.max'] ?? '', bottom: l['ratio.salary_avg.department.min'] ?? '', value: { v: f['ratio.salary_avg.department.max'], f: 'currency' }, low: { v: f['ratio.salary_avg.department.min'], f: 'currency' }, lead: { v: f['ratio.salary_avg.department.max'] / f['ratio.salary_avg.department.min'], f: 'ratio' } }), magnitude: () => 0.2 })
add({ id: 'HR-005', domain: 'hr', requires: [k('avg_performance.chg'), k('avg_performance.cur')], condition: 'performance score change <= -5%', severity: 'watch', template: 'metric_decline', recommendations: ['performance_program'], metric: 'performance', when: (f) => f[k('avg_performance.chg')] <= -0.05, params: (f) => ({ measure: { t: { vi: 'Điểm hiệu suất', en: 'Performance score' } }, chg: pct(abs(f[k('avg_performance.chg')])), cur: { v: f[k('avg_performance.cur')], f: 'score' }, prev: { v: f[k('avg_performance.prev')] ?? NaN, f: 'score' }, cur_period: per() }), magnitude: (f) => abs(f[k('avg_performance.chg')]) })
// manufacturing
add({ id: 'MFG-001', domain: 'manufacturing', requires: [k('defect_rate'), k('output')], condition: 'defect rate >= 6%', severity: 'critical', template: 'defect_rate_critical', recommendations: ['quality_rootcause'], metric: 'defect_rate', when: (f) => f[k('defect_rate')] >= 0.06, params: (f) => ({ rate: pct(f[k('defect_rate')]) }), suppresses: ['MFG-002'], magnitude: (f) => f[k('defect_rate')] * 5 })
add({ id: 'MFG-002', domain: 'manufacturing', requires: [k('defect_rate'), k('output')], condition: 'defect rate >= 3%', severity: 'warning', template: 'defect_rate_high', recommendations: ['quality_rootcause'], metric: 'defect_rate', when: (f) => f[k('defect_rate')] >= 0.03, params: (f) => ({ rate: pct(f[k('defect_rate')]), output: int(f[k('output')]) }), magnitude: (f) => f[k('defect_rate')] * 5 })
add({ id: 'MFG-003', domain: 'manufacturing', requires: [k('defect_rate.chg'), k('defect_rate.cur')], condition: 'defect rate change >= +0.5pp', severity: 'warning', template: 'defect_rate_rising', recommendations: ['quality_rootcause'], metric: 'defect_rate', when: (f) => f[k('defect_rate.chg')] >= 0.005, params: (f) => ({ cur: pct(f[k('defect_rate.cur')]), chg: ppAbs(f[k('defect_rate.chg')]), cur_period: per() }), magnitude: (f) => f[k('defect_rate.chg')] * 20 })
add({ id: 'MFG-004', domain: 'manufacturing', requires: [k('first_pass_yield')], condition: 'first pass yield >= 99%', severity: 'positive', template: 'quality_good', recommendations: ['sustain_growth'], metric: 'defect_rate', when: (f) => f[k('first_pass_yield')] >= 0.99, params: (f) => ({ rate: pct(f[k('first_pass_yield')]) }), magnitude: () => 0.2 })
add({ id: 'MFG-005', domain: 'manufacturing', requires: [k('output_achievement')], condition: 'output / plan < 95%', severity: 'warning', template: 'output_below_plan', recommendations: ['capacity_plan'], metric: 'output', when: (f) => f[k('output_achievement')] < 0.95, params: (f) => ({ ach: pct(f[k('output_achievement')]) }), magnitude: (f) => 1 - f[k('output_achievement')] })
add({ id: 'MFG-006', domain: 'manufacturing', requires: [k('output_achievement')], condition: 'output / plan >= 102%', severity: 'positive', template: 'output_above_plan', recommendations: ['sustain_growth'], metric: 'output', when: (f) => f[k('output_achievement')] >= 1.02, params: (f) => ({ ach: pct(f[k('output_achievement')]) }), magnitude: (f) => f[k('output_achievement')] - 1 })
add({ id: 'MFG-007', domain: 'manufacturing', requires: [k('output_achievement.chg'), k('output_achievement.cur')], condition: 'plan achievement change <= -5pp', severity: 'warning', template: 'target_trend_down', recommendations: ['capacity_plan'], metric: 'output', when: (f) => f[k('output_achievement.chg')] <= -0.05, params: (f) => ({ cur: pct(f[k('output_achievement.cur')]), chg: ppAbs(f[k('output_achievement.chg')]), cur_period: per() }), magnitude: (f) => abs(f[k('output_achievement.chg')]) * 3 })
// inventory
add({ id: 'INV-001', domain: 'inventory', requires: [k('stockout_rate')], condition: 'stock-out records >= 5%', severity: 'critical', template: 'stockout_risk', recommendations: ['replenish'], metric: 'inventory', when: (f) => f[k('stockout_rate')] >= 0.05, params: (f) => ({ rate: pct(f[k('stockout_rate')]) }), magnitude: (f) => f[k('stockout_rate')] * 4 })
add({ id: 'INV-002', domain: 'inventory', requires: [k('inventory_turnover')], condition: 'inventory turnover < 1× within the data period', severity: 'warning', template: 'overstock_risk', recommendations: ['reduce_stock'], metric: 'inventory', when: (f) => f[k('inventory_turnover')] < 1, params: (f) => ({ turnover: { v: f[k('inventory_turnover')], f: 'ratio' } }), magnitude: (f) => 1 - f[k('inventory_turnover')] })
// customer service / operations
add({ id: 'CSV-001', domain: 'customer_service', requires: [k('avg_response_time.chg'), k('avg_response_time.cur')], condition: 'average response time change >= +15%', severity: 'warning', template: 'response_slow', recommendations: ['service_capacity'], metric: 'response_time', when: (f) => f[k('avg_response_time.chg')] >= 0.15, params: (f) => ({ cur: { v: f[k('avg_response_time.cur')], f: 'minutes' }, chg: pct(f[k('avg_response_time.chg')]), cur_period: per() }), magnitude: (f) => f[k('avg_response_time.chg')] })
add({ id: 'CSV-002', domain: 'customer_service', requires: [k('avg_satisfaction.chg'), k('avg_satisfaction.cur')], condition: 'satisfaction change <= -5%', severity: 'warning', template: 'satisfaction_low', recommendations: ['service_quality'], metric: 'satisfaction', when: (f) => f[k('avg_satisfaction.chg')] <= -0.05, params: (f) => ({ cur: { v: f[k('avg_satisfaction.cur')], f: 'score' }, chg: pct(abs(f[k('avg_satisfaction.chg')])), cur_period: per() }), magnitude: (f) => abs(f[k('avg_satisfaction.chg')]) })
add({ id: 'OPS-001', domain: 'operations', requires: [k('on_time_rate')], condition: 'on-time rate < 85%', severity: 'warning', template: 'late_rate_high', recommendations: ['process_review'], metric: 'status', when: (f) => f[k('on_time_rate')] < 0.85, params: (f) => ({ rate: pct(f[k('on_time_rate')]) }), magnitude: (f) => 1 - f[k('on_time_rate')] })
add({ id: 'OPS-002', domain: 'operations', requires: [k('on_time_rate.chg'), k('on_time_rate.cur')], condition: 'on-time rate change <= -3pp', severity: 'warning', template: 'late_rate_rising', recommendations: ['process_review'], metric: 'on_time', when: (f) => f[k('on_time_rate.chg')] <= -0.03, params: (f) => ({ cur: pct(f[k('on_time_rate.cur')]), chg: ppAbs(f[k('on_time_rate.chg')]), cur_period: per() }), magnitude: (f) => abs(f[k('on_time_rate.chg')]) * 4 })
add({ id: 'OPS-003', domain: 'operations', requires: [k('avg_duration.chg'), k('avg_duration.cur')], condition: 'average processing time change >= +15%', severity: 'warning', template: 'response_slow', recommendations: ['process_review'], metric: 'duration', when: (f) => f[k('avg_duration.chg')] >= 0.15, params: (f) => ({ cur: { v: f[k('avg_duration.cur')], f: 'hours' }, chg: pct(f[k('avg_duration.chg')]), cur_period: per() }), magnitude: (f) => f[k('avg_duration.chg')] })
add({ id: 'HR-006', domain: 'hr', requires: [k('absence_rate.chg'), k('absence_rate.cur')], condition: 'absence rate change >= +1pp', severity: 'warning', template: 'absence_rising', recommendations: ['attendance_review'], metric: 'absence', when: (f) => f[k('absence_rate.chg')] >= 0.01, params: (f) => ({ cur: pct(f[k('absence_rate.cur')]), chg: ppAbs(f[k('absence_rate.chg')]), cur_period: per() }), magnitude: (f) => f[k('absence_rate.chg')] * 10 })
add({ id: 'HR-007', domain: 'hr', requires: [k('payroll.chg'), k('payroll.cur')], condition: 'payroll change >= +4%', severity: 'watch', template: 'payroll_growth', recommendations: ['payroll_review'], metric: 'salary', when: (f) => f[k('payroll.chg')] >= 0.04, params: (f) => ({ cur: { v: f[k('payroll.cur')], f: 'currency' }, chg: pct(f[k('payroll.chg')]), cur_period: per() }), magnitude: (f) => f[k('payroll.chg')] })
add({ id: 'FIN-006', domain: 'finance', requires: [k('budget_utilization.cur')], condition: 'latest period budget utilisation >= 105%', severity: 'warning', template: 'budget_overrun_period', recommendations: ['budget_control'], metric: 'budget', when: (f) => f[k('budget_utilization.cur')] >= 1.05, params: (f) => ({ util: pct(f[k('budget_utilization.cur')]), cur_period: per() }), magnitude: (f) => f[k('budget_utilization.cur')] - 1 })
add({ id: 'MKT-006', domain: 'marketing', requires: [k('roas.chg'), k('roas.cur')], condition: 'ROAS change <= -15%', severity: 'warning', template: 'roas_falling', recommendations: ['optimize_channels'], metric: 'roas', when: (f) => f[k('roas.chg')] <= -0.15, params: (f) => ({ cur: { v: f[k('roas.cur')], f: 'ratio' }, chg: pct(abs(f[k('roas.chg')])), cur_period: per() }), magnitude: (f) => abs(f[k('roas.chg')]) })

export const RULE_LIBRARY: readonly RuleDef[] = RULES

export function ruleCountsByDomain(): Record<string, number> {
  const out: Record<string, number> = {}
  for (const r of RULES) out[r.domain] = (out[r.domain] ?? 0) + 1
  return out
}
