/**
 * KPI LIBRARY
 * ------------------------------------------------------------------
 * Every KPI declares the semantic fields it needs, its formula, format, domain and meaning.
 * A KPI is only computed when all required fields exist — nothing is invented.
 *
 * To add a KPI: append an object to KPI_LIBRARY. `compute` receives a Ctx (role-based data access)
 * and, for growth KPIs, the current/previous period contexts. Return NaN when not computable.
 */
import type { Domain, L10n, NumberFormat, Role } from '@/types/core'
import type { Ctx } from '../analysis/context'
import { CANCEL_STATUS, LATE_STATUS, POSITIVE_STATUS, RETURN_STATUS } from '../dictionaries/valueHints'

export interface PeriodPair {
  cur: Ctx
  prev: Ctx
}

export interface KpiDef {
  id: string
  name: L10n
  description: L10n
  formula: string
  format: NumberFormat
  domain: (Domain | 'generic')[]
  required: Role[]
  direction: 'up' | 'down' | 'neutral'
  /** lower = more important when choosing dashboard cards */
  priority: number
  /** true when the KPI is a period-level flow/ratio whose period comparison is meaningful */
  trend: boolean
  /** requires a time dimension (growth KPIs) */
  needsTime?: boolean
  compute: (c: Ctx, p?: PeriodPair) => number
}

const ratio = (a: number, b: number) => (Number.isFinite(a) && Number.isFinite(b) && b !== 0 ? a / b : NaN)
const growth = (a: number, b: number) => (Number.isFinite(a) && Number.isFinite(b) && b !== 0 ? (a - b) / Math.abs(b) : NaN)
const L = (vi: string, en: string): L10n => ({ vi, en })

export const KPI_LIBRARY: KpiDef[] = [
  // ---------------------------------------------------------------- core financials
  { id: 'revenue', name: L('Tổng doanh thu', 'Total revenue'), description: L('Tổng giá trị doanh thu ghi nhận trong dữ liệu.', 'Total revenue recorded in the dataset.'), formula: 'SUM(Revenue)', format: 'currency', domain: ['generic', 'sales', 'retail', 'finance', 'marketing'], required: ['revenue'], direction: 'up', priority: 1, trend: true, compute: (c) => c.sum('revenue') },
  { id: 'cost', name: L('Tổng chi phí', 'Total cost'), description: L('Tổng chi phí / giá vốn ghi nhận.', 'Total cost / COGS recorded.'), formula: 'SUM(Cost)', format: 'currency', domain: ['generic', 'sales', 'retail', 'finance'], required: ['cost'], direction: 'down', priority: 3, trend: true, compute: (c) => c.sum('cost') },
  { id: 'profit', name: L('Lợi nhuận', 'Profit'), description: L('Lợi nhuận từ cột lợi nhuận, hoặc Doanh thu − Chi phí khi không có cột lợi nhuận.', 'Profit column, or Revenue − Cost when no profit column exists.'), formula: 'SUM(Profit) or SUM(Revenue) − SUM(Cost)', format: 'currency', domain: ['generic', 'sales', 'retail', 'finance'], required: ['profit'], direction: 'up', priority: 2, trend: true, compute: (c) => c.sum('profit') },
  { id: 'gross_margin', name: L('Biên lợi nhuận', 'Profit margin'), description: L('Tỷ lệ lợi nhuận trên doanh thu.', 'Profit as a share of revenue.'), formula: 'Profit / Revenue', format: 'percent', domain: ['generic', 'sales', 'retail', 'finance'], required: ['revenue', 'profit'], direction: 'up', priority: 2.5, trend: true, compute: (c) => ratio(c.sum('profit'), c.sum('revenue')) },
  { id: 'cost_ratio', name: L('Tỷ lệ chi phí / doanh thu', 'Cost-to-revenue ratio'), description: L('Mỗi đồng doanh thu tốn bao nhiêu chi phí.', 'How much cost is incurred per unit of revenue.'), formula: 'Cost / Revenue', format: 'percent', domain: ['generic', 'sales', 'finance', 'retail'], required: ['revenue', 'cost'], direction: 'down', priority: 6, trend: true, compute: (c) => ratio(c.sum('cost'), c.sum('revenue')) },
  { id: 'transactions', name: L('Số giao dịch', 'Transactions'), description: L('Số đơn hàng (theo mã đơn nếu có, nếu không là số dòng).', 'Number of orders (distinct order IDs if available, otherwise rows).'), formula: 'COUNT DISTINCT(Order ID) or COUNT(rows)', format: 'integer', domain: ['generic', 'sales', 'retail'], required: ['revenue'], direction: 'up', priority: 4, trend: true, compute: (c) => c.transactions() },
  { id: 'aov', name: L('Giá trị đơn trung bình', 'Average order value'), description: L('Doanh thu bình quân mỗi giao dịch.', 'Average revenue per transaction.'), formula: 'Revenue / Transactions', format: 'currency', domain: ['sales', 'retail', 'generic'], required: ['revenue'], direction: 'up', priority: 5, trend: true, compute: (c) => ratio(c.sum('revenue'), c.transactions()) },
  { id: 'customers', name: L('Số khách hàng', 'Customers'), description: L('Số khách hàng khác nhau có giao dịch.', 'Distinct customers with transactions.'), formula: 'COUNT DISTINCT(Customer)', format: 'integer', domain: ['sales', 'retail', 'generic', 'customer_service'], required: ['customer'], direction: 'up', priority: 6, trend: true, compute: (c) => c.distinct('customer') },
  { id: 'revenue_per_customer', name: L('Doanh thu / khách hàng', 'Revenue per customer'), description: L('Doanh thu bình quân trên mỗi khách hàng.', 'Average revenue per distinct customer.'), formula: 'Revenue / Customers', format: 'currency', domain: ['sales', 'retail'], required: ['revenue', 'customer'], direction: 'up', priority: 9, trend: true, compute: (c) => ratio(c.sum('revenue'), c.distinct('customer')) },
  { id: 'products', name: L('Số sản phẩm có bán', 'Active products'), description: L('Số sản phẩm khác nhau phát sinh giao dịch.', 'Distinct products with transactions.'), formula: 'COUNT DISTINCT(Product)', format: 'integer', domain: ['sales', 'retail', 'inventory'], required: ['product'], direction: 'neutral', priority: 14, trend: false, compute: (c) => c.distinct('product') },
  { id: 'revenue_per_product', name: L('Doanh thu / sản phẩm', 'Revenue per product'), description: L('Doanh thu bình quân của mỗi sản phẩm.', 'Average revenue per product.'), formula: 'Revenue / Products', format: 'currency', domain: ['sales', 'retail'], required: ['revenue', 'product'], direction: 'up', priority: 15, trend: true, compute: (c) => ratio(c.sum('revenue'), c.distinct('product')) },
  { id: 'top_customer_share', name: L('Tỷ trọng khách hàng lớn nhất', 'Top customer share'), description: L('Phần doanh thu đến từ khách hàng lớn nhất.', 'Share of revenue from the largest customer.'), formula: 'MAX(Revenue by Customer) / Revenue', format: 'percent', domain: ['sales', 'generic'], required: ['revenue', 'customer'], direction: 'down', priority: 8, trend: false, compute: (c) => c.topShare('customer', 'revenue', 1) },
  { id: 'top5_customer_share', name: L('Tỷ trọng Top 5 khách hàng', 'Top 5 customer share'), description: L('Phần doanh thu đến từ 5 khách hàng lớn nhất.', 'Share of revenue from the five largest customers.'), formula: 'SUM(Top 5 Customers) / Revenue', format: 'percent', domain: ['sales', 'generic'], required: ['revenue', 'customer'], direction: 'down', priority: 7, trend: false, compute: (c) => c.topShare('customer', 'revenue', 5) },
  { id: 'top_product_share', name: L('Tỷ trọng sản phẩm dẫn đầu', 'Top product share'), description: L('Phần doanh thu đến từ sản phẩm lớn nhất.', 'Share of revenue from the best-selling product.'), formula: 'MAX(Revenue by Product) / Revenue', format: 'percent', domain: ['sales', 'retail'], required: ['revenue', 'product'], direction: 'neutral', priority: 12, trend: false, compute: (c) => c.topShare('product', 'revenue', 1) },
  { id: 'product_concentration', name: L('Mức tập trung sản phẩm (Pareto)', 'Product concentration (Pareto)'), description: L('Tỷ lệ số sản phẩm tạo ra 80% doanh thu. Càng thấp càng tập trung.', 'Share of products generating 80% of revenue. Lower = more concentrated.'), formula: 'Products for 80% Revenue / Products', format: 'percent', domain: ['sales', 'retail'], required: ['revenue', 'product'], direction: 'neutral', priority: 13, trend: false, compute: (c) => c.paretoShare('product', 'revenue') },
  { id: 'customer_concentration', name: L('Mức tập trung khách hàng (Pareto)', 'Customer concentration (Pareto)'), description: L('Tỷ lệ khách hàng tạo ra 80% doanh thu.', 'Share of customers generating 80% of revenue.'), formula: 'Customers for 80% Revenue / Customers', format: 'percent', domain: ['sales'], required: ['revenue', 'customer'], direction: 'neutral', priority: 11, trend: false, compute: (c) => c.paretoShare('customer', 'revenue') },
  { id: 'quantity', name: L('Tổng số lượng', 'Total quantity'), description: L('Tổng số lượng sản phẩm bán ra.', 'Total units sold.'), formula: 'SUM(Quantity)', format: 'integer', domain: ['sales', 'retail', 'inventory'], required: ['quantity'], direction: 'up', priority: 6.5, trend: true, compute: (c) => c.sum('quantity') },
  { id: 'avg_quantity', name: L('Số lượng bình quân / giao dịch', 'Average quantity per transaction'), description: L('Số lượng bình quân mỗi giao dịch.', 'Average units per transaction.'), formula: 'Quantity / Transactions', format: 'number', domain: ['sales', 'retail'], required: ['quantity'], direction: 'up', priority: 16, trend: true, compute: (c) => ratio(c.sum('quantity'), c.transactions()) },
  { id: 'avg_price', name: L('Giá bán bình quân', 'Average selling price'), description: L('Doanh thu trên mỗi đơn vị sản phẩm.', 'Revenue per unit sold.'), formula: 'Revenue / Quantity (or AVG(Price))', format: 'currency', domain: ['sales', 'retail'], required: ['revenue', 'quantity'], direction: 'neutral', priority: 17, trend: true, compute: (c) => ratio(c.sum('revenue'), c.sum('quantity')) },
  { id: 'avg_unit_price', name: L('Đơn giá trung bình', 'Average unit price'), description: L('Trung bình cột đơn giá.', 'Average of the unit price column.'), formula: 'AVG(Price)', format: 'currency', domain: ['retail', 'inventory'], required: ['price'], direction: 'neutral', priority: 20, trend: true, compute: (c) => c.avg('price') },
  { id: 'discount_total', name: L('Tổng chiết khấu', 'Total discount'), description: L('Tổng giá trị chiết khấu / khuyến mãi.', 'Total discounts / promotions.'), formula: 'SUM(Discount)', format: 'currency', domain: ['retail', 'sales'], required: ['discount'], direction: 'down', priority: 18, trend: true, compute: (c) => c.sum('discount') },
  { id: 'discount_rate', name: L('Tỷ lệ chiết khấu', 'Discount rate'), description: L('Chiết khấu so với doanh thu trước chiết khấu.', 'Discount relative to gross revenue.'), formula: 'Discount / (Revenue + Discount)', format: 'percent', domain: ['retail', 'sales'], required: ['discount', 'revenue'], direction: 'down', priority: 10, trend: true, compute: (c) => ratio(c.sum('discount'), c.sum('revenue') + c.sum('discount')) },
  { id: 'return_rate', name: L('Tỷ lệ hoàn trả', 'Return rate'), description: L('Hàng hoàn trả so với số lượng bán, hoặc tỷ lệ đơn có trạng thái hoàn trả.', 'Returned units vs units sold, or share of orders with a return status.'), formula: 'Returns / Quantity or COUNT(status=returned) / COUNT', format: 'percent', domain: ['retail', 'sales'], required: ['returns'], direction: 'down', priority: 9, trend: true, compute: (c) => (c.has('quantity') ? ratio(c.sum('returns'), c.sum('quantity')) : ratio(c.sum('returns'), c.size)) },
  { id: 'status_return_rate', name: L('Tỷ lệ đơn hoàn trả', 'Returned order rate'), description: L('Tỷ lệ dòng có trạng thái hoàn trả / hoàn tiền.', 'Share of records with a returned / refunded status.'), formula: 'COUNT(status ∈ returned) / COUNT', format: 'percent', domain: ['sales', 'retail'], required: ['status'], direction: 'down', priority: 12, trend: true, compute: (c) => c.statusShare(RETURN_STATUS) },
  { id: 'cancel_rate', name: L('Tỷ lệ hủy', 'Cancellation rate'), description: L('Tỷ lệ dòng có trạng thái hủy.', 'Share of records with a cancelled status.'), formula: 'COUNT(status ∈ cancelled) / COUNT', format: 'percent', domain: ['sales', 'retail', 'operations'], required: ['status'], direction: 'down', priority: 11, trend: true, compute: (c) => c.statusShare(CANCEL_STATUS) },
  { id: 'completion_rate', name: L('Tỷ lệ hoàn thành', 'Completion rate'), description: L('Tỷ lệ dòng có trạng thái hoàn thành / thành công.', 'Share of records completed / successful.'), formula: 'COUNT(status ∈ completed) / COUNT', format: 'percent', domain: ['sales', 'operations', 'customer_service'], required: ['status'], direction: 'up', priority: 10, trend: true, compute: (c) => { const v = c.statusShare(POSITIVE_STATUS); return v > 0 ? v : NaN } },
  { id: 'target_achievement', name: L('Tỷ lệ hoàn thành mục tiêu', 'Target achievement'), description: L('Thực hiện (doanh thu hoặc thực tế) so với mục tiêu.', 'Actual (revenue or actual) versus target.'), formula: '(Actual or Revenue) / Target', format: 'percent', domain: ['sales', 'finance', 'generic'], required: ['target'], direction: 'up', priority: 3.5, trend: true, compute: (c) => ratio(c.has('actual') ? c.sum('actual') : c.sum('revenue'), c.sum('target')) },
  { id: 'target_gap', name: L('Chênh lệch so với mục tiêu', 'Gap to target'), description: L('Phần thực hiện còn thiếu (âm) hoặc vượt (dương) so với mục tiêu.', 'Shortfall (negative) or excess (positive) versus target.'), formula: '(Actual or Revenue) − Target', format: 'currency', domain: ['sales', 'finance'], required: ['target'], direction: 'up', priority: 12, trend: false, compute: (c) => (c.has('actual') ? c.sum('actual') : c.sum('revenue')) - c.sum('target') },
  { id: 'budget_total', name: L('Tổng ngân sách', 'Total budget'), description: L('Tổng ngân sách được phân bổ.', 'Total allocated budget.'), formula: 'SUM(Budget)', format: 'currency', domain: ['finance'], required: ['budget'], direction: 'neutral', priority: 4, trend: true, compute: (c) => c.sum('budget') },
  { id: 'budget_variance', name: L('Chênh lệch ngân sách', 'Budget variance'), description: L('Thực chi trừ ngân sách. Dương = vượt ngân sách.', 'Actual spend minus budget. Positive = over budget.'), formula: '(Actual or Expense) − Budget', format: 'currency', domain: ['finance'], required: ['budget'], direction: 'down', priority: 3, trend: false, compute: (c) => (c.has('actual') ? c.sum('actual') : c.has('expense') ? c.sum('expense') : NaN) - c.sum('budget') },
  { id: 'budget_utilization', name: L('Tỷ lệ sử dụng ngân sách', 'Budget utilization'), description: L('Thực chi so với ngân sách.', 'Actual spend relative to budget.'), formula: '(Actual or Expense) / Budget', format: 'percent', domain: ['finance'], required: ['budget'], direction: 'neutral', priority: 2.5, trend: true, compute: (c) => ratio(c.has('actual') ? c.sum('actual') : c.has('expense') ? c.sum('expense') : NaN, c.sum('budget')) },
  { id: 'expense_total', name: L('Tổng chi tiêu', 'Total expense'), description: L('Tổng các khoản chi.', 'Total expenses.'), formula: 'SUM(Expense)', format: 'currency', domain: ['finance', 'generic'], required: ['expense'], direction: 'down', priority: 3, trend: true, compute: (c) => c.sum('expense') },
  { id: 'net_income', name: L('Thu nhập ròng', 'Net income'), description: L('Doanh thu trừ chi tiêu.', 'Revenue minus expenses.'), formula: 'Revenue − Expense', format: 'currency', domain: ['finance'], required: ['revenue', 'expense'], direction: 'up', priority: 2, trend: true, compute: (c) => c.sum('revenue') - c.sum('expense') },
  { id: 'expense_ratio', name: L('Tỷ lệ chi tiêu / doanh thu', 'Expense ratio'), description: L('Chi tiêu trên mỗi đồng doanh thu.', 'Expense per unit of revenue.'), formula: 'Expense / Revenue', format: 'percent', domain: ['finance'], required: ['revenue', 'expense'], direction: 'down', priority: 5, trend: true, compute: (c) => ratio(c.sum('expense'), c.sum('revenue')) },
  { id: 'revenue_growth', name: L('Tăng trưởng doanh thu', 'Revenue growth'), description: L('Doanh thu kỳ gần nhất so với kỳ trước.', 'Latest period revenue vs previous period.'), formula: '(Revenue[t] − Revenue[t−1]) / Revenue[t−1]', format: 'percent', domain: ['generic', 'sales', 'retail', 'finance'], required: ['revenue', 'date'], direction: 'up', priority: 2.2, trend: false, needsTime: true, compute: (_c, p) => (p ? growth(p.cur.sum('revenue'), p.prev.sum('revenue')) : NaN) },
  { id: 'cost_growth', name: L('Tăng trưởng chi phí', 'Cost growth'), description: L('Chi phí kỳ gần nhất so với kỳ trước.', 'Latest period cost vs previous period.'), formula: '(Cost[t] − Cost[t−1]) / Cost[t−1]', format: 'percent', domain: ['generic', 'sales', 'finance'], required: ['cost', 'date'], direction: 'down', priority: 9, trend: false, needsTime: true, compute: (_c, p) => (p ? growth(p.cur.sum('cost'), p.prev.sum('cost')) : NaN) },
  { id: 'profit_growth', name: L('Tăng trưởng lợi nhuận', 'Profit growth'), description: L('Lợi nhuận kỳ gần nhất so với kỳ trước.', 'Latest period profit vs previous period.'), formula: '(Profit[t] − Profit[t−1]) / |Profit[t−1]|', format: 'percent', domain: ['generic', 'sales', 'finance'], required: ['profit', 'date'], direction: 'up', priority: 8, trend: false, needsTime: true, compute: (_c, p) => (p ? growth(p.cur.sum('profit'), p.prev.sum('profit')) : NaN) },
  { id: 'revenue_per_salesperson', name: L('Doanh thu / nhân viên kinh doanh', 'Revenue per salesperson'), description: L('Doanh thu bình quân mỗi nhân viên kinh doanh.', 'Average revenue per salesperson.'), formula: 'Revenue / COUNT DISTINCT(Salesperson)', format: 'currency', domain: ['sales'], required: ['revenue', 'salesperson'], direction: 'up', priority: 7, trend: true, compute: (c) => ratio(c.sum('revenue'), c.distinct('salesperson')) },
  { id: 'top_salesperson_share', name: L('Tỷ trọng nhân viên dẫn đầu', 'Top salesperson share'), description: L('Phần doanh thu của nhân viên kinh doanh dẫn đầu.', 'Share of revenue generated by the top salesperson.'), formula: 'MAX(Revenue by Salesperson) / Revenue', format: 'percent', domain: ['sales'], required: ['revenue', 'salesperson'], direction: 'neutral', priority: 16, trend: false, compute: (c) => c.topShare('salesperson', 'revenue', 1) },
  { id: 'top_region_share', name: L('Tỷ trọng khu vực dẫn đầu', 'Top region share'), description: L('Phần doanh thu của khu vực lớn nhất.', 'Share of revenue from the largest region.'), formula: 'MAX(Revenue by Region) / Revenue', format: 'percent', domain: ['sales', 'retail', 'generic'], required: ['revenue', 'region'], direction: 'neutral', priority: 15, trend: false, compute: (c) => c.topShare('region', 'revenue', 1) },
  { id: 'top_branch_share', name: L('Tỷ trọng chi nhánh dẫn đầu', 'Top branch share'), description: L('Phần doanh thu của chi nhánh / cửa hàng lớn nhất.', 'Share of revenue from the largest branch / store.'), formula: 'MAX(Revenue by Branch) / Revenue', format: 'percent', domain: ['retail', 'sales'], required: ['revenue', 'branch'], direction: 'neutral', priority: 14, trend: false, compute: (c) => c.topShare('branch', 'revenue', 1) },
  { id: 'revenue_per_branch', name: L('Doanh thu / chi nhánh', 'Revenue per branch'), description: L('Doanh thu bình quân mỗi chi nhánh / cửa hàng.', 'Average revenue per branch / store.'), formula: 'Revenue / COUNT DISTINCT(Branch)', format: 'currency', domain: ['retail'], required: ['revenue', 'branch'], direction: 'up', priority: 8, trend: true, compute: (c) => ratio(c.sum('revenue'), c.distinct('branch')) },
  { id: 'revenue_per_employee', name: L('Doanh thu / nhân viên', 'Revenue per employee'), description: L('Doanh thu bình quân mỗi nhân viên.', 'Average revenue per employee.'), formula: 'Revenue / COUNT DISTINCT(Employee)', format: 'currency', domain: ['generic', 'operations'], required: ['revenue', 'employee'], direction: 'up', priority: 12, trend: true, compute: (c) => ratio(c.sum('revenue'), c.distinct('employee')) },
  { id: 'orders_total', name: L('Tổng số đơn', 'Total orders'), description: L('Tổng giá trị cột số đơn hàng.', 'Sum of the orders column.'), formula: 'SUM(Orders)', format: 'integer', domain: ['marketing', 'sales'], required: ['orders'], direction: 'up', priority: 6, trend: true, compute: (c) => c.sum('orders') },
  // ---------------------------------------------------------------- marketing
  { id: 'spend', name: L('Chi phí marketing', 'Marketing spend'), description: L('Tổng chi phí quảng cáo / marketing.', 'Total advertising / marketing spend.'), formula: 'SUM(Spend)', format: 'currency', domain: ['marketing'], required: ['spend'], direction: 'neutral', priority: 1.5, trend: true, compute: (c) => c.sum('spend') },
  { id: 'impressions', name: L('Lượt hiển thị', 'Impressions'), description: L('Tổng lượt hiển thị quảng cáo.', 'Total ad impressions.'), formula: 'SUM(Impressions)', format: 'integer', domain: ['marketing'], required: ['impressions'], direction: 'up', priority: 8, trend: true, compute: (c) => c.sum('impressions') },
  { id: 'clicks', name: L('Lượt nhấp', 'Clicks'), description: L('Tổng lượt nhấp.', 'Total clicks.'), formula: 'SUM(Clicks)', format: 'integer', domain: ['marketing'], required: ['clicks'], direction: 'up', priority: 7, trend: true, compute: (c) => c.sum('clicks') },
  { id: 'ctr', name: L('Tỷ lệ nhấp (CTR)', 'Click-through rate'), description: L('Lượt nhấp trên lượt hiển thị.', 'Clicks per impression.'), formula: 'Clicks / Impressions', format: 'percent', domain: ['marketing'], required: ['clicks', 'impressions'], direction: 'up', priority: 4, trend: true, compute: (c) => ratio(c.sum('clicks'), c.sum('impressions')) },
  { id: 'cpc', name: L('Chi phí / lượt nhấp (CPC)', 'Cost per click'), description: L('Chi phí bình quân cho mỗi lượt nhấp.', 'Average spend per click.'), formula: 'Spend / Clicks', format: 'currency', domain: ['marketing'], required: ['spend', 'clicks'], direction: 'down', priority: 6, trend: true, compute: (c) => ratio(c.sum('spend'), c.sum('clicks')) },
  { id: 'cpm', name: L('Chi phí / 1.000 hiển thị (CPM)', 'Cost per mille'), description: L('Chi phí cho mỗi 1.000 lượt hiển thị.', 'Spend per thousand impressions.'), formula: 'Spend / Impressions × 1000', format: 'currency', domain: ['marketing'], required: ['spend', 'impressions'], direction: 'down', priority: 12, trend: true, compute: (c) => ratio(c.sum('spend'), c.sum('impressions')) * 1000 },
  { id: 'leads', name: L('Số khách tiềm năng', 'Leads'), description: L('Tổng số lead thu được.', 'Total leads generated.'), formula: 'SUM(Leads)', format: 'integer', domain: ['marketing', 'sales'], required: ['lead'], direction: 'up', priority: 3, trend: true, compute: (c) => c.sum('lead') },
  { id: 'cpl', name: L('Chi phí / lead (CPL)', 'Cost per lead'), description: L('Chi phí bình quân để có một lead.', 'Average spend per lead.'), formula: 'Spend / Leads', format: 'currency', domain: ['marketing'], required: ['spend', 'lead'], direction: 'down', priority: 3.5, trend: true, compute: (c) => ratio(c.sum('spend'), c.sum('lead')) },
  { id: 'lead_conversion', name: L('Tỷ lệ chuyển đổi lead', 'Lead conversion'), description: L('Số đơn trên số lead (hoặc trung bình cột tỷ lệ chuyển đổi).', 'Orders per lead (or average of the conversion column).'), formula: 'Orders / Leads or AVG(Conversion)', format: 'percent', domain: ['marketing', 'sales'], required: ['lead'], direction: 'up', priority: 4.5, trend: true, compute: (c) => (c.has('orders') ? ratio(c.sum('orders'), c.sum('lead')) : c.has('conversion') ? c.avg('conversion') : NaN) },
  { id: 'conversion_rate', name: L('Tỷ lệ chuyển đổi', 'Conversion rate'), description: L('Trung bình tỷ lệ chuyển đổi được ghi nhận.', 'Average recorded conversion rate.'), formula: 'AVG(Conversion)', format: 'percent', domain: ['marketing', 'sales'], required: ['conversion'], direction: 'up', priority: 6, trend: true, compute: (c) => c.avg('conversion') },
  { id: 'roas', name: L('Doanh thu / chi phí QC (ROAS)', 'Return on ad spend'), description: L('Doanh thu tạo ra trên mỗi đồng chi phí marketing.', 'Revenue generated per unit of marketing spend.'), formula: 'Revenue / Spend', format: 'ratio', domain: ['marketing'], required: ['revenue', 'spend'], direction: 'up', priority: 2, trend: true, compute: (c) => ratio(c.sum('revenue'), c.sum('spend')) },
  { id: 'cpa', name: L('Chi phí / đơn (CPA)', 'Cost per acquisition'), description: L('Chi phí marketing cho mỗi đơn hàng.', 'Marketing spend per order.'), formula: 'Spend / Orders', format: 'currency', domain: ['marketing'], required: ['spend', 'orders'], direction: 'down', priority: 5, trend: true, compute: (c) => ratio(c.sum('spend'), c.sum('orders')) },
  { id: 'click_to_lead', name: L('Tỷ lệ nhấp → lead', 'Click-to-lead rate'), description: L('Số lead trên mỗi lượt nhấp.', 'Leads per click.'), formula: 'Leads / Clicks', format: 'percent', domain: ['marketing'], required: ['lead', 'clicks'], direction: 'up', priority: 9, trend: true, compute: (c) => ratio(c.sum('lead'), c.sum('clicks')) },
  // ---------------------------------------------------------------- HR
  { id: 'headcount', name: L('Nhân sự (headcount)', 'Headcount'), description: L('Số nhân viên khác nhau.', 'Distinct employees.'), formula: 'COUNT DISTINCT(Employee)', format: 'integer', domain: ['hr'], required: ['employee'], direction: 'neutral', priority: 1, trend: false, compute: (c) => c.distinct('employee') },
  { id: 'avg_salary', name: L('Lương bình quân', 'Average salary'), description: L('Mức lương trung bình mỗi bản ghi nhân viên.', 'Average salary per employee record.'), formula: 'AVG(Salary)', format: 'currency', domain: ['hr'], required: ['salary'], direction: 'neutral', priority: 2, trend: true, compute: (c) => c.avg('salary') },
  { id: 'payroll', name: L('Tổng quỹ lương', 'Total payroll'), description: L('Tổng chi phí lương.', 'Total salary cost.'), formula: 'SUM(Salary)', format: 'currency', domain: ['hr', 'finance'], required: ['salary'], direction: 'neutral', priority: 3, trend: true, compute: (c) => c.sum('salary') },
  { id: 'attendance_rate', name: L('Tỷ lệ chuyên cần', 'Attendance rate'), description: L('Tỷ lệ chuyên cần trung bình.', 'Average attendance rate.'), formula: 'AVG(Attendance)', format: 'percent', domain: ['hr', 'manufacturing'], required: ['attendance'], direction: 'up', priority: 4, trend: true, compute: (c) => { const v = c.avg('attendance'); return v <= 1.0001 ? v : NaN } },
  { id: 'absence_rate', name: L('Tỷ lệ vắng mặt', 'Absence rate'), description: L('1 − tỷ lệ chuyên cần, hoặc ngày nghỉ / (ngày công + ngày nghỉ).', '1 − attendance, or absent days / (present + absent days).'), formula: '1 − Attendance or Absent / (Present + Absent)', format: 'percent', domain: ['hr'], required: ['attendance'], direction: 'down', priority: 5, trend: true, compute: (c) => { const v = c.avg('attendance'); return v <= 1.0001 ? 1 - v : NaN } },
  { id: 'absence_days', name: L('Ngày nghỉ bình quân', 'Average absence days'), description: L('Số ngày nghỉ trung bình mỗi bản ghi.', 'Average absent days per record.'), formula: 'AVG(Absence)', format: 'days', domain: ['hr'], required: ['absence'], direction: 'down', priority: 6, trend: true, compute: (c) => c.avg('absence') },
  { id: 'avg_performance', name: L('Điểm hiệu suất bình quân', 'Average performance score'), description: L('Điểm đánh giá hiệu suất trung bình.', 'Average performance rating.'), formula: 'AVG(Performance)', format: 'score', domain: ['hr'], required: ['performance'], direction: 'up', priority: 5.5, trend: true, compute: (c) => c.avg('performance') },
  { id: 'avg_tenure', name: L('Thâm niên bình quân', 'Average tenure'), description: L('Số năm làm việc bình quân tính đến ngày mới nhất trong dữ liệu.', 'Average years of service up to the latest date in the data.'), formula: 'AVG(Reference date − Hire date) / 365', format: 'number', domain: ['hr'], required: ['hire_date'], direction: 'up', priority: 7, trend: false, compute: (c) => tenure(c) },
  { id: 'departments', name: L('Số phòng ban', 'Departments'), description: L('Số phòng ban khác nhau.', 'Distinct departments.'), formula: 'COUNT DISTINCT(Department)', format: 'integer', domain: ['hr', 'finance'], required: ['department'], direction: 'neutral', priority: 10, trend: false, compute: (c) => c.distinct('department') },
  { id: 'largest_department_cost_share', name: L('Tỷ trọng chi phí phòng ban lớn nhất', 'Largest department cost share'), description: L('Phần quỹ lương thuộc phòng ban lớn nhất.', 'Share of payroll in the largest department.'), formula: 'MAX(Salary by Department) / Salary', format: 'percent', domain: ['hr'], required: ['salary', 'department'], direction: 'neutral', priority: 9, trend: false, compute: (c) => c.topShare('department', 'salary', 1) },
  { id: 'salary_per_head', name: L('Chi phí lương / nhân sự', 'Payroll per head'), description: L('Tổng quỹ lương chia cho số nhân sự.', 'Total payroll divided by headcount.'), formula: 'SUM(Salary) / Headcount', format: 'currency', domain: ['hr'], required: ['salary', 'employee'], direction: 'neutral', priority: 8, trend: true, compute: (c) => ratio(c.sum('salary'), c.distinct('employee')) },
  // ---------------------------------------------------------------- manufacturing
  { id: 'output', name: L('Sản lượng thực tế', 'Actual output'), description: L('Tổng sản lượng sản xuất.', 'Total units produced.'), formula: 'SUM(Output)', format: 'integer', domain: ['manufacturing'], required: ['output'], direction: 'up', priority: 1, trend: true, compute: (c) => c.sum('output') },
  { id: 'planned_output', name: L('Sản lượng kế hoạch', 'Planned output'), description: L('Tổng sản lượng kế hoạch.', 'Total planned units.'), formula: 'SUM(Planned output)', format: 'integer', domain: ['manufacturing'], required: ['planned_output'], direction: 'neutral', priority: 9, trend: true, compute: (c) => c.sum('planned_output') },
  { id: 'output_achievement', name: L('Tỷ lệ đạt kế hoạch sản xuất', 'Output plan achievement'), description: L('Sản lượng thực tế so với kế hoạch.', 'Actual output versus plan.'), formula: 'Output / Planned output', format: 'percent', domain: ['manufacturing'], required: ['output', 'planned_output'], direction: 'up', priority: 2, trend: true, compute: (c) => ratio(c.sum('output'), c.sum('planned_output')) },
  { id: 'defects', name: L('Tổng lỗi / phế phẩm', 'Total defects'), description: L('Tổng số sản phẩm lỗi.', 'Total defective units.'), formula: 'SUM(Defects)', format: 'integer', domain: ['manufacturing'], required: ['defect'], direction: 'down', priority: 6, trend: true, compute: (c) => c.sum('defect') },
  { id: 'defect_rate', name: L('Tỷ lệ lỗi', 'Defect rate'), description: L('Số lỗi trên tổng sản lượng.', 'Defects per unit of output.'), formula: 'Defects / Output', format: 'percent', domain: ['manufacturing'], required: ['defect', 'output'], direction: 'down', priority: 2.5, trend: true, compute: (c) => ratio(c.sum('defect'), c.sum('output')) },
  { id: 'first_pass_yield', name: L('Tỷ lệ đạt chất lượng', 'First pass yield'), description: L('Tỷ lệ sản phẩm đạt (không lỗi).', 'Share of units produced without defects.'), formula: '1 − Defects / Output', format: 'percent', domain: ['manufacturing'], required: ['defect', 'output'], direction: 'up', priority: 4, trend: true, compute: (c) => { const r = ratio(c.sum('defect'), c.sum('output')); return Number.isFinite(r) ? 1 - r : NaN } },
  { id: 'downtime_total', name: L('Tổng thời gian dừng', 'Total downtime'), description: L('Tổng thời gian dừng máy.', 'Total machine downtime.'), formula: 'SUM(Downtime)', format: 'minutes', domain: ['manufacturing', 'operations'], required: ['downtime'], direction: 'down', priority: 3, trend: true, compute: (c) => c.sum('downtime') },
  { id: 'avg_downtime', name: L('Thời gian dừng bình quân / ca', 'Average downtime per record'), description: L('Thời gian dừng trung bình mỗi bản ghi (ca / máy / ngày).', 'Average downtime per record (shift / machine / day).'), formula: 'AVG(Downtime)', format: 'minutes', domain: ['manufacturing', 'operations'], required: ['downtime'], direction: 'down', priority: 5, trend: true, compute: (c) => c.avg('downtime') },
  { id: 'output_per_worker', name: L('Sản lượng / công nhân', 'Output per worker'), description: L('Sản lượng bình quân trên mỗi công nhân / nhân viên.', 'Average output per worker.'), formula: 'Output / COUNT DISTINCT(Employee)', format: 'number', domain: ['manufacturing'], required: ['output', 'employee'], direction: 'up', priority: 7, trend: true, compute: (c) => ratio(c.sum('output'), c.distinct('employee')) },
  { id: 'output_per_machine', name: L('Sản lượng / máy', 'Output per machine'), description: L('Sản lượng bình quân trên mỗi máy.', 'Average output per machine.'), formula: 'Output / COUNT DISTINCT(Machine)', format: 'number', domain: ['manufacturing'], required: ['output', 'machine'], direction: 'up', priority: 8, trend: true, compute: (c) => ratio(c.sum('output'), c.distinct('machine')) },
  { id: 'output_per_hour', name: L('Sản lượng / giờ', 'Output per hour'), description: L('Sản lượng trên mỗi giờ làm việc.', 'Output per working hour.'), formula: 'Output / Hours', format: 'number', domain: ['manufacturing', 'operations'], required: ['output', 'hours'], direction: 'up', priority: 6, trend: true, compute: (c) => ratio(c.sum('output'), c.sum('hours')) },
  // ---------------------------------------------------------------- inventory
  { id: 'inventory_avg', name: L('Tồn kho bình quân', 'Average inventory'), description: L('Mức tồn kho trung bình trên các bản ghi.', 'Average inventory level across records.'), formula: 'AVG(Inventory)', format: 'integer', domain: ['inventory', 'retail'], required: ['inventory'], direction: 'neutral', priority: 2, trend: true, compute: (c) => c.avg('inventory') },
  { id: 'inventory_turnover', name: L('Vòng quay tồn kho', 'Inventory turnover'), description: L('Số lượng bán ra trên tồn kho bình quân (trong phạm vi dữ liệu).', 'Units sold relative to average inventory (within the data period).'), formula: 'Quantity / AVG(Inventory)', format: 'ratio', domain: ['inventory', 'retail'], required: ['inventory', 'quantity'], direction: 'up', priority: 3, trend: true, compute: (c) => ratio(c.sum('quantity'), c.avg('inventory')) },
  { id: 'stockout_rate', name: L('Tỷ lệ hết hàng', 'Stock-out rate'), description: L('Tỷ lệ bản ghi có tồn kho bằng 0.', 'Share of records with zero inventory.'), formula: 'COUNT(Inventory = 0) / COUNT', format: 'percent', domain: ['inventory', 'retail'], required: ['inventory'], direction: 'down', priority: 4, trend: true, compute: (c) => ratio(c.countWhere('inventory', (v) => v <= 0), c.count('inventory')) },
  { id: 'inventory_value', name: L('Giá trị tồn kho (ước tính)', 'Inventory value (est.)'), description: L('Tồn kho × đơn giá, trên các dòng có đủ dữ liệu.', 'Inventory × unit price on rows with both values.'), formula: 'SUM(Inventory × Price)', format: 'currency', domain: ['inventory'], required: ['inventory', 'price'], direction: 'neutral', priority: 5, trend: true, compute: (c) => invValue(c) },
  { id: 'suppliers', name: L('Số nhà cung cấp', 'Suppliers'), description: L('Số nhà cung cấp khác nhau.', 'Distinct suppliers.'), formula: 'COUNT DISTINCT(Supplier)', format: 'integer', domain: ['inventory'], required: ['supplier'], direction: 'neutral', priority: 10, trend: false, compute: (c) => c.distinct('supplier') },
  // ---------------------------------------------------------------- customer service / operations
  { id: 'tickets', name: L('Số yêu cầu', 'Tickets'), description: L('Số yêu cầu / ticket.', 'Number of tickets.'), formula: 'COUNT DISTINCT(Ticket)', format: 'integer', domain: ['customer_service'], required: ['ticket'], direction: 'neutral', priority: 1, trend: true, compute: (c) => c.distinct('ticket') },
  { id: 'avg_response_time', name: L('Thời gian phản hồi bình quân', 'Average response time'), description: L('Thời gian phản hồi trung bình.', 'Average response time.'), formula: 'AVG(Response time)', format: 'minutes', domain: ['customer_service'], required: ['response_time'], direction: 'down', priority: 2, trend: true, compute: (c) => c.avg('response_time') },
  { id: 'avg_satisfaction', name: L('Điểm hài lòng bình quân', 'Average satisfaction'), description: L('Điểm hài lòng trung bình.', 'Average satisfaction score.'), formula: 'AVG(Satisfaction)', format: 'score', domain: ['customer_service', 'generic'], required: ['satisfaction'], direction: 'up', priority: 3, trend: true, compute: (c) => c.avg('satisfaction') },
  { id: 'avg_duration', name: L('Thời gian xử lý bình quân', 'Average processing time'), description: L('Thời gian xử lý / chu kỳ trung bình.', 'Average processing / cycle time.'), formula: 'AVG(Duration)', format: 'hours', domain: ['operations', 'customer_service'], required: ['duration'], direction: 'down', priority: 2, trend: true, compute: (c) => c.avg('duration') },
  { id: 'on_time_rate', name: L('Tỷ lệ đúng hạn', 'On-time rate'), description: L('Tỷ lệ bản ghi không có trạng thái trễ hạn.', 'Share of records without a late / overdue status.'), formula: '1 − COUNT(status ∈ late) / COUNT', format: 'percent', domain: ['operations', 'customer_service'], required: ['status'], direction: 'up', priority: 3, trend: true, compute: (c) => { const v = c.statusShare(LATE_STATUS); return Number.isFinite(v) && v > 0 ? 1 - v : NaN } },
  { id: 'total_hours', name: L('Tổng giờ làm', 'Total hours'), description: L('Tổng số giờ làm việc.', 'Total hours worked.'), formula: 'SUM(Hours)', format: 'hours', domain: ['operations', 'hr'], required: ['hours'], direction: 'neutral', priority: 6, trend: true, compute: (c) => c.sum('hours') },
  { id: 'records', name: L('Số bản ghi', 'Records'), description: L('Số dòng dữ liệu được phân tích.', 'Number of data rows analysed.'), formula: 'COUNT(rows)', format: 'integer', domain: ['generic', 'operations', 'customer_service', 'hr', 'manufacturing', 'inventory', 'finance', 'marketing'], required: [], direction: 'neutral', priority: 30, trend: true, compute: (c) => c.size },
]

function tenure(c: Ctx): number {
  const h = c.dateArray('hire_date')
  if (!h) return NaN
  let ref = -Infinity
  const d = c.dateArray('date')
  const src = d ?? h
  for (let i = 0; i < src.length; i++) if (src[i] === src[i] && src[i] > ref) ref = src[i]
  let s = 0
  let n = 0
  c.forEach((i) => {
    const v = h[i]
    if (v === v && v <= ref) {
      s += (ref - v) / (365.25 * 86400000)
      n++
    }
  })
  return n ? s / n : NaN
}

function invValue(c: Ctx): number {
  const inv = c.measure('inventory')
  const pr = c.measure('price')
  if (!inv || !pr) return NaN
  let s = 0
  let n = 0
  c.forEach((i) => {
    if (inv[i] === inv[i] && pr[i] === pr[i]) {
      s += inv[i] * pr[i]
      n++
    }
  })
  return n ? s : NaN
}

export const KPI_BY_ID = new Map(KPI_LIBRARY.map((k) => [k.id, k]))
