/**
 * INSIGHT TEMPLATES
 * ------------------------------------------------------------------
 * Localized sentence templates. Placeholders {x} are filled ONLY with calculated values.
 * The tone is evidence-first and avoids causal claims.
 */
import type { L10n } from '@/types/core'
import type { Severity } from '@/types/analysis'

export interface InsightTemplate {
  id: string
  type: Severity
  title: L10n
  text: L10n
}

const T = (id: string, type: Severity, tvi: string, ten: string, vi: string, en: string): InsightTemplate => ({ id, type, title: { vi: tvi, en: ten }, text: { vi, en } })

export const INSIGHT_TEMPLATES: InsightTemplate[] = [
  T('metric_decline', 'warning', '{measure} giảm {chg}', '{measure} down {chg}', '{measure} kỳ {cur_period} giảm {chg} so với kỳ trước ({prev} → {cur}).', '{measure} in {cur_period} decreased {chg} versus the previous period ({prev} → {cur}).'),
  T('metric_decline_sharp', 'critical', '{measure} giảm mạnh {chg}', '{measure}: sharp decline of {chg}', '{measure} kỳ {cur_period} giảm mạnh {chg} so với kỳ trước ({prev} → {cur}). Đây là mức giảm đáng kể cần được xem xét ngay.', '{measure} in {cur_period} fell sharply by {chg} versus the previous period ({prev} → {cur}). This is a material decline worth reviewing now.'),
  T('metric_growth', 'positive', '{measure} tăng {chg}', '{measure} up {chg}', '{measure} kỳ {cur_period} tăng {chg} so với kỳ trước ({prev} → {cur}).', '{measure} in {cur_period} increased {chg} versus the previous period ({prev} → {cur}).'),
  T('metric_growth_strong', 'positive', '{measure} tăng trưởng mạnh {chg}', '{measure}: strong growth of {chg}', '{measure} kỳ {cur_period} tăng mạnh {chg} so với kỳ trước ({prev} → {cur}).', '{measure} in {cur_period} grew strongly by {chg} versus the previous period ({prev} → {cur}).'),
  T('cost_pressure', 'critical', 'Áp lực chi phí', 'Cost pressure', 'Doanh thu giảm {rev_chg} trong khi chi phí tăng {cost_chg}, tạo áp lực đáng kể lên hiệu quả kinh doanh.', 'Revenue decreased {rev_chg} while cost increased {cost_chg}, putting significant pressure on business efficiency.'),
  T('cost_outpacing', 'warning', 'Chi phí tăng nhanh hơn doanh thu', 'Cost growing faster than revenue', 'Chi phí tăng {cost_chg}, nhanh hơn mức tăng doanh thu {rev_chg} trong kỳ gần nhất.', 'Cost grew {cost_chg}, faster than revenue growth of {rev_chg} in the latest period.'),
  T('margin_compression', 'warning', 'Biên lợi nhuận bị thu hẹp liên tục', 'Continuous margin compression', 'Biên lợi nhuận đã giảm {n} kỳ liên tiếp, hiện ở mức {margin} (thay đổi {chg_pp} so với kỳ trước).', 'Profit margin has declined for {n} consecutive periods and now stands at {margin} ({chg_pp} versus the previous period).'),
  T('margin_drop', 'warning', 'Biên lợi nhuận giảm {chg_pp}', 'Margin down {chg_pp}', 'Biên lợi nhuận giảm từ {prev} xuống {cur} (giảm {chg_pp}).', 'Profit margin fell from {prev} to {cur} (down {chg_pp}).'),
  T('margin_expansion', 'positive', 'Biên lợi nhuận cải thiện', 'Margin expansion', 'Biên lợi nhuận tăng từ {prev} lên {cur} ({chg_pp}).', 'Profit margin improved from {prev} to {cur} ({chg_pp}).'),
  T('negative_margin', 'critical', 'Lợi nhuận âm', 'Negative profit', 'Tổng lợi nhuận đang âm ({profit}), biên lợi nhuận {margin}.', 'Total profit is negative ({profit}), with a margin of {margin}.'),
  T('thin_margin', 'watch', 'Biên lợi nhuận mỏng', 'Thin margin', 'Biên lợi nhuận chung chỉ đạt {margin}, để lại ít dư địa trước biến động giá hoặc chi phí.', 'Overall profit margin is only {margin}, leaving little buffer against price or cost changes.'),
  T('healthy_margin', 'positive', 'Biên lợi nhuận tốt', 'Healthy margin', 'Biên lợi nhuận chung đạt {margin} trên tổng doanh thu {revenue}.', 'Overall profit margin is {margin} on total revenue of {revenue}.'),
  T('consecutive_decline', 'warning', '{measure} giảm {n} kỳ liên tiếp', '{measure} down {n} periods in a row', '{measure} đã giảm liên tục trong {n} kỳ gần nhất, hiện ở mức {cur}.', '{measure} has declined for {n} consecutive periods and is now {cur}.'),
  T('consecutive_growth', 'positive', '{measure} tăng {n} kỳ liên tiếp', '{measure} up {n} periods in a row', '{measure} đã tăng liên tục trong {n} kỳ gần nhất, hiện ở mức {cur}.', '{measure} has increased for {n} consecutive periods and is now {cur}.'),
  T('downtrend', 'watch', 'Xu hướng giảm của {measure}', 'Downward trend in {measure}', 'Đường xu hướng tuyến tính của {measure} đi xuống khoảng {slope} mỗi kỳ (R² = {r2}).', 'The linear trend of {measure} is declining by about {slope} per period (R² = {r2}).'),
  T('uptrend', 'positive', 'Xu hướng tăng của {measure}', 'Upward trend in {measure}', 'Đường xu hướng tuyến tính của {measure} đi lên khoảng {slope} mỗi kỳ (R² = {r2}).', 'The linear trend of {measure} is rising by about {slope} per period (R² = {r2}).'),
  T('volatile', 'watch', '{measure} biến động mạnh', '{measure} is volatile', '{measure} có hệ số biến thiên {cv} giữa các kỳ, khiến việc lập kế hoạch kém ổn định.', '{measure} has a coefficient of variation of {cv} across periods, making planning less predictable.'),
  T('record_high', 'positive', '{measure} đạt mức cao nhất', '{measure} at its highest', '{measure} kỳ {cur_period} ({cur}) là mức cao nhất trong {n} kỳ có dữ liệu.', '{measure} in {cur_period} ({cur}) is the highest across {n} periods of data.'),
  T('record_low', 'warning', '{measure} ở mức thấp nhất', '{measure} at its lowest', '{measure} kỳ {cur_period} ({cur}) là mức thấp nhất trong {n} kỳ có dữ liệu.', '{measure} in {cur_period} ({cur}) is the lowest across {n} periods of data.'),
  T('deceleration', 'watch', 'Tăng trưởng {measure} chậm lại', '{measure} growth is slowing', 'Tốc độ tăng của {measure} chậm lại {accel} so với kỳ trước đó.', 'Growth of {measure} slowed by {accel} compared with the prior period.'),
  T('acceleration', 'opportunity', 'Tăng trưởng {measure} tăng tốc', '{measure} growth is accelerating', 'Tốc độ tăng của {measure} tăng thêm {accel} so với kỳ trước đó.', 'Growth of {measure} accelerated by {accel} compared with the prior period.'),
  T('top_entity_concentration', 'warning', 'Phụ thuộc vào một {dim}', 'Dependence on a single {dim}', '{dim} "{top}" chiếm {share} tổng {measure}. Mức phụ thuộc này làm tăng rủi ro nếu {dim} này thay đổi.', '{dim} "{top}" accounts for {share} of total {measure}. This level of dependence raises risk if it changes.'),
  T('top5_concentration', 'warning', 'Rủi ro tập trung Top 5 {dim}', 'Top 5 {dim} concentration risk', 'Top 5 {dim} chiếm {share} tổng {measure}.', 'The top 5 {dim} account for {share} of total {measure}.'),
  T('pareto_concentration', 'watch', 'Tập trung Pareto cao theo {dim}', 'High Pareto concentration by {dim}', 'Chỉ {share80} số {dim} tạo ra 80% {measure}; 20% {dim} hàng đầu đóng góp {top20}.', 'Only {share80} of {dim} generate 80% of {measure}; the top 20% contribute {top20}.'),
  T('dim_dominance', 'watch', '{dim} "{top}" chiếm ưu thế', '{dim} "{top}" dominates', '{dim} "{top}" đóng góp {share} tổng {measure}, gấp {lead}× {dim} đứng thứ hai.', '{dim} "{top}" contributes {share} of total {measure}, {lead}× the runner-up.'),
  T('segment_decline', 'warning', '{dim} "{worst}" giảm mạnh nhất', '{dim} "{worst}" declined the most', '{measure} của {dim} "{worst}" giảm {chg} trong kỳ {cur_period} so với kỳ trước; {dim} này chiếm {share} tổng {measure}.', '{measure} for {dim} "{worst}" fell {chg} in {cur_period} versus the previous period; it represents {share} of total {measure}.'),
  T('segment_growth', 'opportunity', '{dim} "{best}" tăng trưởng nổi bật', '{dim} "{best}" is growing fast', '{measure} của {dim} "{best}" tăng {chg} trong kỳ {cur_period}, đóng góp {share} tổng {measure}.', '{measure} for {dim} "{best}" grew {chg} in {cur_period}, contributing {share} of total {measure}.'),
  T('broad_decline', 'warning', 'Suy giảm diện rộng theo {dim}', 'Broad-based decline by {dim}', '{share} số {dim} có {measure} giảm trong kỳ gần nhất (bình quân {avg}).', '{share} of {dim} groups saw {measure} decline in the latest period (average {avg}).'),
  T('broad_growth', 'positive', 'Tăng trưởng diện rộng theo {dim}', 'Broad-based growth by {dim}', '{share} số {dim} có {measure} tăng trong kỳ gần nhất (bình quân {avg}).', '{share} of {dim} groups grew {measure} in the latest period (average {avg}).'),
  T('segment_divergence', 'watch', 'Phân hóa mạnh giữa các {dim}', 'Strong divergence across {dim}', 'Chênh lệch tăng trưởng giữa {dim} tốt nhất ("{best}", {best_chg}) và kém nhất ("{worst}", {worst_chg}) là {spread}.', 'Growth gap between the best {dim} ("{best}", {best_chg}) and the worst ("{worst}", {worst_chg}) is {spread}.'),
  T('long_tail', 'opportunity', 'Đuôi dài {dim} đóng góp thấp', 'Long tail of low-contributing {dim}', 'Có {count} {dim}, nhưng 20% hàng đầu đã chiếm {top20} {measure}. Các {dim} còn lại có thể cần chiến lược riêng.', 'There are {count} {dim}, yet the top 20% account for {top20} of {measure}. The remaining {dim} may need a distinct strategy.'),
  T('target_miss', 'warning', 'Chưa đạt mục tiêu', 'Below target', 'Kết quả đạt {ach} mục tiêu (thiếu {gap}).', 'Results reached {ach} of target (short by {gap}).'),
  T('target_miss_severe', 'critical', 'Thiếu hụt lớn so với mục tiêu', 'Large shortfall versus target', 'Kết quả chỉ đạt {ach} mục tiêu, thiếu {gap}.', 'Results reached only {ach} of target, a shortfall of {gap}.'),
  T('target_exceeded', 'positive', 'Vượt mục tiêu', 'Target exceeded', 'Kết quả đạt {ach} mục tiêu (vượt {gap}).', 'Results reached {ach} of target (exceeding by {gap}).'),
  T('target_near', 'watch', 'Sát mục tiêu', 'Close to target', 'Kết quả đạt {ach} mục tiêu — cần theo dõi để hoàn thành kế hoạch.', 'Results are at {ach} of target — worth monitoring to close the gap.'),
  T('target_trend_down', 'warning', 'Tỷ lệ đạt mục tiêu giảm', 'Target achievement falling', 'Tỷ lệ đạt mục tiêu kỳ {cur_period} là {cur}, giảm {chg} so với kỳ trước.', 'Target achievement in {cur_period} was {cur}, down {chg} versus the previous period.'),
  T('budget_overrun', 'warning', 'Vượt ngân sách', 'Budget overrun', 'Thực chi đạt {util} ngân sách, vượt {variance}.', 'Actual spend is {util} of budget, exceeding it by {variance}.'),
  T('budget_overrun_severe', 'critical', 'Vượt ngân sách nghiêm trọng', 'Severe budget overrun', 'Thực chi đạt {util} ngân sách, vượt {variance}.', 'Actual spend is {util} of budget, exceeding it by {variance}.'),
  T('budget_underuse', 'opportunity', 'Ngân sách chưa sử dụng hết', 'Budget under-utilised', 'Thực chi mới đạt {util} ngân sách (còn {variance}).', 'Actual spend is only {util} of budget ({variance} remaining).'),
  T('dept_overrun', 'watch', '{dim} "{top}" chiếm phần lớn chi tiêu', '{dim} "{top}" drives most spending', '{dim} "{top}" chiếm {share} tổng {measure}.', '{dim} "{top}" accounts for {share} of total {measure}.'),
  T('high_cost_ratio', 'watch', 'Tỷ lệ chi phí cao', 'High cost ratio', 'Chi phí đang chiếm {ratio} doanh thu.', 'Cost represents {ratio} of revenue.'),
  T('discount_heavy', 'watch', 'Chiết khấu cao', 'Heavy discounting', 'Chiết khấu chiếm {rate} doanh thu gộp.', 'Discounts represent {rate} of gross revenue.'),
  T('discount_rising', 'watch', 'Chiết khấu tăng', 'Discounts rising', 'Tỷ lệ chiết khấu tăng {chg} so với kỳ trước.', 'Discount rate rose {chg} versus the previous period.'),
  T('return_rate_high', 'warning', 'Tỷ lệ hoàn trả cao', 'High return rate', 'Tỷ lệ hoàn trả đang ở mức {rate}.', 'Return rate stands at {rate}.'),
  T('cancel_rate_high', 'warning', 'Tỷ lệ hủy cao', 'High cancellation rate', 'Tỷ lệ đơn hủy đang ở mức {rate}.', 'Cancellation rate stands at {rate}.'),
  T('aov_decline', 'watch', 'Giá trị đơn trung bình giảm', 'Average order value falling', 'Giá trị đơn trung bình giảm {chg} ({prev} → {cur}).', 'Average order value fell {chg} ({prev} → {cur}).'),
  T('aov_growth', 'positive', 'Giá trị đơn trung bình tăng', 'Average order value rising', 'Giá trị đơn trung bình tăng {chg} ({prev} → {cur}).', 'Average order value rose {chg} ({prev} → {cur}).'),
  T('customer_base_shrink', 'warning', 'Số khách hàng giảm', 'Customer base shrinking', 'Số khách hàng giao dịch giảm {chg} ({prev} → {cur}).', 'Active customers decreased {chg} ({prev} → {cur}).'),
  T('customer_base_growth', 'positive', 'Số khách hàng tăng', 'Customer base growing', 'Số khách hàng giao dịch tăng {chg} ({prev} → {cur}).', 'Active customers increased {chg} ({prev} → {cur}).'),
  T('defect_rate_high', 'warning', 'Tỷ lệ lỗi vượt ngưỡng', 'Defect rate above threshold', 'Tỷ lệ lỗi đang ở mức {rate} trên tổng sản lượng {output}.', 'Defect rate stands at {rate} on total output of {output}.'),
  T('defect_rate_critical', 'critical', 'Rủi ro chất lượng nghiêm trọng', 'Critical quality risk', 'Tỷ lệ lỗi {rate} — cao hơn đáng kể mức thông thường của sản xuất ổn định.', 'Defect rate of {rate} is well above typical levels for stable production.'),
  T('defect_rate_rising', 'warning', 'Tỷ lệ lỗi tăng', 'Defect rate rising', 'Tỷ lệ lỗi kỳ {cur_period} là {cur}, tăng {chg} so với kỳ trước.', 'Defect rate in {cur_period} was {cur}, up {chg} versus the previous period.'),
  T('quality_good', 'positive', 'Chất lượng sản xuất ổn định', 'Stable production quality', 'Tỷ lệ đạt chất lượng ở mức {rate}.', 'First pass yield is {rate}.'),
  T('downtime_rising', 'warning', 'Thời gian dừng máy tăng mạnh', 'Downtime rising sharply', 'Thời gian dừng kỳ {cur_period} tăng {chg} so với kỳ trước ({prev} → {cur}), ảnh hưởng tới ổn định vận hành.', 'Downtime in {cur_period} rose {chg} versus the previous period ({prev} → {cur}), affecting operational stability.'),
  T('output_below_plan', 'warning', 'Sản lượng dưới kế hoạch', 'Output below plan', 'Sản lượng thực tế đạt {ach} kế hoạch.', 'Actual output reached {ach} of plan.'),
  T('output_above_plan', 'positive', 'Sản lượng vượt kế hoạch', 'Output above plan', 'Sản lượng thực tế đạt {ach} kế hoạch.', 'Actual output reached {ach} of plan.'),
  T('ratio_hotspot', 'watch', '{dim} "{top}" có {metric} cao nhất', '{dim} "{top}" has the highest {metric}', '{metric} của {dim} "{top}" là {value}, so với bình quân {avg}.', '{metric} for {dim} "{top}" is {value} versus an average of {avg}.'),
  T('ratio_best', 'opportunity', '{dim} "{top}" hiệu quả nhất về {metric}', '{dim} "{top}" leads on {metric}', '{metric} của {dim} "{top}" đạt {value}, so với bình quân {avg}.', '{metric} for {dim} "{top}" is {value} versus an average of {avg}.'),
  T('ratio_low', 'watch', '{dim} "{top}" có {metric} thấp nhất', '{dim} "{top}" has the lowest {metric}', '{metric} của {dim} "{top}" chỉ đạt {value}, so với bình quân {avg}.', '{metric} for {dim} "{top}" is only {value} versus an average of {avg}.'),
  T('ratio_gap', 'watch', 'Chênh lệch lớn về {metric} giữa các {dim}', 'Large {metric} gap across {dim}', '{metric} cao nhất ({top}: {value}) gấp {lead}× mức thấp nhất ({bottom}: {low}).', 'Highest {metric} ({top}: {value}) is {lead}× the lowest ({bottom}: {low}).'),
  T('metric_rise_risk', 'warning', '{measure} tăng {chg}', '{measure} up {chg}', '{measure} kỳ {cur_period} tăng {chg} so với kỳ trước ({prev} → {cur}).', '{measure} in {cur_period} rose {chg} versus the previous period ({prev} → {cur}).'),
  T('metric_rise_critical', 'critical', '{measure} tăng mạnh {chg}', '{measure} surged {chg}', '{measure} kỳ {cur_period} tăng mạnh {chg} so với kỳ trước ({prev} → {cur}).', '{measure} in {cur_period} surged {chg} versus the previous period ({prev} → {cur}).'),
  T('metric_fall_good', 'positive', '{measure} giảm {chg}', '{measure} down {chg}', '{measure} kỳ {cur_period} giảm {chg} so với kỳ trước ({prev} → {cur}) — chuyển biến tích cực.', '{measure} in {cur_period} decreased {chg} versus the previous period ({prev} → {cur}) — a favourable change.'),
  T('risk_streak', 'warning', '{measure} tăng {n} kỳ liên tiếp', '{measure} up {n} periods in a row', '{measure} đã tăng liên tục trong {n} kỳ gần nhất, hiện ở mức {cur}.', '{measure} has increased for {n} consecutive periods and is now {cur}.'),
  T('net_negative', 'critical', 'Thu nhập ròng âm', 'Negative net income', 'Doanh thu trừ chi tiêu đang âm ({value}).', 'Revenue minus expenses is negative ({value}).'),
  T('supplier_dependency', 'watch', 'Phụ thuộc nhà cung cấp "{top}"', 'Dependence on supplier "{top}"', 'Nhà cung cấp "{top}" chiếm {share} tổng {measure}.', 'Supplier "{top}" accounts for {share} of total {measure}.'),
  T('segment_cost_surge', 'warning', '{measure} của {dim} "{top}" tăng mạnh', '{measure} surge in {dim} "{top}"', '{measure} của {dim} "{top}" tăng {chg} trong kỳ {cur_period} so với kỳ trước; {dim} này chiếm {share} tổng {measure}.', '{measure} for {dim} "{top}" rose {chg} in {cur_period} versus the previous period; it represents {share} of total {measure}.'),
  T('segment_cost_drop', 'positive', '{measure} của {dim} "{top}" giảm', '{measure} reduced in {dim} "{top}"', '{measure} của {dim} "{top}" giảm {chg} trong kỳ {cur_period}; {dim} này chiếm {share} tổng {measure}.', '{measure} for {dim} "{top}" fell {chg} in {cur_period}; it represents {share} of total {measure}.'),
  T('late_rate_rising', 'warning', 'Tỷ lệ đúng hạn giảm', 'On-time rate falling', 'Tỷ lệ đúng hạn kỳ {cur_period} là {cur}, giảm {chg} so với kỳ trước.', 'On-time rate in {cur_period} was {cur}, down {chg} versus the previous period.'),
  T('absence_rising', 'warning', 'Tỷ lệ vắng mặt tăng', 'Absence rate rising', 'Tỷ lệ vắng mặt kỳ {cur_period} là {cur}, tăng {chg} so với kỳ trước.', 'Absence rate in {cur_period} was {cur}, up {chg} versus the previous period.'),
  T('payroll_growth', 'watch', 'Quỹ lương tăng {chg}', 'Payroll up {chg}', 'Quỹ lương kỳ {cur_period} là {cur}, tăng {chg} so với kỳ trước.', 'Payroll in {cur_period} was {cur}, up {chg} versus the previous period.'),
  T('budget_overrun_period', 'warning', 'Kỳ gần nhất vượt ngân sách', 'Latest period over budget', 'Kỳ {cur_period}, thực chi đạt {util} ngân sách của kỳ.', 'In {cur_period}, actual spend reached {util} of the period budget.'),
  T('roas_falling', 'warning', 'ROAS giảm {chg}', 'ROAS down {chg}', 'ROAS kỳ {cur_period} là {cur}, giảm {chg} so với kỳ trước.', 'ROAS in {cur_period} was {cur}, down {chg} versus the previous period.'),
  T('stockout_risk', 'critical', 'Rủi ro hết hàng', 'Stock-out risk', '{rate} bản ghi tồn kho đang bằng 0.', '{rate} of inventory records are at zero stock.'),
  T('overstock_risk', 'warning', 'Rủi ro tồn kho cao (vốn lưu động)', 'Overstock / working capital risk', 'Vòng quay tồn kho chỉ {turnover} trong phạm vi dữ liệu, cho thấy hàng tồn có thể đang chiếm nhiều vốn.', 'Inventory turnover is only {turnover} within the data period, suggesting stock may tie up working capital.'),
  T('ctr_low', 'watch', 'Tỷ lệ nhấp thấp', 'Low click-through rate', 'CTR chung đạt {rate}.', 'Overall CTR is {rate}.'),
  T('roas_low', 'warning', 'Hiệu quả quảng cáo thấp', 'Low return on ad spend', 'Mỗi đồng chi phí quảng cáo mang về {roas} doanh thu.', 'Each unit of ad spend returns {roas} in revenue.'),
  T('roas_strong', 'positive', 'Hiệu quả quảng cáo tốt', 'Strong return on ad spend', 'Mỗi đồng chi phí quảng cáo mang về {roas} doanh thu.', 'Each unit of ad spend returns {roas} in revenue.'),
  T('cpl_rising', 'warning', 'Chi phí / lead tăng', 'Cost per lead rising', 'CPL kỳ {cur_period} là {cur}, tăng {chg} so với kỳ trước.', 'CPL in {cur_period} was {cur}, up {chg} versus the previous period.'),
  T('lead_conversion_low', 'watch', 'Chuyển đổi lead thấp', 'Low lead conversion', 'Tỷ lệ chuyển đổi lead chỉ đạt {rate}.', 'Lead conversion is only {rate}.'),
  T('absence_high', 'warning', 'Tỷ lệ vắng mặt cao', 'High absence rate', 'Tỷ lệ vắng mặt bình quân đạt {rate}.', 'Average absence rate is {rate}.'),
  T('performance_low', 'watch', 'Hiệu suất bình quân thấp', 'Low average performance', 'Điểm hiệu suất bình quân là {score} (thang tối đa ghi nhận {max}).', 'Average performance score is {score} (highest recorded {max}).'),
  T('payroll_concentration', 'watch', 'Quỹ lương tập trung vào "{top}"', 'Payroll concentrated in "{top}"', 'Phòng ban "{top}" chiếm {share} tổng quỹ lương.', 'Department "{top}" accounts for {share} of total payroll.'),
  T('tenure_low', 'watch', 'Thâm niên bình quân thấp', 'Low average tenure', 'Thâm niên bình quân chỉ {years} năm.', 'Average tenure is only {years} years.'),
  T('response_slow', 'warning', 'Thời gian phản hồi tăng', 'Response time increasing', 'Thời gian phản hồi bình quân kỳ {cur_period} là {cur}, tăng {chg}.', 'Average response time in {cur_period} was {cur}, up {chg}.'),
  T('satisfaction_low', 'warning', 'Mức hài lòng giảm', 'Satisfaction falling', 'Điểm hài lòng kỳ {cur_period} là {cur}, giảm {chg}.', 'Satisfaction in {cur_period} was {cur}, down {chg}.'),
  T('completion_low', 'warning', 'Tỷ lệ hoàn thành thấp', 'Low completion rate', 'Chỉ {rate} bản ghi ở trạng thái hoàn thành.', 'Only {rate} of records are in a completed state.'),
  T('late_rate_high', 'warning', 'Tỷ lệ trễ hạn cao', 'High late rate', 'Tỷ lệ đúng hạn chỉ đạt {rate}.', 'On-time rate is only {rate}.'),
  T('data_quality_low', 'watch', 'Chất lượng dữ liệu cần cải thiện', 'Data quality needs attention', 'Điểm chất lượng dữ liệu là {score}/100; một số kết luận có thể kém tin cậy.', 'Data quality score is {score}/100; some conclusions may be less reliable.'),
  T('yoy_growth', 'positive', '{measure} tăng so với cùng kỳ', '{measure} up year over year', '{measure} kỳ {cur_period} tăng {chg} so với cùng kỳ năm trước.', '{measure} in {cur_period} is up {chg} year over year.'),
  T('yoy_decline', 'warning', '{measure} giảm so với cùng kỳ', '{measure} down year over year', '{measure} kỳ {cur_period} giảm {chg} so với cùng kỳ năm trước.', '{measure} in {cur_period} is down {chg} year over year.'),
  T('below_average', 'watch', '{measure} thấp hơn bình quân', '{measure} below average', '{measure} kỳ {cur_period} thấp hơn {chg} so với bình quân các kỳ.', '{measure} in {cur_period} is {chg} below the period average.'),
  T('above_average', 'positive', '{measure} cao hơn bình quân', '{measure} above average', '{measure} kỳ {cur_period} cao hơn {chg} so với bình quân các kỳ.', '{measure} in {cur_period} is {chg} above the period average.'),
  T('quarter_decline', 'warning', '{measure} 3 kỳ gần nhất giảm', '{measure} down over the last 3 periods', 'Tổng {measure} 3 kỳ gần nhất giảm {chg} so với 3 kỳ trước đó.', 'Total {measure} over the last 3 periods is down {chg} versus the prior 3.'),
  T('quarter_growth', 'positive', '{measure} 3 kỳ gần nhất tăng', '{measure} up over the last 3 periods', 'Tổng {measure} 3 kỳ gần nhất tăng {chg} so với 3 kỳ trước đó.', 'Total {measure} over the last 3 periods is up {chg} versus the prior 3.'),
  T('anomalies_found', 'watch', 'Phát hiện {count} điểm bất thường', '{count} anomalies detected', 'Hệ thống phát hiện {count} điểm bất thường ({high} mức cao) trên các chỉ số chính.', '{count} anomalies were detected ({high} high severity) across key metrics.'),
  T('expense_growth', 'warning', 'Chi tiêu tăng nhanh', 'Expenses rising fast', 'Chi tiêu kỳ {cur_period} tăng {chg} so với kỳ trước ({prev} → {cur}).', 'Expenses in {cur_period} rose {chg} versus the previous period ({prev} → {cur}).'),
  T('salesperson_dependency', 'watch', 'Phụ thuộc vào nhân viên "{top}"', 'Dependence on salesperson "{top}"', 'Nhân viên "{top}" tạo ra {share} tổng doanh thu.', 'Salesperson "{top}" generates {share} of total revenue.'),
]

export const TEMPLATE_BY_ID = new Map(INSIGHT_TEMPLATES.map((t) => [t.id, t]))
