/* Bản Đồ Kiếm Tiền — dữ liệu (phần 1) — © Tân AI */
const CATS=[
 {id:"dautu",n:"Đầu tư tài chính",i:"📈",c:"#f5c451",d:"Để tiền làm việc cho bạn: tiết kiệm, cổ phiếu, quỹ, trái phiếu, vàng, tài sản số."},
 {id:"bds",n:"Bất động sản",i:"🏠",c:"#ff9f5a",d:"Kênh làm giàu kinh điển: cho thuê, homestay, đất nền, môi giới, cải tạo bán lại."},
 {id:"kinhdoanh",n:"Kinh doanh truyền thống",i:"🏪",c:"#ff6b8b",d:"Quán xá, cửa hàng, nhượng quyền, sản xuất, phân phối, buôn bán."},
 {id:"tmdt",n:"Thương mại điện tử",i:"🛒",c:"#ff7ad9",d:"Bán hàng trên sàn, TikTok Shop, dropshipping, Amazon, Print on Demand."},
 {id:"noidung",n:"Sáng tạo nội dung",i:"🎬",c:"#a78bfa",d:"YouTube, TikTok, blog, podcast, affiliate, KOC — biến sự chú ý thành tiền."},
 {id:"freelance",n:"Freelance & Kỹ năng",i:"💼",c:"#5cc8ff",d:"Bán thời gian & chuyên môn: lập trình, thiết kế, viết, dịch, marketing."},
 {id:"giaoduc",n:"Giáo dục & Tri thức",i:"🎓",c:"#3ddbd9",d:"Dạy học, khóa học online, coaching, đào tạo doanh nghiệp, ebook."},
 {id:"congnghe",n:"Công nghệ & AI",i:"🤖",c:"#2ee6a6",d:"SaaS, app, dịch vụ AI, tự động hóa, template số, game indie."},
 {id:"dichvu",n:"Dịch vụ & Nghề tay nghề",i:"🛠️",c:"#7dd87d",d:"Tài xế, sửa chữa, làm đẹp, sự kiện, nấu ăn, chăm sóc, du lịch."},
 {id:"nongnghiep",n:"Nông nghiệp & Chăn nuôi",i:"🌾",c:"#b5e550",d:"Rau sạch, cây ăn trái, chăn nuôi, thủy sản, nấm, yến, farmstay."},
 {id:"thudong",n:"Thu nhập thụ động",i:"💤",c:"#8fa8ff",d:"Kiếm tiền cả khi ngủ: cho thuê tài sản, bản quyền, máy tự động, tài sản số."},
 {id:"sunghiep",n:"Sự nghiệp & Việc làm",i:"🧭",c:"#ffb86b",d:"Tăng lương, nghề kỹ năng cao, làm remote cho nước ngoài, sales hoa hồng."}
];
const VON=["0đ – gần như không vốn","Dưới 10 triệu","10 – 100 triệu","100 triệu – 1 tỷ","Trên 1 tỷ"];
const VON_S=["0đ","< 10tr","10–100tr","100tr–1 tỷ","> 1 tỷ"];
const MODE={on:"Online",off:"Offline",mix:"Online + Offline"};
const SKILL={tech:"Công nghệ",creative:"Sáng tạo",sales:"Bán hàng & giao tiếp",hand:"Tay nghề",finance:"Phân tích & tài chính",teach:"Chia sẻ & giảng dạy",care:"Phục vụ & chăm sóc"};

const M=[
/* ===================== ĐẦU TƯ TÀI CHÍNH ===================== */
{id:"tietkiem",c:"dautu",n:"Gửi tiết kiệm ngân hàng",i:"🏦",d:"Cách an toàn nhất để giữ và tăng tiền nhẹ nhàng. Là nền móng cho quỹ dự phòng trước khi bước sang mọi kênh đầu tư khác.",v:1,k:1,r:1,t:"Ngay lập tức (theo kỳ hạn)",inc:"Lãi ~4–6%/năm",m:"mix",p:1,s:["finance"],
 st:["Lập quỹ dự phòng tối thiểu 3–6 tháng chi tiêu","So sánh lãi suất giữa các ngân hàng (gửi online thường cao hơn tại quầy)","Chia nhỏ thành nhiều sổ kỳ hạn khác nhau (bậc thang) để linh hoạt rút","Tái tục tự động và cộng dồn lãi để hưởng lãi kép"],
 pro:["Gần như không rủi ro, được bảo hiểm tiền gửi","Đơn giản, ai cũng làm được","Thanh khoản tốt"],con:["Lợi suất thấp, có lúc chỉ ngang lạm phát","Rút trước hạn mất lãi","Không giúp giàu nhanh"],
 tip:"Hãy coi tiết kiệm là “bãi đỗ” của tiền, không phải đích đến. Khi quỹ dự phòng đã đủ, phần dư nên chuyển sang kênh sinh lời cao hơn."},
{id:"quymo",c:"dautu",n:"Chứng chỉ quỹ mở & ETF",i:"🧺",d:"Ủy thác tiền cho chuyên gia hoặc mua cả “rổ” cổ phiếu chỉ số. Phù hợp người bận rộn muốn đầu tư dài hạn có kỷ luật.",v:1,k:2,r:3,t:"Dài hạn 3–10 năm",inc:"Kỳ vọng ~8–15%/năm dài hạn",m:"on",p:1,s:["finance"],
 st:["Mở tài khoản tại công ty quản lý quỹ hoặc qua app ngân hàng/chứng khoán","Chọn quỹ cổ phiếu, trái phiếu hoặc cân bằng theo khẩu vị rủi ro","Đầu tư định kỳ hàng tháng (DCA) — chỉ từ vài trăm nghìn","Giữ tối thiểu 3–5 năm, xem lại danh mục mỗi năm 1 lần"],
 pro:["Đa dạng hóa tự động","Không cần theo dõi bảng điện","Vốn khởi đầu rất nhỏ"],con:["Có phí quản lý","Biến động theo thị trường chung","Không “đánh bại” thị trường trong ngắn hạn"],
 tip:"DCA đều đặn + thời gian dài là công thức giúp người bình thường tích lũy tài sản hiệu quả nhất. Đừng dừng mua khi thị trường giảm — đó là lúc mua được giá rẻ."},
{id:"cophieu",c:"dautu",n:"Đầu tư cổ phiếu dài hạn",i:"📊",d:"Trở thành đồng sở hữu doanh nghiệp tốt và lớn lên cùng họ. Đầu tư giá trị theo trường phái Warren Buffett.",v:1,k:3,r:3,t:"Dài hạn 3–10+ năm",inc:"10–20%/năm nếu chọn đúng",m:"on",p:1,s:["finance"],
 st:["Học đọc báo cáo tài chính cơ bản: doanh thu, lợi nhuận, nợ, dòng tiền","Mở tài khoản chứng khoán (eKYC online 5 phút)","Chọn doanh nghiệp có lợi thế cạnh tranh, ban lãnh đạo tốt, định giá hợp lý","Giải ngân từng phần, đa dạng 5–10 mã ở các ngành khác nhau","Nắm giữ dài hạn, chỉ bán khi câu chuyện doanh nghiệp thay đổi"],
 pro:["Lợi nhuận dài hạn cao nhất trong các tài sản phổ biến","Thanh khoản cao","Được nhận cổ tức"],con:["Biến động mạnh, có lúc giảm 30–50%","Cần kiến thức và tâm lý vững","Dễ bị cuốn vào tin đồn"],
 tip:"Chỉ đầu tư tiền nhàn rỗi mà 5 năm tới bạn không cần dùng. Không vay margin khi chưa có kinh nghiệm."},
{id:"trading",c:"dautu",n:"Lướt sóng / Trading chứng khoán",i:"⚡",d:"Mua bán ngắn hạn dựa trên phân tích kỹ thuật và dòng tiền. Lợi nhuận nhanh nhưng phần lớn người mới thua lỗ.",v:2,k:5,r:5,t:"Vài ngày – vài tuần",inc:"Rất biến động: lãi lớn hoặc lỗ lớn",m:"on",p:0,s:["finance"],
 st:["Học phân tích kỹ thuật: xu hướng, hỗ trợ/kháng cự, khối lượng","Viết ra hệ thống giao dịch: điểm vào, điểm cắt lỗ, điểm chốt lời","Giao dịch thử bằng vốn nhỏ ít nhất 6 tháng, ghi nhật ký mọi lệnh","Quản trị vốn: mỗi lệnh không rủi ro quá 1–2% tài khoản"],
 pro:["Có thể sinh lời nhanh","Rèn tư duy kỷ luật","Tận dụng được cả thị trường đi ngang"],con:["Đa số trader nhỏ lẻ thua lỗ","Áp lực tâm lý cực lớn","Tốn thời gian theo dõi"],
 tip:"Cắt lỗ là kỹ năng số 1. Nếu không có kỷ luật cắt lỗ, đừng trading."},
{id:"traiphieu",c:"dautu",n:"Trái phiếu",i:"📜",d:"Cho Chính phủ hoặc doanh nghiệp vay tiền để nhận lãi cố định. Ổn định hơn cổ phiếu, lãi cao hơn tiết kiệm.",v:2,k:2,r:2,t:"1–5 năm",inc:"~5–10%/năm",m:"on",p:1,s:["finance"],
 st:["Phân biệt trái phiếu Chính phủ (an toàn) và doanh nghiệp (lãi cao, rủi ro cao)","Kiểm tra sức khỏe tài chính, tài sản đảm bảo, xếp hạng tín nhiệm của tổ chức phát hành","Mua qua công ty chứng khoán uy tín hoặc chứng chỉ quỹ trái phiếu","Đa dạng nhiều tổ chức phát hành, không dồn hết vào một mã"],
 pro:["Dòng tiền lãi đều đặn","Ít biến động","Phù hợp người thích ổn định"],con:["Rủi ro vỡ nợ với trái phiếu doanh nghiệp yếu","Thanh khoản thấp","Lợi suất bị giới hạn"],
 tip:"Lãi suất càng cao bất thường so với mặt bằng, rủi ro càng lớn. Quỹ trái phiếu là cách dễ nhất để tiếp cận cho người mới."},
{id:"vang",c:"dautu",n:"Vàng & kim loại quý",i:"🥇",d:"Tài sản trú ẩn hàng nghìn năm. Giữ giá trị khi lạm phát, khủng hoảng, đồng tiền mất giá.",v:1,k:1,r:2,t:"Dài hạn",inc:"Bảo toàn giá trị, tăng theo chu kỳ",m:"off",p:1,s:["finance"],
 st:["Xác định tỷ trọng hợp lý (thường 5–15% tài sản)","Chọn vàng miếng/nhẫn trơn của thương hiệu uy tín, giữ hóa đơn","Mua rải rác theo thời gian thay vì một lần","Bảo quản an toàn hoặc gửi ngân hàng"],
 pro:["Phòng thủ khi khủng hoảng","Dễ hiểu, dễ mua bán","Được tin tưởng toàn cầu"],con:["Không tạo dòng tiền","Chênh lệch mua – bán cao","Có giai đoạn đi ngang rất lâu"],
 tip:"Vàng là “bảo hiểm” cho tài sản, không phải cỗ máy sinh lời. Tránh mua đuổi khi giá đang nóng và chênh lệch mua bán lớn."},
{id:"crypto",c:"dautu",n:"Tài sản số (Crypto)",i:"🪙",d:"Bitcoin, Ethereum và hệ sinh thái blockchain. Tiềm năng lớn nhưng biến động cực mạnh, nhiều dự án lừa đảo.",v:1,k:4,r:5,t:"Không xác định",inc:"Có thể x lần hoặc mất trắng",m:"on",p:0,s:["finance","tech"],
 st:["Tìm hiểu kỹ công nghệ và khung pháp lý hiện hành tại nơi bạn sống","Chỉ dùng số tiền chấp nhận mất 100%","Ưu tiên tài sản vốn hóa lớn, tránh coin rác và dự án hứa lãi","Tự bảo quản ví, bảo mật seed phrase, bật xác thực 2 lớp"],
 pro:["Tiềm năng tăng trưởng cao","Giao dịch 24/7 toàn cầu","Công nghệ mới"],con:["Biến động 50–80% là bình thường","Rất nhiều lừa đảo, rug-pull","Rủi ro pháp lý và rủi ro sàn"],
 tip:"Không bao giờ tham gia dự án “cam kết lợi nhuận cố định hằng ngày” — đó gần như chắc chắn là mô hình Ponzi."},
{id:"cotuc",c:"dautu",n:"Đầu tư cổ tức",i:"💵",d:"Xây danh mục cổ phiếu trả cổ tức đều đặn để tạo dòng tiền thụ động hàng năm, tái đầu tư để lãi kép.",v:3,k:3,r:2,t:"5–15 năm để có dòng tiền đáng kể",inc:"Cổ tức ~5–8%/năm + tăng giá",m:"on",p:1,s:["finance"],
 st:["Lọc doanh nghiệp trả cổ tức tiền mặt đều đặn nhiều năm","Kiểm tra tỷ lệ chi trả bền vững (không vay nợ để trả cổ tức)","Mua tích lũy dần, tái đầu tư cổ tức","Theo dõi kết quả kinh doanh hàng quý"],
 pro:["Dòng tiền thụ động thật sự","Ít áp lực hơn lướt sóng","Lãi kép mạnh theo thời gian"],con:["Cần vốn lớn để sống được từ cổ tức","Tăng trưởng có thể chậm","Cổ tức có thể bị cắt"],
 tip:"Quy tắc 4%: muốn nhận 20 triệu/tháng từ cổ tức ~6%, bạn cần danh mục khoảng 4 tỷ. Hãy bắt đầu từ sớm."},
{id:"thienthan",c:"dautu",n:"Đầu tư thiên thần / Startup",i:"🦄",d:"Rót vốn vào startup giai đoạn sớm để đổi lấy cổ phần. Phần lớn thất bại, nhưng một thương vụ thắng có thể gấp hàng chục lần.",v:4,k:5,r:5,t:"5–10 năm",inc:"0 hoặc x10–x100",m:"mix",p:1,s:["finance","sales"],
 st:["Tham gia mạng lưới nhà đầu tư thiên thần, sự kiện khởi nghiệp","Đánh giá đội ngũ sáng lập, thị trường, sản phẩm, mô hình kinh doanh","Đầu tư nhỏ vào nhiều startup (10–20 công ty)","Đồng hành, hỗ trợ kết nối để tăng giá trị khoản đầu tư"],
 pro:["Tiềm năng lợi nhuận cực lớn","Được đồng hành cùng người tài","Tạo tác động xã hội"],con:["Đa số startup thất bại","Vốn bị “khóa” nhiều năm","Đòi hỏi kinh nghiệm và quan hệ"],
 tip:"Không bao giờ dành quá 10% tài sản cho đầu tư mạo hiểm."},
{id:"phaisinh",c:"dautu",n:"Chứng khoán phái sinh",i:"🎢",d:"Hợp đồng tương lai chỉ số với đòn bẩy cao, cho phép kiếm lời cả khi thị trường tăng hay giảm. Chỉ dành cho người có kinh nghiệm.",v:2,k:5,r:5,t:"Trong ngày – vài ngày",inc:"Biến động rất lớn theo đòn bẩy",m:"on",p:0,s:["finance"],
 st:["Thành thạo chứng khoán cơ sở trước","Học cơ chế ký quỹ, đòn bẩy, ngày đáo hạn","Luôn đặt lệnh cắt lỗ tự động","Giao dịch khối lượng nhỏ cho đến khi có lãi ổn định nhiều tháng"],
 pro:["Kiếm lời cả hai chiều","Vốn yêu cầu thấp nhờ đòn bẩy","Thanh khoản cao"],con:["Đòn bẩy khuếch đại thua lỗ","Áp lực tâm lý rất lớn","Không phù hợp người mới"],
 tip:"Chỉ giao dịch trên sàn được cấp phép hợp pháp. Tránh xa các sàn forex/“quyền chọn nhị phân” không phép quảng cáo trên mạng."},

/* ===================== BẤT ĐỘNG SẢN ===================== */
{id:"chothuenha",c:"bds",n:"Mua nhà/căn hộ cho thuê",i:"🏢",d:"Mua bất động sản để cho thuê dài hạn: vừa có dòng tiền hàng tháng, vừa hưởng tăng giá tài sản theo thời gian.",v:4,k:3,r:2,t:"Ngay khi có khách thuê",inc:"Lợi suất thuê ~3–6%/năm + tăng giá",m:"off",p:1,s:["finance"],
 st:["Chọn khu vực gần trường, khu công nghiệp, văn phòng — nơi nhu cầu thuê ổn định","Tính dòng tiền: tiền thuê – lãi vay – phí quản lý – sửa chữa","Kiểm tra pháp lý kỹ (sổ, quy hoạch, tranh chấp)","Trang bị nội thất vừa đủ, ký hợp đồng rõ ràng, đặt cọc","Thuê dịch vụ quản lý nếu có nhiều căn"],
 pro:["Tài sản hữu hình, giữ giá tốt","Thu nhập thụ động hàng tháng","Có thể dùng đòn bẩy ngân hàng"],con:["Vốn rất lớn, thanh khoản chậm","Rủi ro khách thuê, trống phòng","Chi phí bảo trì, thuế"],
 tip:"Đừng chỉ nhìn giá tăng — một bất động sản tốt phải tự “nuôi” được khoản vay bằng tiền thuê."},
{id:"homestay",c:"bds",n:"Homestay / Airbnb / Căn hộ dịch vụ",i:"🛏️",d:"Cho thuê ngắn ngày theo đêm cho khách du lịch, công tác. Lợi suất cao hơn cho thuê dài hạn nhưng cần vận hành.",v:3,k:3,r:3,t:"1–3 tháng",inc:"Lợi suất 8–20%/năm tùy công suất",m:"mix",p:0,s:["care","creative","sales"],
 st:["Chọn vị trí du lịch/trung tâm, kiểm tra quy định cho thuê ngắn ngày","Thuê hoặc mua căn hộ, thiết kế đẹp “sống ảo”, đủ tiện nghi","Đăng trên Airbnb, Booking, Agoda với ảnh chuyên nghiệp","Chuẩn hóa quy trình dọn phòng, check-in tự động","Tối ưu đánh giá 5 sao và giá linh hoạt theo mùa"],
 pro:["Lợi suất cao","Có thể bắt đầu bằng cách thuê lại nhà","Mở rộng thành chuỗi"],con:["Phụ thuộc mùa du lịch","Vận hành vất vả","Rủi ro pháp lý, hàng xóm"],
 tip:"Đánh giá của khách là tài sản lớn nhất. Một chi tiết nhỏ như nước suối, bản đồ ăn uống viết tay có thể đổi lấy hàng chục đánh giá 5 sao."},
{id:"datnen",c:"bds",n:"Đầu tư đất nền dài hạn",i:"🗺️",d:"Mua đất ở khu vực có tiềm năng hạ tầng, đô thị hóa để chờ tăng giá. Kênh làm giàu của nhiều thế hệ.",v:4,k:4,r:4,t:"3–10 năm",inc:"Có thể x2–x5 nếu đúng vùng",m:"off",p:1,s:["finance","sales"],
 st:["Nghiên cứu quy hoạch hạ tầng: đường cao tốc, sân bay, khu công nghiệp","Đi thực địa, hỏi người dân bản địa, kiểm tra pháp lý tại cơ quan chức năng","Chỉ mua đất có sổ riêng, đúng quy hoạch, có lối đi","Không dùng đòn bẩy quá cao; chuẩn bị tinh thần giữ lâu"],
 pro:["Biên lợi nhuận lớn","Ít chi phí bảo trì","Tài sản để lại cho con cháu"],con:["Không tạo dòng tiền","Rủi ro sốt ảo, quy hoạch treo","Thanh khoản rất kém khi thị trường trầm lắng"],
 tip:"Mua khi thị trường im ắng, bán khi đám đông hào hứng. Tránh xa “dự án ma” và đất phân lô chưa có pháp lý."},
{id:"moigioi",c:"bds",n:"Môi giới bất động sản",i:"🤝",d:"Kết nối người mua – người bán và nhận hoa hồng. Không cần vốn, thu nhập không giới hạn nếu giỏi bán hàng.",v:0,k:3,r:2,t:"1–6 tháng cho giao dịch đầu",inc:"Hoa hồng 1–3% giá trị giao dịch",m:"mix",p:0,s:["sales"],
 st:["Tham gia sàn/công ty môi giới uy tín để được đào tạo và có nguồn hàng","Học chứng chỉ hành nghề môi giới theo quy định","Chọn một khu vực/phân khúc để trở thành chuyên gia","Xây kênh cá nhân (Facebook, TikTok, Zalo) để có khách hàng","Chăm sóc khách sau giao dịch để có giới thiệu"],
 pro:["Không cần vốn","Thu nhập cao","Học được kiến thức BĐS để tự đầu tư sau này"],con:["Thu nhập thất thường","Cạnh tranh khốc liệt","Phụ thuộc chu kỳ thị trường"],
 tip:"Người môi giới giỏi bán sự tin tưởng chứ không bán nhà. Trung thực về nhược điểm sản phẩm sẽ giúp bạn có khách quay lại."},
{id:"thuelai",c:"bds",n:"Thuê lại & cho thuê lại (Sublease)",i:"🔁",d:"Thuê nguyên căn nhà dài hạn, cải tạo thành phòng trọ/căn hộ mini/homestay để cho thuê lại với giá cao hơn.",v:2,k:3,r:3,t:"1–3 tháng",inc:"5–30 triệu/tháng mỗi căn",m:"off",p:0,s:["sales","care"],
 st:["Tìm nhà nguyên căn giá tốt, đàm phán hợp đồng 3–5 năm, cho phép cho thuê lại","Cải tạo, ngăn phòng hợp lý, đảm bảo phòng cháy chữa cháy","Định giá và đăng tin cho thuê trên nhiều kênh","Quản lý thu tiền, điện nước bằng phần mềm"],
 pro:["Không cần mua bất động sản","Hoàn vốn nhanh","Dễ nhân rộng"],con:["Phụ thuộc chủ nhà","Rủi ro trống phòng","Cần quản lý liên tục"],
 tip:"Hợp đồng gốc là sinh mệnh của mô hình: ghi rõ quyền cho thuê lại, giá cố định nhiều năm và điều khoản đền bù."},
{id:"flip",c:"bds",n:"Mua nhà cũ cải tạo bán lại (Flip)",i:"🔨",d:"Mua nhà xuống cấp giá rẻ, sửa chữa nâng cấp, bán lại có lời. Mô hình phổ biến ở Mỹ và các đô thị lớn.",v:4,k:4,r:4,t:"3–12 tháng mỗi thương vụ",inc:"Lợi nhuận 10–30%/thương vụ",m:"off",p:0,s:["hand","creative","finance"],
 st:["Tìm nhà có vị trí tốt nhưng xuống cấp, giá dưới thị trường","Ước tính chi phí cải tạo chính xác (cộng dự phòng 20%)","Cải tạo những phần tăng giá nhiều nhất: bếp, nhà vệ sinh, mặt tiền","Chụp ảnh đẹp, bán nhanh để giảm chi phí vốn"],
 pro:["Lợi nhuận nhanh hơn chờ tăng giá","Tạo giá trị thực","Có thể làm lặp lại"],con:["Vốn lớn","Rủi ro đội chi phí","Phụ thuộc thanh khoản thị trường"],
 tip:"Lợi nhuận được tạo ra lúc mua, không phải lúc bán. Mua đủ rẻ là yếu tố quyết định."},
{id:"reits",c:"bds",n:"Quỹ REITs / Quỹ bất động sản",i:"🏙️",d:"Đầu tư bất động sản chỉ với vài triệu đồng qua chứng chỉ quỹ, nhận cổ tức từ tiền cho thuê văn phòng, trung tâm thương mại.",v:1,k:2,r:3,t:"Dài hạn",inc:"Cổ tức + tăng giá ~6–10%/năm",m:"on",p:1,s:["finance"],
 st:["Tìm hiểu các quỹ REIT/quỹ BĐS đang hoạt động hợp pháp","Đọc bản cáo bạch: tài sản, công suất cho thuê, phí","Mua qua tài khoản chứng khoán","Giữ dài hạn và tái đầu tư cổ tức"],
 pro:["Vốn nhỏ","Không phải quản lý nhà","Đa dạng nhiều bất động sản"],con:["Lựa chọn còn hạn chế ở một số thị trường","Biến động theo lãi suất","Có phí quản lý"],
 tip:"Với người trẻ ít vốn, REITs là cửa ngõ để “sở hữu” bất động sản trước khi đủ tiền mua căn đầu tiên."},
{id:"matbang",c:"bds",n:"Cho thuê mặt bằng, kho bãi",i:"🏬",d:"Sở hữu hoặc thuê dài hạn mặt bằng kinh doanh, kho xưởng để cho các doanh nghiệp, cửa hàng thuê lại.",v:4,k:3,r:2,t:"Ngay khi có khách thuê",inc:"Lợi suất 5–8%/năm",m:"off",p:1,s:["finance","sales"],
 st:["Chọn vị trí mặt tiền đông đúc hoặc gần cảng, KCN cho kho bãi","Xây dựng/cải tạo phù hợp nhu cầu khách thuê","Ký hợp đồng dài hạn có điều khoản tăng giá định kỳ","Kiểm tra năng lực tài chính khách thuê"],
 pro:["Hợp đồng dài, ổn định","Khách thuê tự lo nội thất","Lợi suất cao hơn nhà ở"],con:["Vốn rất lớn","Trống mặt bằng thì thiệt hại lớn","Phụ thuộc kinh tế"],
 tip:"Kho bãi gần các trung tâm thương mại điện tử đang là phân khúc tăng trưởng mạnh."},

/* ===================== KINH DOANH TRUYỀN THỐNG ===================== */
{id:"cafe",c:"kinhdoanh",n:"Quán cà phê / Trà sữa",i:"☕",d:"Mô hình được nhiều người mơ ước. Lợi nhuận tốt nếu vị trí đúng và có điểm khác biệt, nhưng tỷ lệ đóng cửa cũng rất cao.",v:3,k:4,r:4,t:"6–18 tháng hoàn vốn",inc:"10–100+ triệu/tháng",m:"off",p:0,s:["creative","care","sales"],
 st:["Xác định khách hàng mục tiêu và concept khác biệt","Khảo sát vị trí: lưu lượng người, đối thủ, chỗ để xe","Lập bảng dự toán vốn + quỹ duy trì ít nhất 6 tháng","Chuẩn hóa công thức, quy trình pha chế, đào tạo nhân viên","Marketing khai trương + bán online qua app giao đồ ăn"],
 pro:["Biên lợi nhuận đồ uống cao","Xây được thương hiệu","Có thể nhân rộng chuỗi"],con:["Cạnh tranh rất khốc liệt","Tiền mặt bằng cao","Vận hành mệt"],
 tip:"Đừng mở quán vì “thích cà phê”. Hãy mở vì bạn đã tính được điểm hòa vốn và có lý do khiến khách chọn bạn thay vì quán bên cạnh."},
{id:"quanan",c:"kinhdoanh",n:"Quán ăn / Xe đẩy / Food stall",i:"🍜",d:"Bán món ăn sở trường: từ xe bánh mì, gánh xôi đến quán cơm văn phòng. Nhu cầu ăn uống không bao giờ biến mất.",v:2,k:3,r:3,t:"1–6 tháng",inc:"10–60 triệu/tháng",m:"off",p:0,s:["hand","care"],
 st:["Chọn 1–3 món đặc trưng làm thật ngon","Bắt đầu nhỏ: xe đẩy, gian hàng, bán online trước","Tìm nguồn nguyên liệu ổn định, giá tốt","Đăng ký trên GrabFood, ShopeeFood","Chuẩn hóa công thức để mở rộng"],
 pro:["Vốn khởi đầu linh hoạt","Thu tiền mặt hằng ngày","Khách quen trung thành"],con:["Vất vả, thời gian dài","Vệ sinh an toàn thực phẩm","Phụ thuộc vị trí"],
 tip:"Một món làm xuất sắc đánh bại một thực đơn 50 món làm bình thường."},
{id:"taphoa",c:"kinhdoanh",n:"Tiệm tạp hóa / Minimart",i:"🧃",d:"Cửa hàng bán lẻ nhu yếu phẩm cho khu dân cư. Biên lợi nhuận mỏng nhưng ổn định, khách đều.",v:3,k:3,r:2,t:"3–12 tháng",inc:"10–40 triệu/tháng",m:"off",p:0,s:["sales","care"],
 st:["Chọn mặt bằng trong khu dân cư đông, ít đối thủ","Tìm nhà phân phối, đại lý cấp 1 để lấy hàng giá tốt","Dùng phần mềm quản lý bán hàng, tồn kho","Bổ sung dịch vụ: giao hàng tận nhà, thanh toán QR, bán online qua Zalo"],
 pro:["Nhu cầu thiết yếu, ổn định","Rủi ro thấp","Dễ vận hành"],con:["Lợi nhuận mỏng","Cạnh tranh với chuỗi lớn","Trói buộc thời gian"],
 tip:"Hiểu khách trong bán kính 500m: bạn có thể thắng chuỗi lớn bằng sự thân quen, giao nhanh và bán chịu có kiểm soát."},
{id:"franchise",c:"kinhdoanh",n:"Nhượng quyền thương hiệu (Franchise)",i:"🏷️",d:"Mua quyền kinh doanh một thương hiệu đã thành công: có sẵn công thức, quy trình, nhận diện và hỗ trợ.",v:3,k:3,r:3,t:"6–24 tháng hoàn vốn",inc:"Tùy thương hiệu",m:"off",p:0,s:["sales","finance"],
 st:["So sánh nhiều thương hiệu: phí nhượng quyền, phí hằng tháng, tỷ lệ cửa hàng sống sót","Nói chuyện trực tiếp với các chủ cửa hàng đang vận hành","Đọc kỹ hợp đồng: độc quyền khu vực, thời hạn, điều kiện chấm dứt","Tuân thủ chuẩn vận hành và tập trung bán hàng địa phương"],
 pro:["Giảm rủi ro thử nghiệm","Có sẵn thương hiệu","Được đào tạo, hỗ trợ"],con:["Phí nhượng quyền, phí duy trì","Ít tự do sáng tạo","Phụ thuộc danh tiếng chuỗi"],
 tip:"Hỏi chủ nhượng quyền: “Bao nhiêu cửa hàng đã đóng cửa trong 2 năm qua?” — câu trả lời nói lên tất cả."},
{id:"cho",c:"kinhdoanh",n:"Bán hàng chợ / Sạp / Chợ đêm",i:"🧺",d:"Hình thức buôn bán lâu đời nhất: thuê sạp ở chợ, chợ đêm, hội chợ. Vốn nhỏ, học được kỹ năng bán hàng thực chiến.",v:1,k:2,r:2,t:"Ngay lập tức",inc:"5–30 triệu/tháng",m:"off",p:0,s:["sales"],
 st:["Chọn mặt hàng phù hợp khách của chợ (quần áo, phụ kiện, đồ ăn vặt…)","Lấy hàng từ chợ đầu mối, xưởng sản xuất","Trưng bày bắt mắt, giá rõ ràng","Kết bạn Zalo với khách để bán thêm online"],
 pro:["Vốn rất nhỏ","Học bán hàng thực tế","Tiền về hằng ngày"],con:["Phụ thuộc thời tiết","Thu nhập không ổn định","Vất vả"],
 tip:"Chợ đêm, hội chợ cuối tuần là nơi tuyệt vời để thử nghiệm sản phẩm trước khi đầu tư lớn."},
{id:"daily",c:"kinhdoanh",n:"Đại lý / Nhà phân phối",i:"🚚",d:"Làm cầu nối giữa nhà sản xuất và điểm bán lẻ: nhận hàng số lượng lớn, phân phối cho các cửa hàng trong khu vực.",v:3,k:3,r:3,t:"3–12 tháng",inc:"Chiết khấu 5–30%",m:"off",p:0,s:["sales","finance"],
 st:["Chọn ngành hàng có nhu cầu ổn định (FMCG, vật liệu xây dựng, nông sản…)","Đàm phán với nhà sản xuất về chiết khấu, khu vực độc quyền","Xây mạng lưới điểm bán và đội giao hàng","Quản lý công nợ chặt chẽ"],
 pro:["Doanh thu lớn","Quan hệ bền vững","Có thể độc quyền khu vực"],con:["Vốn lưu động lớn","Rủi ro công nợ","Biên lợi nhuận bị ép"],
 tip:"Công nợ là kẻ giết chết nhà phân phối. Hãy có chính sách hạn mức nợ rõ ràng cho từng khách."},
{id:"xuong",c:"kinhdoanh",n:"Xưởng sản xuất nhỏ",i:"🏭",d:"Tự sản xuất sản phẩm: may mặc, đồ gỗ, đồ thủ công, thực phẩm đóng gói, mỹ phẩm handmade… để bán sỉ và lẻ.",v:3,k:4,r:3,t:"6–18 tháng",inc:"Biên 20–50%",m:"off",p:0,s:["hand","creative"],
 st:["Chọn sản phẩm bạn có lợi thế (tay nghề, nguyên liệu địa phương)","Làm mẫu, thử nghiệm thị trường với số lượng nhỏ","Đăng ký kinh doanh, công bố chất lượng, nhãn mác","Bán sỉ cho cửa hàng + bán lẻ online","Đầu tư máy móc khi đơn hàng ổn định"],
 pro:["Kiểm soát chất lượng và giá","Biên lợi nhuận tốt","Xây thương hiệu riêng"],con:["Vốn máy móc, nhân công","Quản lý phức tạp","Rủi ro tồn kho"],
 tip:"Bán trước, sản xuất sau: nhận đặt hàng, thu cọc rồi mới sản xuất số lượng lớn."},
{id:"xnk",c:"kinhdoanh",n:"Xuất nhập khẩu & Buôn hàng",i:"🚢",d:"Mua hàng ở nơi rẻ, bán ở nơi đắt — nguyên lý từ thời Con đường Tơ lụa. Nhập hàng quốc tế hoặc xuất nông sản, thủ công ra nước ngoài.",v:3,k:4,r:3,t:"3–12 tháng",inc:"Biên 15–50%",m:"mix",p:0,s:["sales","finance"],
 st:["Học thủ tục hải quan, Incoterms, thanh toán quốc tế","Tìm nhà cung cấp trên Alibaba, hội chợ, hoặc người mua qua các sàn B2B","Đặt hàng mẫu, kiểm định chất lượng","Tính đủ chi phí: thuế, vận chuyển, lưu kho","Bắt đầu lô nhỏ, mở rộng dần"],
 pro:["Biên chênh lệch lớn","Thị trường toàn cầu","Có thể làm sỉ quy mô lớn"],con:["Thủ tục phức tạp","Rủi ro tỷ giá, chất lượng","Vốn lưu động lớn"],
 tip:"Thuê dịch vụ logistics/ủy thác xuất nhập khẩu cho vài lô đầu để học quy trình mà giảm rủi ro."},
{id:"thoivu",c:"kinhdoanh",n:"Kinh doanh thời vụ",i:"🧧",d:"Bán hàng theo mùa: giỏ quà Tết, bánh trung thu, hoa 8/3, 14/2, đồ Noel, áo mưa mùa mưa, đồ mùa tựu trường…",v:1,k:2,r:2,t:"Vài tuần",inc:"5–100 triệu/mùa",m:"mix",p:0,s:["sales","creative"],
 st:["Lên lịch các mùa cao điểm trong năm","Chuẩn bị hàng và nhập trước 1–2 tháng","Bán qua mạng xã hội + quầy tạm","Thanh lý hàng tồn ngay sau mùa"],
 pro:["Vốn quay vòng nhanh","Có thể làm song song công việc chính","Nhu cầu cao, chốt đơn dễ"],con:["Rủi ro tồn kho sau mùa","Cạnh tranh tăng vọt","Không ổn định"],
 tip:"Bán cho doanh nghiệp (quà tặng nhân viên, đối tác) thường có đơn lớn hơn bán lẻ rất nhiều."},

/* ===================== THƯƠNG MẠI ĐIỆN TỬ ===================== */
{id:"san",c:"tmdt",n:"Bán hàng trên Shopee / Lazada / Tiki",i:"🛍️",d:"Mở gian hàng trên sàn thương mại điện tử để tiếp cận hàng triệu người mua mà không cần mặt bằng.",v:1,k:2,r:2,t:"1–3 tháng",inc:"Vài triệu – hàng trăm triệu/tháng",m:"on",p:0,s:["sales","creative"],
 st:["Chọn ngách sản phẩm: có nhu cầu, ít cạnh tranh, lợi nhuận ≥ 30%","Tìm nguồn hàng: xưởng, chợ sỉ, nhập khẩu","Chụp ảnh đẹp, viết tiêu đề chuẩn SEO trên sàn","Chạy quảng cáo nội sàn, tham gia chương trình khuyến mãi","Chăm sóc đánh giá, tối ưu tỷ lệ chuyển đổi"],
 pro:["Lượng khách khổng lồ sẵn có","Vốn ban đầu nhỏ","Hệ thống vận chuyển, thanh toán có sẵn"],con:["Cạnh tranh giá gắt","Phí sàn ngày càng tăng","Phụ thuộc thuật toán"],
 tip:"Đừng cạnh tranh bằng giá rẻ nhất. Cạnh tranh bằng ảnh đẹp hơn, mô tả rõ hơn, đóng gói tốt hơn và phản hồi nhanh hơn."},
{id:"tiktokshop",c:"tmdt",n:"TikTok Shop & Livestream bán hàng",i:"📱",d:"Kết hợp video ngắn và livestream để bán hàng. “Mua sắm giải trí” đang bùng nổ, người mới vẫn có cơ hội nổ đơn.",v:1,k:3,r:2,t:"1–3 tháng",inc:"Vài triệu – hàng tỷ/tháng",m:"on",p:0,s:["creative","sales"],
 st:["Mở TikTok Shop, chọn sản phẩm có tính “trình diễn” cao","Làm 1–3 video ngắn/ngày: review, trước-sau, mẹo dùng","Livestream đều đặn cùng khung giờ, có kịch bản chốt đơn","Hợp tác với KOC/affiliate để họ bán giúp","Phân tích video nào ra đơn để nhân bản"],
 pro:["Lan truyền tự nhiên mạnh","Chi phí thấp","Xây được thương hiệu cá nhân"],con:["Cần làm nội dung liên tục","Thuật toán thay đổi","Áp lực livestream"],
 tip:"3 giây đầu quyết định tất cả. Mở video bằng kết quả/vấn đề, không mở bằng lời chào."},
{id:"dropship",c:"tmdt",n:"Dropshipping",i:"📦",d:"Bán hàng không cần ôm hàng: khách đặt trên cửa hàng của bạn, nhà cung cấp giao trực tiếp. Bạn tập trung marketing.",v:1,k:3,r:3,t:"1–6 tháng",inc:"Biên 20–40%",m:"on",p:0,s:["tech","sales"],
 st:["Tạo website bằng Shopify/Haravan/WordPress hoặc bán trên sàn","Tìm nhà cung cấp dropship uy tín, đặt mẫu kiểm tra","Test sản phẩm bằng quảng cáo ngân sách nhỏ","Giữ sản phẩm thắng, tắt sản phẩm thua","Dần chuyển sang thương hiệu riêng"],
 pro:["Không rủi ro tồn kho","Vốn thấp","Bán toàn cầu"],con:["Kiểm soát chất lượng kém","Giao hàng chậm","Biên mỏng do chi phí quảng cáo"],
 tip:"Dropshipping là trường học marketing tuyệt vời. Người thành công thường dùng nó để tìm sản phẩm thắng, sau đó nhập hàng làm thương hiệu riêng."},
{id:"amazon",c:"tmdt",n:"Amazon FBA",i:"🌎",d:"Bán hàng trên Amazon tại Mỹ, châu Âu, Nhật: gửi hàng vào kho Amazon, họ lo lưu kho, giao hàng, chăm sóc khách.",v:3,k:4,r:3,t:"6–12 tháng",inc:"Biên 20–35% bằng USD",m:"on",p:0,s:["sales","finance","tech"],
 st:["Nghiên cứu sản phẩm bằng công cụ (Helium10, Jungle Scout)","Tìm nhà sản xuất (Việt Nam là lợi thế cho đồ gỗ, thủ công, may mặc)","Đăng ký tài khoản người bán, đăng ký thương hiệu","Tối ưu listing: ảnh, tiêu đề, A+ content","Chạy Amazon PPC và thu thập đánh giá hợp lệ"],
 pro:["Thị trường giàu sức mua","Amazon lo hậu cần","Thu nhập bằng ngoại tệ"],con:["Vốn và kiến thức lớn","Chính sách nghiêm ngặt","Cạnh tranh toàn cầu"],
 tip:"Sản phẩm “Made in Vietnam” có câu chuyện văn hóa thường có lợi thế khác biệt trên Amazon và Etsy."},
{id:"pod",c:"tmdt",n:"Print on Demand (POD)",i:"👕",d:"Thiết kế hình in lên áo, cốc, tranh… chỉ khi có đơn đối tác mới in và giao. Không vốn, không tồn kho.",v:0,k:2,r:1,t:"1–6 tháng",inc:"Vài trăm – vài nghìn USD/tháng",m:"on",p:1,s:["creative","tech"],
 st:["Chọn ngách: nghề nghiệp, sở thích, thú cưng, câu nói vui…","Thiết kế bằng Canva, Illustrator hoặc AI tạo ảnh (chú ý bản quyền)","Đăng bán trên Etsy, Redbubble, Amazon Merch, TeeSpring","Nghiên cứu từ khóa, đăng số lượng lớn","Nhân bản các thiết kế bán chạy"],
 pro:["Không vốn, không tồn kho","Thiết kế 1 lần bán mãi mãi","Bán toàn cầu"],con:["Lợi nhuận mỗi đơn thấp","Cạnh tranh lớn","Rủi ro vi phạm bản quyền/thương hiệu"],
 tip:"Tuyệt đối không dùng hình nhân vật, logo, thương hiệu của người khác — tài khoản có thể bị khóa vĩnh viễn."},
{id:"d2c",c:"tmdt",n:"Website & Thương hiệu riêng (D2C)",i:"✨",d:"Xây thương hiệu bán trực tiếp đến người tiêu dùng qua website riêng, kiểm soát hoàn toàn dữ liệu khách hàng.",v:2,k:4,r:3,t:"6–18 tháng",inc:"Biên 40–70%",m:"on",p:0,s:["creative","tech","sales"],
 st:["Định vị thương hiệu: khách hàng là ai, vì sao chọn bạn","Phát triển sản phẩm khác biệt, bao bì đẹp","Làm website, kết nối thanh toán, vận chuyển","Kéo traffic: SEO, quảng cáo, KOL, email marketing","Xây cộng đồng khách hàng trung thành"],
 pro:["Biên lợi nhuận cao","Sở hữu thương hiệu và dữ liệu","Giá trị doanh nghiệp lớn"],con:["Tốn chi phí kéo khách","Cần nhiều kỹ năng","Thời gian xây dựng lâu"],
 tip:"Đầu tư vào danh sách email/Zalo khách hàng — đó là tài sản không ai lấy đi được."},
{id:"social",c:"tmdt",n:"Bán hàng qua Facebook / Zalo",i:"💬",d:"Bán online qua trang cá nhân, fanpage, nhóm và Zalo. Cách khởi nghiệp phổ biến nhất của người Việt.",v:1,k:2,r:2,t:"Vài tuần",inc:"3–50 triệu/tháng",m:"on",p:0,s:["sales","creative"],
 st:["Xây trang cá nhân đáng tin: ảnh thật, chia sẻ đời sống, phản hồi khách","Chọn sản phẩm bạn thật sự dùng và hiểu","Đăng nội dung giá trị 80%, bán hàng 20%","Chăm sóc khách qua Zalo, tạo nhóm khách hàng thân thiết"],
 pro:["Dễ bắt đầu","Tận dụng quan hệ sẵn có","Chi phí thấp"],con:["Phụ thuộc nền tảng","Dễ bị coi là “spam”","Khó mở rộng lớn"],
 tip:"Người ta mua từ người họ tin. Hãy bán bằng câu chuyện thật, không bán bằng ảnh copy."},
{id:"secondhand",c:"tmdt",n:"Mua bán đồ cũ / Săn đồ secondhand",i:"♻️",d:"Săn đồ cũ giá rẻ (quần áo vintage, đồ điện tử, sách, đồ cổ, sneaker) rồi làm sạch, bán lại giá cao hơn.",v:1,k:2,r:2,t:"Vài tuần",inc:"3–30 triệu/tháng",m:"mix",p:0,s:["sales"],
 st:["Chọn ngách bạn am hiểu để định giá đúng","Săn hàng ở chợ đồ cũ, thanh lý, kiện hàng, hội nhóm","Làm sạch, sửa chữa, chụp ảnh đẹp","Bán trên Facebook Marketplace, Chợ Tốt, sàn TMĐT, live"],
 pro:["Vốn nhỏ","Biên lợi nhuận cao","Thân thiện môi trường"],con:["Nguồn hàng không đều","Mất thời gian săn và xử lý","Khó tăng quy mô"],
 tip:"Kiến thức chuyên sâu là lợi nhuận: người biết phân biệt hàng hiếm luôn mua được giá hời."},
{id:"order",c:"tmdt",n:"Order hàng quốc tế",i:"✈️",d:"Nhận đặt hộ hàng từ Trung Quốc, Mỹ, Nhật, Hàn… thu phí dịch vụ hoặc chênh lệch giá.",v:1,k:2,r:2,t:"Vài tuần",inc:"Phí 5–15%/đơn",m:"on",p:0,s:["sales"],
 st:["Chọn thị trường nguồn và tìm đơn vị vận chuyển uy tín","Xây bảng giá rõ ràng: giá gốc, phí ship, phí dịch vụ","Thu cọc trước khi đặt hàng","Theo dõi đơn, cập nhật khách thường xuyên"],
 pro:["Không ôm hàng","Vốn nhỏ","Có thể làm thêm"],con:["Rủi ro thất lạc, hư hỏng","Thời gian giao lâu","Thủ tục thuế, hải quan"],
 tip:"Minh bạch là chìa khóa: báo trước mọi chi phí và thời gian để khách không bất ngờ."}
];
