/* Bản Đồ Kiếm Tiền — dữ liệu (phần 2) — © Tân AI */
M.push(
/* ===================== SÁNG TẠO NỘI DUNG ===================== */
{id:"youtube",c:"noidung",n:"Kênh YouTube",i:"▶️",d:"Làm video về chủ đề bạn giỏi hoặc đam mê. Kiếm tiền từ quảng cáo, tài trợ, affiliate, bán sản phẩm riêng.",v:1,k:3,r:2,t:"6–24 tháng",inc:"0 – hàng trăm triệu/tháng",m:"on",p:1,s:["creative","teach"],
 st:["Chọn ngách: giao điểm của đam mê, chuyên môn và nhu cầu người xem","Nghiên cứu từ khóa, đối thủ, video đang thịnh hành","Đăng đều đặn 1–2 video/tuần, tối ưu tiêu đề + thumbnail","Đạt điều kiện bật kiếm tiền (YouTube Partner Program)","Đa dạng nguồn thu: tài trợ, affiliate, khóa học, membership"],
 pro:["Video cũ vẫn kiếm tiền nhiều năm","Thu nhập toàn cầu","Xây thương hiệu cá nhân mạnh"],con:["Rất lâu mới có thu nhập","Cần kiên trì và kỹ năng","Phụ thuộc thuật toán"],
 tip:"100 video đầu tiên là học phí. Đừng bỏ cuộc trước khi chạm mốc đó."},
{id:"tiktok",c:"noidung",n:"Nhà sáng tạo TikTok / Reels / Shorts",i:"🎵",d:"Làm video ngắn để xây lượng theo dõi nhanh, sau đó kiếm tiền từ quảng cáo, booking, affiliate, bán hàng.",v:0,k:3,r:2,t:"3–12 tháng",inc:"Vài triệu – hàng trăm triệu/tháng",m:"on",p:0,s:["creative"],
 st:["Chọn một chủ đề cố định và một “nhân vật” dễ nhớ","Đăng 1–3 video/ngày, thử nhiều định dạng","Phân tích số liệu: tỷ lệ xem hết, chia sẻ","Khi có ~10.000 follow, nhận booking và affiliate","Chuyển người xem sang kênh riêng (Zalo, email, sản phẩm)"],
 pro:["Tăng trưởng nhanh nhất","Chỉ cần điện thoại","Nhiều nguồn thu"],con:["Xu hướng thay đổi rất nhanh","Áp lực sáng tạo liên tục","Thu nhập không ổn định"],
 tip:"Nhất quán quan trọng hơn hoàn hảo. Một video “ổn” mỗi ngày tốt hơn một video “hoàn hảo” mỗi tháng."},
{id:"blog",c:"noidung",n:"Blog / Website SEO",i:"✍️",d:"Viết bài chất lượng để lên top Google, kiếm tiền từ quảng cáo hiển thị, affiliate và khách hàng tiềm năng.",v:1,k:3,r:2,t:"6–18 tháng",inc:"Vài trăm – vài nghìn USD/tháng",m:"on",p:1,s:["creative","tech","teach"],
 st:["Chọn ngách có nhu cầu tìm kiếm và giá trị thương mại","Mua tên miền, hosting, cài WordPress","Nghiên cứu từ khóa, viết bài chuyên sâu trả lời đúng câu hỏi","Xây backlink tự nhiên, tối ưu tốc độ","Gắn quảng cáo (AdSense, Ezoic) và affiliate"],
 pro:["Thu nhập thụ động lâu dài","Tài sản có thể bán","Không cần xuất hiện"],con:["Lâu có kết quả","Cập nhật thuật toán có thể làm mất traffic","Cạnh tranh với AI search"],
 tip:"Viết từ trải nghiệm thật (đã dùng, đã thử, có ảnh tự chụp) — đó là thứ AI và đối thủ khó sao chép."},
{id:"affiliate",c:"noidung",n:"Tiếp thị liên kết (Affiliate)",i:"🔗",d:"Giới thiệu sản phẩm của người khác bằng link riêng và nhận hoa hồng khi có người mua.",v:0,k:3,r:1,t:"1–6 tháng",inc:"Hoa hồng 3–50%",m:"on",p:1,s:["creative","sales"],
 st:["Đăng ký chương trình affiliate: Shopee, Lazada, TikTok, AccessTrade, Amazon…","Chọn sản phẩm bạn thật sự dùng và phù hợp người theo dõi","Làm nội dung review, so sánh, hướng dẫn","Đặt link ở bio, mô tả, bài viết, nhóm","Theo dõi số liệu và tối ưu sản phẩm chuyển đổi tốt"],
 pro:["Không vốn, không hàng","Không chăm sóc khách","Kết hợp với mọi kênh nội dung"],con:["Hoa hồng có thể bị giảm","Phụ thuộc nền tảng","Cần lượng truy cập lớn"],
 tip:"Sản phẩm phần mềm, khóa học, dịch vụ tài chính thường có hoa hồng cao và định kỳ hàng tháng."},
{id:"podcast",c:"noidung",n:"Podcast",i:"🎙️",d:"Chương trình âm thanh/video dài về một chủ đề. Thính giả trung thành cao, giá trị tài trợ lớn.",v:1,k:3,r:2,t:"6–24 tháng",inc:"Tài trợ, membership, sự kiện",m:"on",p:0,s:["creative","teach"],
 st:["Chọn chủ đề và định dạng (độc thoại, phỏng vấn, đối thoại)","Đầu tư micro tốt, phòng thu ít vang","Phát trên Spotify, Apple Podcasts, YouTube","Cắt clip ngắn để quảng bá trên mạng xã hội","Bán tài trợ, gói hội viên, tổ chức sự kiện"],
 pro:["Khán giả trung thành","Kết nối người có ảnh hưởng","Dễ làm khi đang bận việc khác"],con:["Tăng trưởng chậm","Khó đo lường","Cần nội dung sâu"],
 tip:"Mời khách mời có tệp người theo dõi riêng — mỗi tập là một lần “mượn” khán giả mới."},
{id:"newsletter",c:"noidung",n:"Bản tin trả phí (Newsletter)",i:"📨",d:"Gửi thư định kỳ chứa phân tích, kiến thức độc quyền. Người đọc trả phí hằng tháng hoặc nhà tài trợ trả tiền quảng cáo.",v:0,k:3,r:1,t:"6–12 tháng",inc:"Thu nhập định kỳ",m:"on",p:1,s:["creative","finance","teach"],
 st:["Chọn ngách cụ thể mà bạn có góc nhìn sâu","Dùng Substack, Beehiiv, Ghost hoặc tự xây","Gửi miễn phí để xây danh sách, sau đó mở gói trả phí","Đăng tóm tắt lên mạng xã hội để kéo người đăng ký"],
 pro:["Sở hữu trực tiếp người đọc","Doanh thu định kỳ","Chi phí thấp"],con:["Cần viết đều đặn chất lượng","Tăng trưởng chậm","Khó thuyết phục trả phí"],
 tip:"1.000 người trả 100.000đ/tháng = 100 triệu/tháng. Bạn không cần hàng triệu người theo dõi."},
{id:"koc",c:"noidung",n:"KOL / KOC – Review sản phẩm",i:"⭐",d:"Người có ảnh hưởng nhận booking từ nhãn hàng để trải nghiệm và giới thiệu sản phẩm đến người theo dõi.",v:0,k:3,r:2,t:"3–12 tháng",inc:"500k – hàng chục triệu/booking",m:"on",p:0,s:["creative","sales"],
 st:["Xây kênh với tệp người theo dõi rõ ràng (mẹ bỉm, làm đẹp, công nghệ…)","Tạo media kit: số liệu, giá booking, case cũ","Đăng ký trên nền tảng kết nối KOC hoặc chủ động liên hệ nhãn hàng","Giữ uy tín: chỉ nhận sản phẩm phù hợp và trung thực"],
 pro:["Nhận sản phẩm miễn phí","Thu nhập cao khi có tiếng","Linh hoạt"],con:["Uy tín dễ mất","Áp lực hình ảnh","Phụ thuộc xu hướng"],
 tip:"KOC nhỏ (micro) có tỷ lệ tương tác cao thường được nhãn hàng ưa chuộng hơn KOL lớn nhưng xa cách."},
{id:"stream",c:"noidung",n:"Livestream game / Streaming",i:"🎮",d:"Phát trực tiếp chơi game, trò chuyện, sáng tạo. Kiếm tiền từ donate, quà tặng, quảng cáo, tài trợ.",v:2,k:4,r:3,t:"6–24 tháng",inc:"0 – hàng trăm triệu/tháng",m:"on",p:0,s:["creative"],
 st:["Đầu tư máy tính, mic, webcam, mạng ổn định","Chọn nền tảng và khung giờ phát cố định","Tương tác với người xem, xây cộng đồng Discord/nhóm","Cắt highlight đăng TikTok, YouTube để kéo người mới"],
 pro:["Biến sở thích thành nghề","Cộng đồng gắn kết","Nhiều nguồn thu"],con:["Rất cạnh tranh","Ảnh hưởng sức khỏe nếu thức khuya","Thu nhập bất ổn"],
 tip:"Tính cách mới là sản phẩm, game chỉ là bối cảnh."},
{id:"fanpage",c:"noidung",n:"Fanpage / Nhóm cộng đồng",i:"👥",d:"Xây fanpage hoặc group lớn về một chủ đề, kiếm tiền từ quảng cáo, đăng bài tài trợ, bán hàng, affiliate.",v:0,k:2,r:2,t:"3–12 tháng",inc:"Vài triệu – vài chục triệu/tháng",m:"on",p:0,s:["creative","sales"],
 st:["Chọn chủ đề có cộng đồng rõ ràng (nghề nghiệp, địa phương, sở thích)","Đăng nội dung hữu ích, khuyến khích thành viên tương tác","Đặt luật nhóm, kiểm duyệt chống spam","Bán bài quảng cáo, hợp tác với nhãn hàng phù hợp"],
 pro:["Không vốn","Tài sản cộng đồng giá trị","Hiệu ứng lan truyền"],con:["Phụ thuộc chính sách nền tảng","Quản trị tốn thời gian","Dễ bị đánh sập"],
 tip:"Luôn có kênh dự phòng (Zalo, email, website) để không mất cộng đồng nếu tài khoản gặp sự cố."},
{id:"viettruyen",c:"noidung",n:"Viết truyện / Viết sách",i:"📚",d:"Xuất bản sách, viết truyện online trả phí theo chương, tự xuất bản ebook trên Amazon Kindle.",v:0,k:3,r:1,t:"6–24 tháng",inc:"Nhuận bút, tiền bản quyền",m:"on",p:1,s:["creative","teach"],
 st:["Chọn thể loại có độc giả trả tiền (ngôn tình, kỹ năng, kinh doanh…)","Viết đều mỗi ngày, xây độc giả trên nền tảng truyện","Hợp tác nhà xuất bản hoặc tự xuất bản","Bán bản quyền chuyển thể, sách nói, bản dịch"],
 pro:["Thu nhập bản quyền lâu dài","Nâng tầm uy tín cá nhân","Có thể làm từ bất cứ đâu"],con:["Thu nhập ban đầu thấp","Cần kỷ luật cao","Khó đoán thành công"],
 tip:"Một cuốn sách là “danh thiếp” mạnh nhất: nó mở ra cơ hội diễn thuyết, đào tạo, tư vấn có giá trị gấp nhiều lần nhuận bút."},

/* ===================== FREELANCE ===================== */
{id:"dev",c:"freelance",n:"Lập trình viên Freelance",i:"💻",d:"Nhận dự án web, app, phần mềm, tự động hóa cho khách hàng trong nước và quốc tế.",v:1,k:4,r:2,t:"1–3 tháng",inc:"20–150+ triệu/tháng",m:"on",p:0,s:["tech"],
 st:["Thành thạo một stack được thị trường cần (web, mobile, data…)","Làm 3–5 dự án mẫu đưa lên GitHub/portfolio","Tạo hồ sơ trên Upwork, Freelancer, Toptal, LinkedIn","Bắt đầu với dự án nhỏ, xin đánh giá tốt","Nâng giá và chuyển sang khách quen, hợp đồng dài hạn"],
 pro:["Thu nhập cao, có thể bằng USD","Làm từ xa","Nhu cầu lớn"],con:["Áp lực deadline","Khách hàng khó tính","Phải liên tục học"],
 tip:"Chuyên môn hóa sâu (ví dụ: “Shopify cho thương hiệu mỹ phẩm”) giúp bạn tính giá cao gấp 3 lần lập trình viên đa năng."},
{id:"design",c:"freelance",n:"Thiết kế đồ họa / UI-UX",i:"🎨",d:"Thiết kế logo, bộ nhận diện, banner, giao diện web/app cho doanh nghiệp và cá nhân.",v:1,k:3,r:2,t:"1–3 tháng",inc:"10–80 triệu/tháng",m:"on",p:0,s:["creative","tech"],
 st:["Học công cụ: Figma, Photoshop, Illustrator, Canva","Xây portfolio trên Behance, Dribbble","Nhận việc trên Fiverr, Upwork, hội nhóm freelancer","Đóng gói dịch vụ có giá rõ ràng","Bán thêm template, mockup, font"],
 pro:["Sáng tạo, thú vị","Làm từ xa","Kết hợp được với bán sản phẩm số"],con:["Khách sửa nhiều lần","AI làm giảm giá việc đơn giản","Cạnh tranh nhiều"],
 tip:"Dùng AI như trợ lý để làm nhanh gấp đôi — và tập trung vào tư duy chiến lược thương hiệu mà AI chưa thay thế được."},
{id:"content",c:"freelance",n:"Viết content / Copywriting",i:"🖋️",d:"Viết bài website, quảng cáo, kịch bản video, email marketing, trang bán hàng cho doanh nghiệp.",v:0,k:2,r:1,t:"Vài tuần",inc:"5–50 triệu/tháng",m:"on",p:0,s:["creative","sales"],
 st:["Luyện viết mỗi ngày, học công thức copywriting (AIDA, PAS)","Làm mẫu cho 3–5 thương hiệu giả định","Nhận việc trên hội nhóm, Fiverr, agency","Chuyên sâu một ngành (bất động sản, tài chính, y tế…)"],
 pro:["Không vốn","Có thể làm thêm","Kỹ năng dùng cả đời"],con:["Giá thấp khi mới bắt đầu","AI cạnh tranh mảng viết cơ bản","Phụ thuộc phản hồi khách"],
 tip:"Copywriter giỏi được trả tiền theo kết quả bán hàng, không theo số chữ. Hãy đo lường và chứng minh hiệu quả."},
{id:"dich",c:"freelance",n:"Dịch thuật / Phiên dịch",i:"🌐",d:"Dịch tài liệu, phụ đề, website, hoặc phiên dịch trực tiếp cho sự kiện, đàm phán, du lịch.",v:0,k:3,r:1,t:"Vài tuần",inc:"10–60 triệu/tháng",m:"mix",p:0,s:["teach","care"],
 st:["Đạt trình độ ngoại ngữ cao, có chứng chỉ nếu được","Chọn chuyên ngành: pháp lý, y tế, kỹ thuật, game…","Đăng ký với công ty dịch thuật, nền tảng freelance","Học dùng công cụ CAT và AI để tăng năng suất","Nhận phiên dịch sự kiện, hội thảo để tăng thu nhập"],
 pro:["Nhu cầu ổn định","Làm linh hoạt","Phiên dịch có thù lao cao"],con:["Dịch máy làm giảm giá việc cơ bản","Áp lực độ chính xác","Cần chuyên môn sâu"],
 tip:"Ngôn ngữ hiếm (Hàn, Nhật, Đức) và lĩnh vực chuyên ngành có thù lao cao hơn nhiều so với dịch Anh–Việt phổ thông."},
{id:"edit",c:"freelance",n:"Dựng video / Motion graphics",i:"🎞️",d:"Nhu cầu video bùng nổ: dựng video YouTube, TikTok, quảng cáo, đám cưới, sự kiện cho nhà sáng tạo và doanh nghiệp.",v:1,k:3,r:1,t:"1–2 tháng",inc:"10–60 triệu/tháng",m:"on",p:0,s:["creative","tech"],
 st:["Học CapCut, Premiere, DaVinci Resolve, After Effects","Dựng lại video mẫu để làm portfolio","Liên hệ YouTuber, nhãn hàng, agency nhận việc","Ký hợp đồng tháng với nhà sáng tạo để có thu nhập ổn định"],
 pro:["Nhu cầu rất cao","Làm từ xa","Kết hợp sáng tạo và kỹ thuật"],con:["Tốn thời gian","Cần máy cấu hình tốt","Deadline gắt"],
 tip:"Nhận làm “trọn gói hằng tháng” cho 3–5 nhà sáng tạo là cách ổn định thu nhập tốt nhất."},
{id:"ads",c:"freelance",n:"Chạy quảng cáo / Digital Marketing",i:"🎯",d:"Quản lý quảng cáo Facebook, Google, TikTok, SEO cho doanh nghiệp. Kỹ năng được trả tiền theo hiệu quả.",v:1,k:3,r:2,t:"1–3 tháng",inc:"10–100 triệu/tháng",m:"on",p:0,s:["tech","sales","finance"],
 st:["Học nền tảng quảng cáo và đo lường (Pixel, GA4, chuyển đổi)","Tự chạy thử với ngân sách nhỏ để có case thật","Nhận khách nhỏ, chứng minh kết quả bằng số liệu","Tính phí cố định + % ngân sách hoặc theo kết quả","Mở rộng thành agency"],
 pro:["Kỹ năng doanh nghiệp nào cũng cần","Có thể phát triển thành agency","Dùng được cho kinh doanh của chính mình"],con:["Nền tảng thay đổi liên tục","Áp lực kết quả","Khách hay so sánh giá"],
 tip:"Marketer giỏi nhất là người hiểu kinh doanh của khách: biên lợi nhuận, giá trị vòng đời khách hàng, không chỉ giá mỗi click."},
{id:"va",c:"freelance",n:"Trợ lý ảo (Virtual Assistant)",i:"🗂️",d:"Hỗ trợ từ xa cho doanh nhân, nhà sáng tạo: quản lý email, lịch, chăm sóc khách, nhập liệu, quản lý mạng xã hội.",v:0,k:1,r:1,t:"Vài tuần",inc:"5–30 triệu/tháng (hoặc 4–15 USD/giờ)",m:"on",p:0,s:["care","tech"],
 st:["Thành thạo công cụ văn phòng, Google Workspace, Notion, Canva","Có tiếng Anh giao tiếp tốt để nhận khách nước ngoài","Tạo hồ sơ trên OnlineJobs, Upwork, LinkedIn","Tạo quy trình làm việc chuyên nghiệp, báo cáo đều đặn"],
 pro:["Dễ bắt đầu","Làm từ xa","Có thể thành quản lý vận hành"],con:["Thu nhập ban đầu khiêm tốn","Lệch múi giờ","Công việc lặp lại"],
 tip:"Học thêm tự động hóa (Zapier, Make, AI) để nâng cấp từ VA thành “chuyên gia vận hành” với mức phí cao hơn."},
{id:"photo",c:"freelance",n:"Nhiếp ảnh & Quay phim",i:"📷",d:"Chụp ảnh cưới, kỷ yếu, sản phẩm, sự kiện, profile doanh nhân, quay TVC cho doanh nghiệp.",v:2,k:3,r:2,t:"1–6 tháng",inc:"10–100 triệu/tháng",m:"off",p:0,s:["creative","care"],
 st:["Đầu tư thiết bị cơ bản phù hợp ngách","Luyện tay nghề, chụp miễn phí/giá rẻ để có portfolio","Xây Instagram, fanpage, TikTok chia sẻ hậu trường","Đóng gói dịch vụ, giá rõ ràng, hợp đồng chuyên nghiệp"],
 pro:["Nghề sáng tạo, gặp gỡ nhiều người","Thù lao tốt mùa cao điểm","Bán thêm ảnh stock"],con:["Thiết bị đắt","Theo mùa","Cạnh tranh giá"],
 tip:"Chụp sản phẩm cho shop online là ngách ổn định quanh năm, không theo mùa như ảnh cưới."},
{id:"ketoan",c:"freelance",n:"Kế toán / Thuế / Pháp lý tự do",i:"🧾",d:"Làm dịch vụ kế toán, báo cáo thuế, thành lập doanh nghiệp, tư vấn pháp lý cho hộ kinh doanh và doanh nghiệp nhỏ.",v:0,k:3,r:1,t:"1–3 tháng",inc:"1–3 triệu/khách/tháng",m:"mix",p:0,s:["finance"],
 st:["Có chứng chỉ, kinh nghiệm chuyên môn phù hợp","Đóng gói dịch vụ theo tháng cho doanh nghiệp nhỏ","Tìm khách qua giới thiệu, hội doanh nhân, online","Dùng phần mềm để phục vụ nhiều khách cùng lúc"],
 pro:["Thu nhập định kỳ ổn định","Nhu cầu bắt buộc theo luật","Ít cạnh tranh về giá"],con:["Trách nhiệm pháp lý cao","Mùa quyết toán rất bận","Quy định thay đổi"],
 tip:"20 khách × 2 triệu/tháng = 40 triệu thu nhập định kỳ — đây là một trong những nghề tự do ổn định nhất."},
{id:"voice",c:"freelance",n:"Lồng tiếng / Voice-over",i:"🗣️",d:"Đọc quảng cáo, thuyết minh phim, sách nói, video doanh nghiệp, bài giảng e-learning.",v:1,k:3,r:1,t:"1–3 tháng",inc:"500k – vài triệu/bản thu",m:"on",p:0,s:["creative"],
 st:["Luyện giọng, phát âm chuẩn, cảm xúc","Đầu tư micro thu âm và xử lý cách âm cơ bản","Làm demo nhiều giọng (quảng cáo, kể chuyện, tin tức)","Đăng ký với studio, nền tảng freelance"],
 pro:["Làm tại nhà","Thù lao/giờ cao","Nghề độc đáo"],con:["Cạnh tranh với giọng AI","Cần năng khiếu","Việc không đều"],
 tip:"Sách nói và e-learning là thị trường đang tăng mạnh, cần giọng đọc dài hơi và truyền cảm."}
);
