/* Bản Đồ Kiếm Tiền — dữ liệu (phần 3) — © Tân AI */
M.push(
/* ===================== GIÁO DỤC ===================== */
{id:"giasu",c:"giaoduc",n:"Gia sư (offline & online)",i:"📖",d:"Dạy kèm các môn học, luyện thi, ngoại ngữ, năng khiếu. Nghề kiếm tiền phổ biến của sinh viên và giáo viên.",v:0,k:2,r:1,t:"Vài tuần",inc:"150k – 1 triệu/buổi",m:"mix",p:0,s:["teach"],
 st:["Chọn môn bạn giỏi nhất và nhóm học sinh phù hợp","Đăng ký trung tâm gia sư hoặc tự tìm qua hội nhóm phụ huynh","Chuẩn bị giáo án, theo dõi tiến bộ học sinh","Mở lớp nhóm nhỏ để tăng thu nhập/giờ","Dạy online để phục vụ học sinh mọi tỉnh thành"],
 pro:["Không vốn","Giờ giấc linh hoạt","Ý nghĩa"],con:["Thu nhập theo giờ, có giới hạn","Mùa hè/Tết ít lớp","Đi lại nhiều nếu dạy offline"],
 tip:"Kết quả của học sinh là quảng cáo tốt nhất. Một phụ huynh hài lòng giới thiệu cho bạn 3 phụ huynh khác."},
{id:"khoahoc",c:"giaoduc",n:"Khóa học online",i:"🖥️",d:"Đóng gói kiến thức thành khóa học video, bán một lần cho hàng nghìn học viên.",v:1,k:3,r:2,t:"3–12 tháng",inc:"Vài triệu – hàng tỷ/năm",m:"on",p:1,s:["teach","creative"],
 st:["Xác định vấn đề cụ thể mà khóa học giải quyết","Bán trước (pre-sale) để kiểm chứng nhu cầu","Quay bài giảng ngắn gọn, có bài tập thực hành","Đăng trên Udemy, Unica, Gitiho hoặc nền tảng riêng","Xây phễu: nội dung miễn phí → webinar → khóa học"],
 pro:["Làm một lần bán nhiều lần","Biên lợi nhuận rất cao","Xây uy tín chuyên gia"],con:["Cần thương hiệu cá nhân","Cạnh tranh nội dung miễn phí","Phải cập nhật nội dung"],
 tip:"Người ta không mua kiến thức, họ mua sự chuyển đổi. Hãy bán “kết quả sau 30 ngày” thay vì “30 bài giảng”."},
{id:"coach",c:"giaoduc",n:"Coaching / Mentoring 1:1",i:"🧑‍🏫",d:"Hướng dẫn trực tiếp cá nhân đạt mục tiêu: sự nghiệp, kinh doanh, sức khỏe, tài chính, kỹ năng.",v:0,k:3,r:1,t:"1–3 tháng",inc:"500k – 10 triệu/buổi",m:"mix",p:0,s:["teach","sales","care"],
 st:["Xác định chuyên môn đã được chứng minh bằng kết quả","Coach miễn phí 5–10 người đầu để có lời chứng thực","Đóng gói chương trình 4–12 tuần có giá rõ ràng","Tìm khách qua nội dung, giới thiệu, LinkedIn"],
 pro:["Thu nhập/giờ rất cao","Vốn gần như bằng 0","Tác động sâu"],con:["Giới hạn bởi thời gian","Cần uy tín","Khó mở rộng"],
 tip:"Chuyển từ 1:1 sang coaching nhóm để phục vụ nhiều người hơn mà không tăng giờ làm."},
{id:"trainer",c:"giaoduc",n:"Đào tạo doanh nghiệp / Trainer",i:"🎤",d:"Thiết kế và giảng dạy chương trình đào tạo cho nhân viên doanh nghiệp: kỹ năng mềm, bán hàng, quản lý, marketing, AI…",v:0,k:4,r:1,t:"3–12 tháng",inc:"5–50 triệu/buổi đào tạo",m:"off",p:0,s:["teach","sales"],
 st:["Có chuyên môn và kinh nghiệm thực chiến được chứng minh","Thiết kế chương trình có mục tiêu đo lường được","Hợp tác với công ty đào tạo hoặc tự bán trực tiếp cho phòng nhân sự","Xây thương hiệu cá nhân qua sách, bài viết, diễn thuyết"],
 pro:["Thù lao cao","Uy tín xã hội","Khách hàng doanh nghiệp lớn"],con:["Cần nhiều năm xây uy tín","Áp lực đứng lớp","Doanh nghiệp cắt ngân sách khi khó khăn"],
 tip:"Đào tạo về AI ứng dụng cho doanh nghiệp đang là ngách có nhu cầu tăng mạnh nhất hiện nay."},
{id:"ebook",c:"giaoduc",n:"Ebook / Tài liệu / Template",i:"📘",d:"Bán sản phẩm số: ebook, bộ tài liệu, checklist, template Excel/Notion/Canva, bộ prompt AI.",v:0,k:2,r:1,t:"1–3 tháng",inc:"Vài triệu – vài chục triệu/tháng",m:"on",p:1,s:["teach","creative"],
 st:["Tìm vấn đề người ta sẵn sàng trả tiền để giải quyết nhanh","Tạo sản phẩm số gọn, dễ dùng","Bán trên Gumroad, Etsy, website, hoặc qua Zalo/Facebook","Dùng nội dung miễn phí để dẫn khách"],
 pro:["Chi phí sản xuất 1 lần","Không giao hàng","Biên lợi nhuận gần 100%"],con:["Dễ bị sao chép","Giá bán thấp","Cần kênh bán hàng"],
 tip:"Template giúp tiết kiệm thời gian (lập kế hoạch tài chính, quản lý shop) thường bán tốt hơn ebook lý thuyết."},
{id:"membership",c:"giaoduc",n:"Cộng đồng Membership trả phí",i:"🔐",d:"Xây cộng đồng kín thu phí hằng tháng/năm: học tập, kết nối, nội dung độc quyền, hỏi đáp trực tiếp.",v:0,k:3,r:2,t:"6–12 tháng",inc:"Doanh thu định kỳ",m:"on",p:1,s:["teach","sales"],
 st:["Có tệp người theo dõi tin tưởng bạn","Thiết kế giá trị định kỳ: livestream, tài liệu, thử thách","Dùng Skool, Discord, Facebook Group kín, Zalo","Giữ chân thành viên bằng hoạt động đều đặn"],
 pro:["Thu nhập lặp lại","Gắn kết cao","Dễ bán thêm sản phẩm"],con:["Phải duy trì giá trị liên tục","Tỷ lệ rời bỏ","Tốn công quản trị"],
 tip:"Người ta ở lại vì cộng đồng (bạn bè cùng chí hướng) nhiều hơn vì nội dung."},
{id:"daytiengviet",c:"giaoduc",n:"Dạy ngoại ngữ / Dạy tiếng Việt cho người nước ngoài",i:"🗺️",d:"Dạy trên nền tảng quốc tế như iTalki, Preply hoặc trung tâm. Người nước ngoài học tiếng Việt ngày càng nhiều.",v:0,k:2,r:1,t:"1–2 tháng",inc:"8–30 USD/giờ",m:"on",p:0,s:["teach"],
 st:["Tạo hồ sơ giáo viên với video giới thiệu ấn tượng","Chuẩn bị giáo trình theo cấp độ","Định giá thấp lúc đầu để có đánh giá","Tăng giá dần khi lịch kín"],
 pro:["Thu nhập bằng ngoại tệ","Làm tại nhà","Kết nối văn hóa"],con:["Lệch múi giờ","Cạnh tranh giá","Thu nhập theo giờ"],
 tip:"Dạy tiếng Việt cho người Việt kiều thế hệ 2 và người nước ngoài làm việc tại Việt Nam là ngách ít cạnh tranh."},
{id:"workshop",c:"giaoduc",n:"Tổ chức workshop / Sự kiện thu phí",i:"🎟️",d:"Tổ chức buổi học thực hành, hội thảo, lớp làm bánh, vẽ tranh, cắm hoa, kỹ năng… thu phí tham gia.",v:1,k:3,r:2,t:"1–2 tháng",inc:"5–50 triệu/sự kiện",m:"off",p:0,s:["teach","sales","creative"],
 st:["Chọn chủ đề có trải nghiệm thực hành hấp dẫn","Thuê địa điểm phù hợp, chuẩn bị nguyên vật liệu","Bán vé qua mạng xã hội, đối tác","Chụp ảnh, quay video để quảng bá lần sau"],
 pro:["Tiền về nhanh","Xây cộng đồng","Bán thêm sản phẩm/khóa học"],con:["Rủi ro không đủ người","Chi phí địa điểm","Tốn sức tổ chức"],
 tip:"Workshop trải nghiệm (làm nến, gốm, vẽ) cho dân văn phòng cuối tuần và team building doanh nghiệp rất được ưa chuộng."},

/* ===================== CÔNG NGHỆ & AI ===================== */
{id:"saas",c:"congnghe",n:"SaaS – Phần mềm thuê bao",i:"☁️",d:"Xây phần mềm giải quyết vấn đề cụ thể, thu phí hàng tháng. Mô hình kinh doanh có giá trị định giá cao nhất.",v:2,k:5,r:4,t:"12–36 tháng",inc:"Doanh thu định kỳ, có thể rất lớn",m:"on",p:1,s:["tech","sales"],
 st:["Tìm “nỗi đau” lặp lại của một ngành cụ thể","Phỏng vấn 20–30 khách tiềm năng trước khi viết code","Làm bản MVP tối giản, bán cho 10 khách đầu","Lắng nghe phản hồi, cải tiến liên tục","Tối ưu giữ chân khách và giảm tỷ lệ hủy"],
 pro:["Doanh thu định kỳ","Mở rộng gần như không giới hạn","Giá trị doanh nghiệp cao"],con:["Thời gian phát triển lâu","Cạnh tranh toàn cầu","Cần cả kỹ năng kỹ thuật và kinh doanh"],
 tip:"Phần mềm “nhàm chán” cho ngành truyền thống (phòng khám, nhà xe, tiệm sửa) thường kiếm tiền tốt hơn ý tưởng “hot”."},
{id:"app",c:"congnghe",n:"Ứng dụng di động",i:"📲",d:"Phát triển app tiện ích, giáo dục, sức khỏe, game nhỏ. Kiếm tiền từ quảng cáo, mua trong app, thuê bao.",v:2,k:4,r:4,t:"6–24 tháng",inc:"0 – rất lớn",m:"on",p:1,s:["tech","creative"],
 st:["Nghiên cứu thị trường trên App Store/Google Play","Thiết kế trải nghiệm đơn giản, giải quyết một việc thật tốt","Phát triển bằng Flutter/React Native để chạy 2 nền tảng","Tối ưu ASO (từ khóa, ảnh, đánh giá)","Thử nghiệm mô hình kiếm tiền"],
 pro:["Tiếp cận hàng tỷ người dùng","Thu nhập thụ động khi app ổn định","Có thể bán lại app"],con:["Tỷ lệ thành công thấp","Chi phí thu hút người dùng cao","Cập nhật liên tục"],
 tip:"Hàng nghìn app nhỏ kiếm vài nghìn USD/tháng nhờ giải quyết một nhu cầu ngách rất cụ thể."},
{id:"aiagency",c:"congnghe",n:"Dịch vụ AI & Tự động hóa cho doanh nghiệp",i:"🧠",d:"Giúp doanh nghiệp ứng dụng AI: chatbot chăm sóc khách, tự động hóa quy trình, trợ lý AI nội bộ, đào tạo nhân viên dùng AI.",v:1,k:4,r:2,t:"1–6 tháng",inc:"10–500 triệu/dự án",m:"mix",p:0,s:["tech","sales","teach"],
 st:["Thành thạo các công cụ AI phổ biến và nền tảng tự động hóa","Chọn một ngành để chuyên sâu (bất động sản, spa, giáo dục…)","Làm demo giải quyết vấn đề thật của ngành đó","Bán gói triển khai + phí duy trì hằng tháng","Đóng gói thành sản phẩm để nhân rộng"],
 pro:["Nhu cầu đang bùng nổ","Giá trị hợp đồng cao","Thu nhập định kỳ từ bảo trì"],con:["Công nghệ thay đổi rất nhanh","Khách hàng còn hoài nghi","Cần cả kỹ thuật lẫn tư vấn"],
 tip:"Đừng bán “AI”, hãy bán kết quả: “giảm 50% thời gian trả lời khách”, “tăng 30% lead”. Doanh nghiệp mua lợi ích, không mua công nghệ."},
{id:"aicontent",c:"congnghe",n:"Sáng tạo nội dung với AI",i:"🪄",d:"Dùng AI tạo ảnh, video, nhạc, giọng đọc, bài viết để làm dịch vụ hoặc xây kênh nội dung với tốc độ gấp nhiều lần.",v:1,k:2,r:2,t:"1–3 tháng",inc:"Vài triệu – vài chục triệu/tháng",m:"on",p:0,s:["creative","tech"],
 st:["Thành thạo các công cụ AI tạo ảnh, video, giọng nói","Chọn hướng: làm dịch vụ cho doanh nghiệp hoặc xây kênh riêng","Kết hợp AI với tư duy sáng tạo và biên tập của con người","Tuân thủ bản quyền, gắn nhãn nội dung AI khi cần"],
 pro:["Năng suất cực cao","Chi phí thấp","Kỹ năng của tương lai"],con:["Nội dung AI đại trà bị đánh giá thấp","Vấn đề bản quyền","Rào cản gia nhập thấp"],
 tip:"AI làm 80% công việc, giá trị của bạn nằm ở 20% còn lại: ý tưởng, gu thẩm mỹ, câu chuyện và sự thấu hiểu khách hàng."},
{id:"template",c:"congnghe",n:"Bán template / Plugin / Theme",i:"🧩",d:"Tạo template Notion, Canva, Figma, theme WordPress, plugin, bộ công cụ cho nhà phát triển và bán nhiều lần.",v:0,k:3,r:1,t:"1–6 tháng",inc:"Vài trăm – vài nghìn USD/tháng",m:"on",p:1,s:["tech","creative"],
 st:["Xác định nhu cầu cụ thể của một nhóm người dùng","Thiết kế sản phẩm đẹp, dễ dùng, có hướng dẫn","Bán trên Gumroad, ThemeForest, Notion Marketplace, Etsy","Quảng bá qua nội dung hướng dẫn"],
 pro:["Thu nhập thụ động","Bán toàn cầu","Vốn gần bằng 0"],con:["Phải hỗ trợ người mua","Cạnh tranh nhiều","Cập nhật theo phiên bản nền tảng"],
 tip:"Template giải quyết công việc cụ thể (quản lý đơn hàng, kế hoạch nội dung) bán tốt hơn template “đẹp” chung chung."},
{id:"nocode",c:"congnghe",n:"Làm website / No-code cho khách",i:"🌐",d:"Dùng công cụ no-code (WordPress, Webflow, Wix, Framer) làm website, landing page cho doanh nghiệp nhỏ.",v:0,k:2,r:1,t:"Vài tuần",inc:"3–30 triệu/website",m:"on",p:0,s:["tech","creative"],
 st:["Thành thạo một nền tảng no-code","Làm 3 website mẫu cho các ngành khác nhau","Tìm khách: tiệm spa, nhà hàng, phòng khám, cửa hàng địa phương","Bán thêm gói bảo trì, SEO, hosting hằng tháng"],
 pro:["Học nhanh","Nhu cầu luôn có","Thu phí duy trì định kỳ"],con:["Cạnh tranh giá rẻ","AI tạo web tự động","Khách nhỏ ngân sách hạn chế"],
 tip:"Gói “website + duy trì + cập nhật hằng tháng” giúp bạn có thu nhập định kỳ thay vì chỉ thu một lần."},
{id:"bugbounty",c:"congnghe",n:"Bug Bounty / Bảo mật",i:"🛡️",d:"Tìm lỗ hổng bảo mật hợp pháp trong các chương trình bug bounty của doanh nghiệp và nhận tiền thưởng.",v:0,k:5,r:2,t:"6–24 tháng",inc:"Vài trăm – hàng chục nghìn USD/lỗi",m:"on",p:0,s:["tech"],
 st:["Học nền tảng mạng, web, bảo mật ứng dụng","Luyện tập trên môi trường thực hành hợp pháp (CTF, lab)","Tham gia HackerOne, Bugcrowd, chương trình trong nước","Chỉ kiểm thử trong phạm vi được cho phép, viết báo cáo chất lượng"],
 pro:["Tiền thưởng lớn","Kỹ năng cực kỳ được săn đón","Làm từ xa"],con:["Đường học rất dài","Thu nhập không đều","Cạnh tranh với chuyên gia toàn cầu"],
 tip:"Luôn tuân thủ phạm vi và quy định của chương trình — kiểm thử trái phép là vi phạm pháp luật."},
{id:"datalabel",c:"congnghe",n:"Gắn nhãn dữ liệu AI / Kiểm thử phần mềm",i:"🏷️",d:"Làm việc vi mô: gắn nhãn hình ảnh, đánh giá câu trả lời AI, kiểm thử ứng dụng, khảo sát người dùng.",v:0,k:1,r:1,t:"Vài tuần",inc:"3–20 triệu/tháng",m:"on",p:0,s:["tech","care"],
 st:["Đăng ký với các nền tảng đánh giá AI, kiểm thử, khảo sát uy tín","Hoàn thành bài kiểm tra đầu vào","Làm chính xác để tăng hạng và nhận việc giá cao","Học kiểm thử chuyên nghiệp để chuyển thành nghề QA"],
 pro:["Dễ bắt đầu","Linh hoạt thời gian","Cửa ngõ vào ngành công nghệ"],con:["Thu nhập thấp lúc đầu","Việc không đều","Có nhiều nền tảng lừa đảo giả danh"],
 tip:"Cảnh giác: công việc thật KHÔNG BAO GIỜ yêu cầu bạn nạp tiền, đặt cọc hay “làm nhiệm vụ” để được trả lương."},
{id:"gameindie",c:"congnghe",n:"Làm game indie",i:"🕹️",d:"Phát triển game nhỏ (mobile, PC, web) và phát hành trên Steam, App Store, Google Play.",v:1,k:5,r:4,t:"12–36 tháng",inc:"0 – rất lớn",m:"on",p:1,s:["tech","creative"],
 st:["Học engine: Unity, Godot, Unreal","Làm nhiều game rất nhỏ để học trọn quy trình","Xây cộng đồng sớm, chia sẻ quá trình phát triển","Phát hành, lắng nghe người chơi, cập nhật"],
 pro:["Sáng tạo tự do","Thu nhập thụ động khi game thành công","Thị trường toàn cầu"],con:["Rủi ro rất cao","Tốn nhiều thời gian","Cần nhiều kỹ năng"],
 tip:"Hoàn thành một game nhỏ tốt hơn bỏ dở một game lớn. Hãy phát hành sớm và thường xuyên."},

/* ===================== DỊCH VỤ & NGHỀ ===================== */
{id:"taixe",c:"dichvu",n:"Tài xế công nghệ / Giao hàng",i:"🛵",d:"Chạy xe ôm, taxi công nghệ, giao đồ ăn, giao hàng. Bắt đầu ngay, thu nhập theo công sức.",v:1,k:1,r:2,t:"Ngay lập tức",inc:"8–25 triệu/tháng",m:"off",p:0,s:["care"],
 st:["Chuẩn bị phương tiện, giấy tờ, bằng lái hợp lệ","Đăng ký với các ứng dụng gọi xe/giao hàng","Chạy vào giờ cao điểm, khu vực đông đơn","Theo dõi chi phí xăng, bảo dưỡng để tính lợi nhuận thật"],
 pro:["Bắt đầu ngay","Linh hoạt giờ","Không cần bằng cấp"],con:["Vất vả, rủi ro giao thông","Thu nhập bị giới hạn","Hao mòn phương tiện"],
 tip:"Hãy coi đây là thu nhập bắc cầu. Dùng thời gian rảnh để học một kỹ năng có giá trị cao hơn."},
{id:"suachua",c:"dichvu",n:"Sửa chữa điện lạnh / điện nước / xe",i:"🔧",d:"Nghề có tay nghề luôn có việc: sửa điều hòa, máy giặt, điện nước, xe máy, điện thoại, máy tính.",v:2,k:3,r:1,t:"3–12 tháng học nghề",inc:"10–40 triệu/tháng",m:"off",p:0,s:["hand"],
 st:["Học nghề tại trường nghề hoặc theo thợ giỏi","Đầu tư bộ đồ nghề cơ bản","Đăng ký trên các app dịch vụ tại nhà, Google Maps","Làm uy tín, bảo hành rõ ràng để có khách quen","Mở cửa hàng, thuê thợ khi khách đông"],
 pro:["Nhu cầu thiết yếu","Khó bị AI thay thế","Có thể mở tiệm riêng"],con:["Vất vả","Cần học nghề bài bản","Rủi ro an toàn lao động"],
 tip:"Thợ trung thực, báo giá rõ ràng là “hàng hiếm”. Uy tín sẽ giúp bạn kín lịch nhờ truyền miệng."},
{id:"vesinh",c:"dichvu",n:"Dọn dẹp nhà / Vệ sinh công nghiệp",i:"🧹",d:"Dịch vụ dọn nhà theo giờ, vệ sinh sau xây dựng, giặt sofa, vệ sinh máy lạnh, văn phòng.",v:1,k:2,r:1,t:"Vài tuần",inc:"8–50 triệu/tháng",m:"off",p:0,s:["care","hand"],
 st:["Bắt đầu tự làm, đăng ký trên app giúp việc","Đầu tư máy móc chuyên dụng để tăng giá trị dịch vụ","Xây quy trình, checklist chất lượng","Tuyển và đào tạo nhân viên, nhận hợp đồng văn phòng"],
 pro:["Nhu cầu lớn ở đô thị","Vốn thấp","Dễ mở rộng thành công ty"],con:["Lao động nặng","Quản lý nhân sự khó","Biên lợi nhuận vừa phải"],
 tip:"Hợp đồng vệ sinh định kỳ với văn phòng, chung cư mang lại doanh thu ổn định hơn khách lẻ."},
{id:"lamdep",c:"dichvu",n:"Làm đẹp: Nail, Tóc, Spa, Makeup",i:"💅",d:"Ngành dịch vụ làm đẹp tăng trưởng mạnh. Tay nghề tốt có thể làm tại nhà, mở tiệm, hoặc làm việc ở nước ngoài.",v:2,k:3,r:2,t:"3–6 tháng học nghề",inc:"10–60 triệu/tháng",m:"off",p:0,s:["hand","creative","care"],
 st:["Học nghề tại học viện uy tín, có chứng chỉ","Làm cho tiệm lớn để học kinh nghiệm và tệp khách","Xây Instagram/TikTok chia sẻ tác phẩm","Mở tiệm riêng hoặc làm dịch vụ tại nhà"],
 pro:["Nhu cầu cao, khách quay lại","Nghề sáng tạo","Cơ hội làm ở nước ngoài"],con:["Đứng nhiều, hóa chất","Cạnh tranh","Phụ thuộc tay nghề cá nhân"],
 tip:"Khách làm đẹp quay lại đều đặn mỗi 2–6 tuần — giá trị vòng đời khách rất lớn, hãy chăm sóc thật tốt."},
{id:"sukien",c:"dichvu",n:"Tổ chức sự kiện / Tiệc cưới",i:"🎉",d:"Lên kế hoạch và tổ chức tiệc cưới, sinh nhật, khai trương, hội nghị, team building.",v:2,k:4,r:3,t:"3–6 tháng",inc:"10–200 triệu/sự kiện (doanh thu)",m:"off",p:0,s:["creative","sales","care"],
 st:["Làm việc cho công ty sự kiện để học nghề","Xây mạng lưới nhà cung cấp: âm thanh, ánh sáng, trang trí, MC","Bắt đầu với sự kiện nhỏ, chụp ảnh portfolio","Định vị phong cách riêng, nhận dự án lớn hơn"],
 pro:["Giá trị hợp đồng lớn","Sáng tạo","Nhiều cơ hội kết nối"],con:["Áp lực cao","Theo mùa","Rủi ro phát sinh"],
 tip:"Mạng lưới nhà cung cấp tin cậy là lợi thế cạnh tranh lớn nhất của người tổ chức sự kiện."},
{id:"pet",c:"dichvu",n:"Dịch vụ thú cưng",i:"🐶",d:"Spa, cắt tỉa lông, trông giữ, dắt chó đi dạo, huấn luyện, bán thức ăn và phụ kiện thú cưng.",v:2,k:2,r:2,t:"1–6 tháng",inc:"10–50 triệu/tháng",m:"off",p:0,s:["care","hand"],
 st:["Học kỹ năng grooming, chăm sóc, huấn luyện cơ bản","Bắt đầu với dịch vụ tại nhà hoặc trông giữ","Xây cộng đồng chủ nuôi thú cưng trên mạng xã hội","Mở pet shop kết hợp spa khi có tệp khách"],
 pro:["Thị trường đang tăng mạnh","Khách chi tiêu mạnh tay","Công việc vui"],con:["Rủi ro thú cưng bị thương","Cần không gian","Vất vả"],
 tip:"Người nuôi thú cưng coi chúng như con — sự tận tâm và minh bạch (gửi ảnh/video cập nhật) là chìa khóa giữ khách."},
{id:"nauan",c:"dichvu",n:"Nấu ăn tại nhà / Suất ăn / Bánh handmade",i:"🧁",d:"Nấu cơm văn phòng, đồ ăn healthy, bánh ngọt, món đặc sản bán online từ căn bếp nhà mình.",v:1,k:2,r:2,t:"Vài tuần",inc:"5–40 triệu/tháng",m:"mix",p:0,s:["hand","creative","care"],
 st:["Chọn món tủ, chuẩn hóa công thức","Chụp ảnh món ăn đẹp, bán qua Facebook, Zalo, app giao đồ ăn","Nhận đặt trước theo ngày để giảm lãng phí","Đảm bảo vệ sinh an toàn thực phẩm, đăng ký khi mở rộng"],
 pro:["Làm tại nhà","Vốn nhỏ","Khách quen trung thành"],con:["Vất vả","Hạn chế quy mô","Phụ thuộc thời gian giao"],
 tip:"Mô hình đặt trước – giao theo khung giờ cố định giúp bạn chủ động nguyên liệu và tối ưu lợi nhuận."},
{id:"dulich",c:"dichvu",n:"Hướng dẫn viên / Tự tổ chức tour",i:"🧳",d:"Dẫn tour cho khách trong nước và quốc tế, tổ chức tour trải nghiệm ẩm thực, phượt, trekking.",v:1,k:3,r:2,t:"1–6 tháng",inc:"10–50 triệu/tháng + tip",m:"off",p:0,s:["care","teach","sales"],
 st:["Học ngoại ngữ, kiến thức văn hóa – lịch sử địa phương","Lấy thẻ hướng dẫn viên theo quy định","Đăng tour trải nghiệm trên Airbnb Experiences, Klook, GetYourGuide","Xây đánh giá tốt, hợp tác với khách sạn, homestay"],
 pro:["Đi nhiều, gặp nhiều người","Tiền tip từ khách quốc tế","Biến đam mê thành nghề"],con:["Theo mùa du lịch","Sức khỏe","Thu nhập biến động"],
 tip:"Tour trải nghiệm nhỏ (food tour, làng nghề, nấu ăn) có giá trị cao và ít cạnh tranh hơn tour đại trà."},
{id:"vantai",c:"dichvu",n:"Chuyển nhà / Vận tải",i:"🚛",d:"Dịch vụ chuyển nhà, chuyển văn phòng, xe tải chở hàng theo chuyến, giao hàng cồng kềnh.",v:3,k:2,r:2,t:"1–3 tháng",inc:"15–60 triệu/tháng",m:"off",p:0,s:["hand","care"],
 st:["Đầu tư hoặc thuê xe tải phù hợp","Đăng ký trên các app vận tải, Google Maps","Xây đội bốc xếp đáng tin cậy, có bảo hiểm hàng hóa","Báo giá rõ ràng, trọn gói"],
 pro:["Nhu cầu ổn định","Giá trị mỗi đơn cao","Dễ mở rộng đội xe"],con:["Vốn phương tiện","Rủi ro hư hỏng hàng","Lao động nặng"],
 tip:"Đánh giá 5 sao trên Google Maps là nguồn khách miễn phí lớn nhất cho dịch vụ địa phương."},
{id:"chamsoc",c:"dichvu",n:"Chăm sóc người già / Trẻ em",i:"🤲",d:"Giúp việc, bảo mẫu, chăm sóc người cao tuổi, điều dưỡng tại nhà — nhu cầu tăng mạnh khi dân số già hóa.",v:0,k:2,r:1,t:"Vài tuần",inc:"7–20 triệu/tháng",m:"off",p:0,s:["care"],
 st:["Học khóa chăm sóc, sơ cứu cơ bản, có chứng chỉ điều dưỡng nếu được","Đăng ký với trung tâm, app dịch vụ chăm sóc","Xây uy tín qua giới thiệu","Mở trung tâm cung ứng khi có kinh nghiệm"],
 pro:["Nhu cầu tăng mạnh","Không cần vốn","Ý nghĩa nhân văn"],con:["Áp lực tinh thần","Thời gian dài","Thu nhập vừa phải"],
 tip:"Chăm sóc người cao tuổi là ngành có tương lai lớn tại Việt Nam và nhiều nước như Nhật, Đức."},
{id:"pt",c:"dichvu",n:"Huấn luyện viên thể hình / Yoga",i:"🏋️",d:"Dạy cá nhân, lớp nhóm, coaching online về tập luyện, dinh dưỡng, giảm cân.",v:1,k:3,r:1,t:"3–6 tháng",inc:"10–60 triệu/tháng",m:"mix",p:0,s:["teach","care"],
 st:["Có chứng chỉ huấn luyện viên uy tín","Làm tại phòng gym để xây tệp khách","Chia sẻ kiến thức, hành trình học viên trên mạng xã hội","Mở coaching online, bán giáo án, thực đơn"],
 pro:["Sống khỏe khi làm nghề","Khách gắn bó lâu","Kết hợp online"],con:["Phụ thuộc thể lực","Thu nhập theo giờ","Cạnh tranh"],
 tip:"Kết quả “trước – sau” của học viên (có đồng ý) là nội dung marketing mạnh nhất."},

/* ===================== NÔNG NGHIỆP ===================== */
{id:"rausach",c:"nongnghiep",n:"Rau sạch / Thủy canh / Nhà màng",i:"🥬",d:"Trồng rau sạch, rau thủy canh, nông nghiệp công nghệ cao để bán cho gia đình, nhà hàng, siêu thị.",v:2,k:3,r:3,t:"2–6 tháng",inc:"10–50 triệu/tháng",m:"off",p:0,s:["hand"],
 st:["Học kỹ thuật canh tác, thủy canh, nhà màng","Bắt đầu quy mô nhỏ (sân thượng, vườn nhà)","Tìm đầu ra trước: bếp ăn, nhà hàng, nhóm cư dân","Đạt chứng nhận VietGAP để vào siêu thị","Bán online trực tiếp đến người tiêu dùng"],
 pro:["Nhu cầu thực phẩm sạch tăng","Chu kỳ thu hoạch nhanh","Có thể kết hợp du lịch"],con:["Phụ thuộc thời tiết, sâu bệnh","Đầu ra bấp bênh","Lao động vất vả"],
 tip:"Đầu ra quyết định thành bại trong nông nghiệp. Có khách trước rồi mới mở rộng diện tích."},
{id:"channuoi",c:"nongnghiep",n:"Chăn nuôi (gà, heo, bò, dê)",i:"🐓",d:"Chăn nuôi quy mô hộ gia đình hoặc trang trại. Gà thả vườn, dê, bò thịt là các mô hình phổ biến.",v:2,k:3,r:3,t:"3–12 tháng",inc:"Tùy quy mô",m:"off",p:0,s:["hand"],
 st:["Học kỹ thuật chăn nuôi, phòng dịch bệnh","Bắt đầu số lượng nhỏ để học kinh nghiệm","Xây chuồng trại đúng quy chuẩn, xử lý môi trường","Tìm đầu ra ổn định (thương lái, nhà hàng, bán lẻ)"],
 pro:["Nhu cầu thực phẩm ổn định","Tận dụng đất đai","Có thể liên kết doanh nghiệp"],con:["Rủi ro dịch bệnh","Giá thị trường biến động","Ô nhiễm môi trường"],
 tip:"Liên kết bao tiêu với doanh nghiệp giúp giảm rủi ro giá, đặc biệt với người mới."},
{id:"thuysan",c:"nongnghiep",n:"Nuôi trồng thủy sản",i:"🦐",d:"Nuôi tôm, cá, ốc, cua… Lợi nhuận cao nhưng rủi ro lớn, đòi hỏi kỹ thuật.",v:3,k:4,r:4,t:"3–8 tháng/vụ",inc:"Lợi nhuận cao nếu thành công",m:"off",p:0,s:["hand"],
 st:["Chọn đối tượng nuôi phù hợp vùng nước","Học kỹ thuật quản lý nước, thức ăn, dịch bệnh","Đầu tư ao nuôi, hệ thống sục khí","Bắt đầu từ diện tích nhỏ, ghi chép kỹ","Tìm đầu ra, liên kết doanh nghiệp chế biến"],
 pro:["Biên lợi nhuận lớn","Thị trường xuất khẩu","Việt Nam có lợi thế tự nhiên"],con:["Rủi ro dịch bệnh rất cao","Vốn lớn","Biến đổi khí hậu"],
 tip:"Mô hình nuôi kết hợp (tôm – lúa, cá – lúa) giảm rủi ro và thân thiện môi trường."},
{id:"caytrai",c:"nongnghiep",n:"Cây ăn trái đặc sản",i:"🥭",d:"Trồng sầu riêng, bưởi, xoài, cam, mít, dừa… Cây lâu năm mang lại thu nhập ổn định nhiều năm.",v:3,k:3,r:3,t:"3–5 năm",inc:"Hàng trăm triệu/ha/năm khi cho trái",m:"off",p:1,s:["hand","finance"],
 st:["Chọn giống phù hợp thổ nhưỡng, có thị trường xuất khẩu","Trồng xen cây ngắn ngày để có thu nhập trong thời gian chờ","Áp dụng quy trình canh tác chuẩn, mã số vùng trồng","Liên kết hợp tác xã, doanh nghiệp xuất khẩu"],
 pro:["Thu nhập lâu dài","Giá trị đất tăng","Cơ hội xuất khẩu"],con:["Thời gian chờ lâu","Rủi ro giá khi trồng ồ ạt","Thời tiết cực đoan"],
 tip:"Cẩn trọng khi đám đông đổ xô trồng một loại cây — giá có thể sụp khi cung vượt cầu."},
{id:"ocop",c:"nongnghiep",n:"Đặc sản vùng miền / Nông sản chế biến",i:"🍯",d:"Đóng gói đặc sản quê nhà (mật ong, cà phê, trà, khô, mắm, bánh) thành sản phẩm có thương hiệu, bán online toàn quốc.",v:1,k:3,r:2,t:"2–6 tháng",inc:"5–100 triệu/tháng",m:"mix",p:0,s:["sales","creative","hand"],
 st:["Chọn đặc sản có câu chuyện và nguồn gốc rõ ràng","Thiết kế bao bì, nhãn mác, đăng ký công bố chất lượng","Kể câu chuyện nguồn gốc qua video, livestream tại vườn","Bán trên sàn TMĐT, mạng xã hội, quà tặng doanh nghiệp","Hướng tới chứng nhận OCOP"],
 pro:["Tạo giá trị gia tăng cho nông sản","Câu chuyện độc đáo","Giúp đỡ quê hương"],con:["Thủ tục an toàn thực phẩm","Bảo quản, vận chuyển","Cần kỹ năng marketing"],
 tip:"Livestream ngay tại vườn, xưởng chế biến là cách xây niềm tin nhanh nhất cho sản phẩm nông nghiệp."},
{id:"farmstay",c:"nongnghiep",n:"Du lịch sinh thái / Farmstay",i:"🏕️",d:"Kết hợp nông trại với du lịch trải nghiệm: hái trái cây, câu cá, cắm trại, lưu trú giữa thiên nhiên.",v:3,k:4,r:3,t:"6–18 tháng",inc:"Tùy quy mô",m:"off",p:0,s:["care","creative","sales"],
 st:["Tận dụng đất vườn có cảnh quan đẹp, gần thành phố","Thiết kế trải nghiệm: hái quả, nấu ăn, workshop","Xây khu lưu trú, cắm trại tối thiểu","Quảng bá trên mạng xã hội, hợp tác trường học, công ty"],
 pro:["Tăng giá trị đất nông nghiệp","Nhiều nguồn thu","Xu hướng du lịch xanh"],con:["Thủ tục pháp lý đất đai","Theo mùa","Vốn hạ tầng"],
 tip:"Tour trải nghiệm cho học sinh và team building doanh nghiệp mang lại khách đoàn ổn định."},
{id:"nam",c:"nongnghiep",n:"Trồng nấm",i:"🍄",d:"Trồng nấm bào ngư, linh chi, đông trùng hạ thảo… trong nhà, tốn ít diện tích, vòng quay nhanh.",v:2,k:3,r:3,t:"1–3 tháng",inc:"5–30 triệu/tháng",m:"off",p:0,s:["hand"],
 st:["Học kỹ thuật tại cơ sở uy tín","Chuẩn bị nhà trồng đảm bảo nhiệt độ, độ ẩm","Mua phôi giống chất lượng","Bán tươi cho chợ, nhà hàng hoặc sấy khô, chế biến"],
 pro:["Ít diện tích","Chu kỳ ngắn","Tận dụng phụ phẩm nông nghiệp"],con:["Dễ nhiễm bệnh","Cần kỹ thuật","Đầu ra cần xây dựng"],
 tip:"Sản phẩm chế biến sâu (nấm sấy, trà linh chi) có giá trị gấp nhiều lần nấm tươi và bảo quản lâu hơn."},
{id:"yen",c:"nongnghiep",n:"Nuôi yến / Nuôi ong",i:"🐝",d:"Xây nhà yến lấy tổ yến hoặc nuôi ong lấy mật — mô hình có giá trị sản phẩm cao.",v:3,k:4,r:4,t:"1–3 năm",inc:"Giá trị cao khi thành công",m:"off",p:1,s:["hand","finance"],
 st:["Khảo sát vùng có đàn yến/nguồn hoa phù hợp","Học kỹ thuật từ người có kinh nghiệm","Tuân thủ quy định địa phương về nhà yến","Xây thương hiệu sản phẩm, bán trực tiếp"],
 pro:["Sản phẩm giá trị cao","Gần như thụ động khi ổn định","Nhu cầu lớn"],con:["Rủi ro yến không về","Vốn lớn","Hàng giả cạnh tranh"],
 tip:"Đừng nghe quảng cáo “xây nhà yến chắc chắn có lãi”. Khảo sát kỹ và học từ người thật trước khi xuống tiền."}
);
