/* Drabuff AI — full enterprise AI service catalogue (content) */
window.CATS = [
  { id: 'cx', n: 'Giao tiếp khách hàng', d: 'AI nói chuyện với khách thay bạn: nhắn tin, gọi điện, tư vấn, video.' },
  { id: 'auto', n: 'Tự động hóa & Robot phần mềm', d: 'Bỏ việc copy–dán, nhập liệu, chuyển giấy tờ bằng tay.' },
  { id: 'agent', n: 'AI Agent', d: 'AI không chỉ trả lời mà tự lên kế hoạch và làm trọn việc.' },
  { id: 'know', n: 'Tri thức & Dữ liệu', d: 'Biến tài liệu và số liệu của công ty thành câu trả lời, dự báo.' },
  { id: 'mkt', n: 'Marketing & Nội dung', d: 'Sản xuất nội dung, hình ảnh, video và lắng nghe khách hàng.' },
  { id: 'phys', n: 'Thị giác máy & Robot vật lý', d: 'AI bước ra thế giới thật: camera, cảm biến, robot.' },
  { id: 'llm', n: 'Nền tảng LLM & Hạ tầng', d: '"Bộ não" AI đặt ở đâu: cloud công cộng, cloud riêng hay ngay tại công ty.' },
  { id: 'gov', n: 'Chiến lược, Quản trị & Vận hành', d: 'Làm gì trước, dùng an toàn, đào tạo con người và chăm sóc hệ thống.' }
];

window.SERVICES = [
  /* ---------- GIAO TIẾP KHÁCH HÀNG ---------- */
  { id: 'chatbot', cat: 'cx', code: 'C01', n: 'AI Chatbot đa kênh', tag: 'Tư vấn viên trực 24/7 trên Zalo, Facebook, Website', tl: '2–4 tuần', cx: 1,
    easy: 'Giống một nhân viên tư vấn đã học thuộc toàn bộ bảng giá, chính sách và câu hỏi thường gặp của công ty. Không nghỉ, không quên, trả lời cùng lúc hàng trăm khách.',
    flow: [['Khách nhắn tin', 'Khách hỏi qua Zalo OA, Fanpage hoặc khung chat website, vào bất kỳ giờ nào.'], ['AI hiểu câu hỏi', 'AI đọc tin nhắn và hiểu khách muốn gì: hỏi giá, đặt lịch, khiếu nại…'], ['Tra kho kiến thức', 'Tìm đúng thông tin trong tài liệu công ty: bảng giá, chính sách, tồn kho.'], ['Trả lời & hành động', 'Trả lời tự nhiên, xin số điện thoại, đặt lịch hoặc tạo đơn.'], ['Lưu vào CRM', 'Thông tin khách và nội dung trao đổi tự ghi vào hệ thống bán hàng.']],
    branch: [2, 'Câu hỏi khó hoặc khách muốn gặp người thật', 'chuyển ngay cho nhân viên kèm tóm tắt cuộc trò chuyện.'],
    ex: ['Spa tư vấn liệu trình và đặt lịch lúc 23h', 'Shop online trả lời phí ship, size, tình trạng đơn', 'Trường học tư vấn tuyển sinh mùa cao điểm'],
    get: ['Phản hồi dưới 10 giây, 24/7', 'Tự xử lý 60–80% câu hỏi lặp lại', 'Không bỏ sót khách ngoài giờ'],
    fit: ['Nhận trên 30 tin nhắn mỗi ngày', 'Khách hỏi đi hỏi lại những câu giống nhau', 'Muốn mở rộng mà không tăng người trực'] },
  { id: 'voice', cat: 'cx', code: 'C02', n: 'Voice AI · Callbot tổng đài', tag: 'Tổng đài viên AI nghe và nói tiếng Việt tự nhiên', tl: '4–6 tuần', cx: 3,
    easy: 'Như có một tổng đài viên giọng nói tự nhiên, nghe hiểu khách nói gì và trả lời ngay qua điện thoại. Gọi đến hay gọi đi đều được, hàng nghìn cuộc cùng lúc.',
    flow: [['Cuộc gọi đến / đi', 'Khách gọi tổng đài, hoặc hệ thống tự gọi theo danh sách.'], ['Giọng nói → chữ', 'AI nghe và chép lại lời khách theo thời gian thực (Speech-to-Text).'], ['AI nghĩ câu trả lời', 'Mô hình ngôn ngữ hiểu ý và soạn câu trả lời theo kịch bản.'], ['Chữ → giọng nói', 'Đọc câu trả lời bằng giọng tự nhiên (Text-to-Speech).'], ['Tóm tắt & ghi nhận', 'Tự tóm tắt cuộc gọi, gắn kết quả, lưu vào CRM.']],
    branch: [2, 'Khách bức xúc hoặc yêu cầu đặc biệt', 'chuyển máy cho nhân viên ngay trong cuộc gọi.'],
    ex: ['Gọi xác nhận đơn COD trước khi giao', 'Nhắc lịch hẹn khám, nhắc đóng phí', 'Khảo sát mức hài lòng sau dịch vụ'],
    get: ['Gọi hàng nghìn cuộc mỗi ngày', 'Giảm tải tổng đài giờ cao điểm', '100% cuộc gọi được ghi chép'],
    fit: ['Có tổng đài hoặc đội telesales', 'Nhiều cuộc gọi lặp lại theo kịch bản'] },
  { id: 'salesagent', cat: 'cx', code: 'C03', n: 'AI Sales Agent', tag: 'Hỏi nhu cầu, gợi ý sản phẩm và chốt đơn như sales giỏi', tl: '3–5 tuần', cx: 2,
    easy: 'Không chỉ trả lời, mà chủ động hỏi nhu cầu, gợi ý đúng sản phẩm, xử lý băn khoăn và dẫn khách tới quyết định mua. Giống như nhân bản người bán hàng giỏi nhất của bạn.',
    flow: [['Khách quan tâm', 'Khách bấm quảng cáo, nhắn tin hoặc để lại thông tin.'], ['Hỏi nhu cầu', 'AI hỏi vài câu ngắn để hiểu ngân sách, mục đích, sở thích.'], ['Gợi ý phù hợp', 'Chọn 1–3 sản phẩm hợp nhất trong danh mục và giải thích vì sao.'], ['Xử lý băn khoăn', 'Trả lời về giá, chất lượng, so sánh theo kịch bản chuẩn.'], ['Chốt & bàn giao', 'Tạo đơn, nhận cọc hoặc chuyển khách "nóng" cho sales chốt.']],
    ex: ['Bất động sản: lọc khách theo tài chính, gợi ý căn phù hợp', 'Showroom xe: tư vấn phiên bản, đặt lịch lái thử', 'TMĐT: gợi ý combo để tăng giá trị đơn'],
    get: ['Tăng tỷ lệ chuyển đổi từ tin nhắn', 'Sales chỉ tập trung vào khách nóng', 'Chất lượng tư vấn đồng đều'],
    fit: ['Chạy quảng cáo nhiều, lead đông', 'Sản phẩm cần tư vấn trước khi mua'] },
  { id: 'avatar', cat: 'cx', code: 'C04', n: 'AI Avatar · Người dẫn ảo', tag: 'Nhân vật số đọc kịch bản thành video, đa ngôn ngữ', tl: '1–3 tuần', cx: 1,
    easy: 'Tạo một "người dẫn chương trình số" có khuôn mặt và giọng nói (có thể giống chính bạn), đọc bất kỳ kịch bản nào thành video mà không cần quay dựng.',
    flow: [['Đưa nội dung', 'Giới thiệu sản phẩm, bài đào tạo, bản tin nội bộ.'], ['AI biên tập', 'Viết lại kịch bản ngắn gọn, hấp dẫn, dịch nhiều ngôn ngữ.'], ['Nhân vật số đọc', 'Avatar khớp khẩu hình với giọng nói tự nhiên.'], ['Dựng video', 'Ghép phụ đề, hình minh họa, logo thương hiệu.'], ['Phát hành', 'Đăng đa kênh hoặc dùng cho đào tạo nội bộ.']],
    ex: ['Video đào tạo nhân viên mới hàng loạt', 'Giới thiệu sản phẩm bằng 5 ngôn ngữ', 'Bản tin nội bộ hằng tuần'],
    get: ['Từ vài ngày quay dựng xuống vài phút', 'Có video trong vài phút'],
    fit: ['Cần nhiều video đào tạo hoặc marketing', 'Phục vụ khách nước ngoài'] },

  /* ---------- TỰ ĐỘNG HÓA ---------- */
  { id: 'workflow', cat: 'auto', code: 'A01', n: 'Workflow Automation', tag: 'Nối các phần mềm thành dây chuyền tự chạy', tl: '2–4 tuần', cx: 1,
    easy: 'Giống dây chuyền trong nhà máy: việc A xong thì tự chuyển sang B, sang C. Không ai phải copy, dán hay nhắc nhau nữa.',
    flow: [['Sự kiện kích hoạt', 'Có đơn mới, có form đăng ký, có email, hoặc đến giờ hẹn.'], ['Lấy dữ liệu', 'Hệ thống tự lấy thông tin từ nơi phát sinh.'], ['AI xử lý', 'Phân loại, tóm tắt, viết nội dung, kiểm tra điều kiện.'], ['Ghi & cập nhật', 'Tự ghi vào Google Sheets, CRM, phần mềm kế toán.'], ['Báo đúng người', 'Nhắn Zalo hoặc email cho người phụ trách kèm việc cần làm.']],
    ex: ['Form đăng ký → tạo khách trong CRM → nhắn Zalo cho sales', 'Đơn hàng mới → xuất hóa đơn → báo kho', 'Email đơn hàng → AI tóm tắt → báo trưởng phòng'],
    get: ['Bỏ hẳn thao tác copy–dán', 'Không sót việc, không quên nhắc', 'Chạy 24/7, có nhật ký đầy đủ'],
    fit: ['Dùng nhiều phần mềm rời rạc', 'Có quy trình lặp lại mỗi ngày'] },
  { id: 'rpa', cat: 'auto', code: 'A02', n: 'RPA · Robot phần mềm', tag: 'Robot thao tác trên máy tính thay con người', tl: '3–6 tuần', cx: 2,
    easy: 'Một "nhân viên ảo" ngồi trước máy tính: tự mở phần mềm, bấm nút, gõ dữ liệu, tải file, đúng như người làm nhưng nhanh hơn và không sai.',
    flow: [['Ghi lại thao tác', 'Chuyên gia quan sát và mô tả từng bước nhân viên đang làm.'], ['Dạy robot', 'Robot được lập trình mở ứng dụng, điền form, bấm nút.'], ['Chạy theo lịch', 'Tự chạy hằng giờ, hằng ngày, kể cả ban đêm.'], ['Bắt ngoại lệ', 'Gặp trường hợp lạ thì dừng và báo người xử lý.'], ['Báo cáo', 'Gửi tổng kết số việc đã làm và lỗi gặp phải.']],
    branch: [3, 'Dữ liệu sai định dạng hoặc giao diện thay đổi', 'robot dừng an toàn và gửi cảnh báo, không làm bừa.'],
    ex: ['Nhập 500 hóa đơn vào phần mềm kế toán', 'Tải sao kê ngân hàng và đối soát', 'Cập nhật đơn trên nhiều sàn TMĐT'],
    get: ['Nhanh gấp 5–10 lần người làm', 'Gần như không sai sót', 'Không cần sửa phần mềm cũ'],
    fit: ['Phần mềm cũ không có API', 'Nhiều thao tác nhập liệu lặp lại'] },
  { id: 'idp', cat: 'auto', code: 'A03', n: 'Xử lý tài liệu thông minh', tag: 'Đọc hóa đơn, hợp đồng, chứng từ và lấy dữ liệu ra', tl: '3–5 tuần', cx: 2,
    easy: 'AI "đọc" ảnh chụp hoặc file PDF như người, hiểu đâu là số tiền, mã số thuế, ngày ký… rồi tự điền vào hệ thống.',
    flow: [['Nhận tài liệu', 'Ảnh chụp, PDF scan, file đính kèm email.'], ['Nhận dạng chữ (OCR)', 'Biến hình ảnh thành văn bản, kể cả tiếng Việt có dấu.'], ['Hiểu & trích xuất', 'Xác định các trường cần lấy: tên, số tiền, ngày, điều khoản.'], ['Kiểm tra chéo', 'So với đơn hàng và quy định, đánh dấu chỗ bất thường.'], ['Đẩy vào hệ thống', 'Ghi vào ERP/Excel, lưu trữ để tìm kiếm sau.']],
    branch: [3, 'AI không chắc chắn về một trường dữ liệu', 'chuyển người duyệt nhanh trước khi ghi.'],
    ex: ['Hóa đơn đầu vào → phần mềm kế toán', 'Hồ sơ vay, bảo hiểm → kiểm tra thiếu giấy tờ', 'Chứng từ xuất nhập khẩu → khai báo'],
    get: ['Giảm 60–80% thời gian nhập liệu', 'Phát hiện sai lệch từ sớm'],
    fit: ['Xử lý trên 200 chứng từ mỗi tháng'] },
  { id: 'inbox', cat: 'auto', code: 'A04', n: 'AI xử lý Email & Ticket', tag: 'Phân loại, soạn trả lời nháp và chia việc từ hộp thư chung', tl: '2–3 tuần', cx: 1,
    easy: 'Như một thư ký đọc hết hộp thư mỗi sáng: biết thư nào gấp, thư nào của ai, soạn sẵn câu trả lời để bạn chỉ cần bấm gửi.',
    flow: [['Email / ticket đến', 'Từ hộp thư chung, form hỗ trợ, cổng khách hàng.'], ['Phân loại', 'Gắn nhãn yêu cầu tư vấn, khiếu nại, hỏi đơn, hóa đơn; chấm độ gấp.'], ['Soạn nháp', 'Viết sẵn phản hồi dựa trên lịch sử và chính sách.'], ['Giao đúng người', 'Chuyển cho bộ phận phụ trách, đặt hạn xử lý.'], ['Theo dõi hạn', 'Nhắc khi sắp trễ, báo cáo cuối tuần.']],
    ex: ['Hộp thư sales@ nhận 300 email mỗi ngày', 'Bộ phận hỗ trợ kỹ thuật B2B'],
    get: ['Không thư nào bị bỏ quên', 'Thời gian phản hồi giảm một nửa trở lên'],
    fit: ['Giao dịch với khách chủ yếu qua email'] },

  /* ---------- AI AGENT ---------- */
  { id: 'agent', cat: 'agent', code: 'G01', n: 'AI Agent tác vụ', tag: 'AI tự lên kế hoạch và làm trọn một việc nhiều bước', tl: '4–8 tuần', cx: 3,
    easy: 'Chatbot chỉ trả lời. Agent thì làm việc: bạn giao mục tiêu, nó tự chia nhỏ, tự dùng công cụ (tìm kiếm, Excel, email, phần mềm) và báo lại khi xong.',
    flow: [['Giao mục tiêu', 'Ví dụ: "Lập báo cáo đối thủ tuần này và gửi cho tôi".'], ['Lập kế hoạch', 'Agent chia mục tiêu thành các bước nhỏ.'], ['Dùng công cụ', 'Tự tìm kiếm, đọc file, truy vấn dữ liệu, gọi phần mềm.'], ['Tự kiểm tra', 'Đánh giá kết quả, làm lại bước chưa đạt.'], ['Báo cáo / xin duyệt', 'Gửi kết quả; việc quan trọng thì chờ người duyệt.']],
    branch: [4, 'Hành động có rủi ro (chi tiền, gửi cho khách)', 'luôn dừng lại chờ con người duyệt.'],
    ex: ['Agent nghiên cứu thị trường hằng tuần', 'Agent đối soát công nợ và nhắc thanh toán', 'Agent tuyển dụng: lọc CV, hẹn lịch phỏng vấn'],
    get: ['Giao trọn việc, không phải làm từng bước', 'Làm việc 24/7, có nhật ký'],
    fit: ['Việc nhiều bước nhưng có quy tắc rõ ràng'] },
  { id: 'multiagent', cat: 'agent', code: 'G02', n: 'Hệ thống Multi-Agent', tag: 'Một "phòng ban AI" gồm nhiều agent phối hợp', tl: '8–12 tuần', cx: 3,
    easy: 'Giống một đội nhóm: agent trưởng nhóm nhận việc rồi giao cho agent nghiên cứu, agent viết, agent kiểm duyệt. Mỗi agent giỏi một việc, phối hợp ra kết quả hoàn chỉnh.',
    flow: [['Yêu cầu lớn', 'Ví dụ: "Lên chiến dịch ra mắt sản phẩm mới".'], ['Agent điều phối', 'Chia việc và giao cho các agent chuyên trách.'], ['Agent chuyên môn', 'Nghiên cứu, viết, phân tích số liệu song song.'], ['Agent kiểm duyệt', 'Soát lỗi, kiểm tra thương hiệu và quy định.'], ['Tổng hợp', 'Gộp thành sản phẩm hoàn chỉnh cho người duyệt cuối.']],
    ex: ['Phòng marketing AI: nghiên cứu → nội dung → lịch đăng', 'Bộ phận thầu: đọc hồ sơ → tính giá → soạn hồ sơ dự thầu'],
    get: ['Xử lý việc phức tạp liên phòng ban', 'Chất lượng cao nhờ kiểm duyệt chéo'],
    fit: ['Đã có agent đơn lẻ và muốn mở rộng'] },
  { id: 'computeruse', cat: 'agent', code: 'G03', n: 'Agent thao tác máy tính', tag: 'AI nhìn màn hình và dùng phần mềm như con người', tl: '4–8 tuần', cx: 3,
    easy: 'Kết hợp robot phần mềm với AI: agent "nhìn" màn hình, hiểu đang ở đâu và tự quyết định bấm gì. Giao diện có thay đổi vẫn làm được, điều mà robot RPA thông thường hay bị kẹt.',
    flow: [['Nhận nhiệm vụ', 'Ví dụ: "Lấy báo cáo doanh thu từ 3 cổng nhà cung cấp".'], ['Nhìn màn hình', 'AI chụp và hiểu giao diện: nút, ô nhập, bảng.'], ['Thao tác', 'Di chuột, gõ phím, tải file như người dùng.'], ['Xác minh', 'Kiểm tra kết quả, thử lại nếu cần.'], ['Bàn giao', 'Lưu file, cập nhật hệ thống, báo hoàn thành.']],
    ex: ['Đăng nhập các cổng dịch vụ công lấy dữ liệu', 'Thao tác trên phần mềm cũ không có API'],
    get: ['Tự động hóa cả những việc "khó tự động"'],
    fit: ['Làm việc với nhiều cổng web, phần mềm khác nhau'] },
  { id: 'copilot', cat: 'agent', code: 'G04', n: 'Trợ lý AI cho từng nhân viên', tag: 'Mỗi vị trí có một trợ lý AI riêng đã hiểu công việc', tl: '2–4 tuần', cx: 1,
    easy: 'Mỗi nhân viên có một trợ lý riêng đã đọc quy trình, mẫu biểu, giọng văn công ty: soạn văn bản, tóm tắt cuộc họp, trả lời câu hỏi nghiệp vụ trong vài giây.',
    flow: [['Chọn vị trí', 'Sales, kế toán, HR, CSKH… mỗi vị trí một trợ lý.'], ['Nạp kiến thức', 'Quy trình, mẫu biểu, ví dụ làm tốt của công ty.'], ['Cài đặt an toàn', 'Phân quyền, chặn dữ liệu nhạy cảm, ghi nhật ký.'], ['Nhân viên sử dụng', 'Hỏi và giao việc qua web, Zalo hoặc Teams.'], ['Cải tiến', 'Thu phản hồi, cập nhật kiến thức hằng tháng.']],
    ex: ['Trợ lý kế toán trả lời câu hỏi thuế nội bộ', 'Trợ lý sales soạn đề xuất theo mẫu'],
    get: ['Tiết kiệm 4–8 giờ/người/tuần', 'Người mới làm tốt như người cũ'],
    fit: ['Mọi doanh nghiệp muốn phổ cập AI'] },

  /* ---------- TRI THỨC & DỮ LIỆU ---------- */
  { id: 'rag', cat: 'know', code: 'K01', n: 'Trợ lý tri thức nội bộ (RAG)', tag: 'Hỏi gì đáp nấy trên tài liệu công ty, có trích nguồn', tl: '3–4 tuần', cx: 2,
    easy: 'Như một đồng nghiệp đã đọc hết mọi quy trình, chính sách, hợp đồng mẫu của công ty. Hỏi bằng tiếng Việt, trả lời ngay và chỉ rõ lấy từ tài liệu nào.',
    flow: [['Gom tài liệu', 'Word, PDF, Excel, Google Drive, wiki nội bộ.'], ['Lập chỉ mục', 'Chia tài liệu thành đoạn nhỏ và đánh dấu theo ý nghĩa để tìm nhanh.'], ['Nhân viên hỏi', '"Chính sách đổi trả với khách sỉ thế nào?"'], ['Tìm đoạn liên quan', 'Hệ thống lấy ra các đoạn tài liệu đúng nhất.'], ['Trả lời có nguồn', 'Tổng hợp câu trả lời, dẫn link tài liệu gốc.']],
    branch: [4, 'Không có thông tin trong tài liệu', 'AI trả lời "chưa có dữ liệu" thay vì tự bịa.'],
    ex: ['Hướng dẫn nhân viên mới', 'Tra cứu quy định, chính sách nhanh', 'Kỹ thuật viên tra tài liệu máy móc'],
    get: ['Rút ngắn 40–60% thời gian onboarding', 'Kiến thức không mất khi người cũ nghỉ việc'],
    fit: ['Nhiều tài liệu, quy trình; trên 30 nhân sự'] },
  { id: 'bi', cat: 'know', code: 'K02', n: 'AI phân tích dữ liệu & báo cáo', tag: 'Hỏi số liệu bằng tiếng Việt, nhận biểu đồ ngay', tl: '3–6 tuần', cx: 2,
    easy: 'Thay vì chờ nhân viên làm báo cáo, lãnh đạo chỉ cần hỏi "Tháng này chi nhánh nào giảm doanh thu, vì sao?". AI tự lấy số liệu, vẽ biểu đồ và giải thích.',
    flow: [['Kết nối dữ liệu', 'Phần mềm bán hàng, ERP, CRM, Google Sheets, quảng cáo.'], ['Làm sạch & hợp nhất', 'Gom về một kho dữ liệu chuẩn.'], ['Đặt câu hỏi', 'Gõ hoặc nói câu hỏi bằng tiếng Việt.'], ['AI truy vấn', 'Chuyển câu hỏi thành lệnh truy vấn dữ liệu (Text-to-SQL).'], ['Biểu đồ & nhận xét', 'Trả về biểu đồ, giải thích, cảnh báo bất thường.']],
    ex: ['Báo cáo doanh thu tự gửi lúc 8h sáng', 'Cảnh báo khi tồn kho hoặc chỉ số vượt ngưỡng'],
    get: ['Giảm 70–90% thời gian làm báo cáo', 'Quyết định dựa trên số liệu thật'],
    fit: ['Dữ liệu bán hàng, vận hành đã được số hóa'] },
  { id: 'predict', cat: 'know', code: 'K03', n: 'AI Dự báo & Tối ưu', tag: 'Dự đoán doanh số, tồn kho, khách sắp rời bỏ', tl: '6–10 tuần', cx: 3,
    easy: 'AI học từ dữ liệu quá khứ để đoán tương lai: tháng sau bán bao nhiêu, nên nhập bao nhiêu hàng, khách nào sắp bỏ đi. Giống dự báo thời tiết, nhưng cho việc kinh doanh.',
    flow: [['Dữ liệu lịch sử', 'Bán hàng, mùa vụ, khuyến mãi, thời tiết…'], ['Huấn luyện mô hình', 'Mô hình học quy luật từ dữ liệu.'], ['Dự báo', 'Đưa ra con số dự kiến kèm mức độ tin cậy.'], ['Đề xuất hành động', 'Gợi ý số lượng nhập, ngân sách, khách cần giữ chân.'], ['Học lại', 'So với thực tế, mô hình tự cải thiện.']],
    ex: ['Chuỗi bán lẻ dự báo nhập hàng từng cửa hàng', 'Dự đoán khách sắp hủy dịch vụ để giữ chân'],
    get: ['Giảm tồn kho và giảm hết hàng', 'Chủ động thay vì chữa cháy'],
    fit: ['Có ít nhất 1–2 năm dữ liệu'] },
  { id: 'personalize', cat: 'know', code: 'K04', n: 'Cá nhân hóa & Gợi ý', tag: 'Mỗi khách thấy đúng sản phẩm, đúng ưu đãi', tl: '4–8 tuần', cx: 2,
    easy: 'Giống người bán hàng nhớ từng khách quen: biết họ thích gì, đã mua gì, để gợi ý đúng món trên website, app, Zalo và email.',
    flow: [['Thu thập hành vi', 'Xem, mua, bấm, mở tin nhắn.'], ['Hồ sơ khách', 'Xây chân dung sở thích từng người.'], ['Tính gợi ý', 'Mô hình chọn sản phẩm, nội dung phù hợp nhất.'], ['Hiển thị đúng lúc', 'Trên web, app, Zalo ZNS, email.'], ['Đo hiệu quả', 'Thử nghiệm A/B và tối ưu liên tục.']],
    ex: ['"Khách mua X thường mua thêm Y"', 'Ưu đãi sinh nhật theo sở thích riêng'],
    get: ['Tăng giá trị đơn và tỷ lệ mua lại'],
    fit: ['Nhiều sản phẩm và tệp khách lớn'] },

  /* ---------- MARKETING & NỘI DUNG ---------- */
  { id: 'content', cat: 'mkt', code: 'M01', n: 'AI Content Engine', tag: 'Dây chuyền sản xuất nội dung đúng giọng thương hiệu', tl: '2–3 tuần', cx: 1,
    easy: 'Một "xưởng nội dung" AI: lên ý tưởng, viết bài, chuyển thể thành nhiều định dạng. Con người chỉ cần duyệt và chỉnh cho đúng chất.',
    flow: [['Brief & dữ liệu', 'Sản phẩm, chiến dịch, insight khách hàng.'], ['Lên lịch nội dung', 'AI đề xuất chủ đề 30 ngày theo mục tiêu.'], ['Viết đa định dạng', 'Bài Facebook, bài SEO, email, kịch bản video.'], ['Người duyệt', 'Duyệt 1 chạm trên Google Sheets hoặc Zalo.'], ['Đăng & đo', 'Lên lịch đăng, thu số liệu để tối ưu.']],
    ex: ['60 bài mỗi tháng cho 3 fanpage', 'Bài SEO hàng loạt cho website'],
    get: ['Gấp 3–5 lần sản lượng nội dung', 'Giọng thương hiệu nhất quán'],
    fit: ['Cần nội dung đều đặn trên nhiều kênh'] },
  { id: 'creative', cat: 'mkt', code: 'M02', n: 'AI hình ảnh & video', tag: 'Ảnh sản phẩm, banner, video ngắn trong vài phút', tl: '1–3 tuần', cx: 1,
    easy: 'Từ một ảnh sản phẩm chụp bằng điện thoại, AI tạo ra ảnh studio, banner quảng cáo, video ngắn. Không cần thuê chụp, thuê dựng mỗi lần.',
    flow: [['Ảnh gốc & ý tưởng', 'Ảnh sản phẩm, logo, thông điệp.'], ['AI tạo hình', 'Đổi nền, ghép bối cảnh, tạo người mẫu ảo.'], ['AI dựng video', 'Ghép cảnh, giọng đọc, phụ đề, nhạc.'], ['Kiểm soát thương hiệu', 'Đúng màu, font, logo và quy định quảng cáo.'], ['Xuất nhiều kích thước', 'Cho Facebook, TikTok, website, sàn TMĐT.']],
    ex: ['100 ảnh sản phẩm cho sàn TMĐT', 'Video TikTok mỗi ngày'],
    get: ['Chủ động sản xuất hình ảnh mỗi ngày, không chờ đợi'],
    fit: ['Nhiều mã sản phẩm, chạy quảng cáo thường xuyên'] },
  { id: 'listening', cat: 'mkt', code: 'M03', n: 'Lắng nghe mạng xã hội', tag: 'Biết khách đang nói gì về bạn và đối thủ', tl: '3–4 tuần', cx: 2,
    easy: 'AI đọc hàng nghìn bình luận, đánh giá, bài đăng để cho bạn biết khách khen gì, chê gì, đối thủ đang làm gì. Như có người theo dõi dư luận 24/7.',
    flow: [['Thu thập', 'Bình luận, đánh giá Google Maps, sàn TMĐT, hội nhóm.'], ['Phân tích cảm xúc', 'Tích cực, tiêu cực, trung lập theo từng chủ đề.'], ['Phát hiện vấn đề', 'Chủ đề nóng, dấu hiệu khủng hoảng.'], ['Cảnh báo', 'Báo ngay khi có làn sóng tiêu cực.'], ['Báo cáo insight', 'Tổng hợp hằng tuần: điểm mạnh, điểm yếu, cơ hội.']],
    ex: ['Chuỗi F&B theo dõi đánh giá từng chi nhánh', 'Thương hiệu phát hiện khủng hoảng sớm'],
    get: ['Phản ứng nhanh khi có sự cố', 'Insight để cải tiến sản phẩm'],
    fit: ['Thương hiệu bán lẻ, nhiều điểm bán'] },

  /* ---------- THỊ GIÁC & ROBOT VẬT LÝ ---------- */
  { id: 'vision', cat: 'phys', code: 'P01', n: 'Camera AI (Computer Vision)', tag: 'Camera biết nhìn: đếm, nhận diện, phát hiện lỗi', tl: '6–10 tuần', cx: 3,
    easy: 'Biến camera thường thành "con mắt thông minh": tự đếm khách, nhận ra hàng lỗi trên dây chuyền, phát hiện người không đội mũ bảo hộ, và báo ngay.',
    flow: [['Camera ghi hình', 'Dùng camera sẵn có hoặc lắp thêm.'], ['AI nhận diện', 'Mô hình thị giác nhận ra người, vật, lỗi, hành vi.'], ['Áp quy tắc', 'So với tiêu chuẩn: lỗi, vi phạm, quá đông.'], ['Cảnh báo tức thì', 'Báo qua Zalo, loa hoặc đèn cho người phụ trách.'], ['Thống kê', 'Dashboard lưu lượng, tỷ lệ lỗi theo ca.']],
    ex: ['Kiểm tra lỗi sản phẩm trên băng chuyền', 'Đếm lượt khách, thời gian chờ tại cửa hàng', 'Giám sát an toàn lao động'],
    get: ['Kiểm tra 100% thay vì lấy mẫu', 'Phát hiện sự cố ngay lập tức'],
    fit: ['Nhà máy, kho hàng, chuỗi cửa hàng'] },
  { id: 'robotics', cat: 'phys', code: 'P02', n: 'Robot vật lý + AI', tag: 'Robot phục vụ, robot kho, cánh tay robot', tl: '8–16 tuần', cx: 3,
    easy: 'Robot thật làm việc chân tay lặp lại: chạy món, chở hàng trong kho, gắp và xếp sản phẩm. AI giúp robot "nhìn", tránh vật cản và phối hợp với hệ thống.',
    flow: [['Khảo sát mặt bằng', 'Đo không gian, luồng di chuyển, công việc cần thay.'], ['Chọn & tích hợp', 'Robot phục vụ, robot tự hành chở hàng (AMR), cánh tay robot.'], ['Dạy robot', 'Lập bản đồ, tuyến đường, thao tác gắp – đặt.'], ['Kết nối hệ thống', 'Nhận lệnh từ phần mềm bán hàng hoặc quản lý kho.'], ['Giám sát & bảo trì', 'Theo dõi hiệu suất, bảo trì định kỳ.']],
    ex: ['Nhà hàng: robot chạy món', 'Kho: robot chở hàng tới khu đóng gói', 'Nhà máy: cánh tay robot đóng thùng'],
    get: ['Giảm việc nặng nhọc, làm liên tục 24/7'],
    fit: ['Việc chân tay lặp lại, khó tuyển lao động'] },
  { id: 'iot', cat: 'phys', code: 'P03', n: 'IoT + AI bảo trì dự đoán', tag: 'Máy móc báo trước khi hỏng', tl: '8–12 tuần', cx: 3,
    easy: 'Gắn cảm biến lên máy, AI theo dõi độ rung, nhiệt độ, điện năng và báo "máy này sắp hỏng" trước khi nó làm dừng dây chuyền. Như khám sức khỏe định kỳ cho máy.',
    flow: [['Gắn cảm biến', 'Nhiệt độ, độ rung, dòng điện, áp suất.'], ['Truyền dữ liệu', 'Gửi liên tục về máy chủ hoặc cloud.'], ['Học "nhịp bình thường"', 'AI hiểu khi máy khỏe thì chạy thế nào.'], ['Phát hiện bất thường', 'Thấy dấu hiệu sắp hỏng trước nhiều ngày.'], ['Lên lịch bảo trì', 'Tạo phiếu bảo trì, đặt phụ tùng trước.']],
    ex: ['Máy nén, máy ép trong nhà máy', 'Hệ thống lạnh kho thực phẩm'],
    get: ['Giảm dừng máy đột xuất', 'Kéo dài tuổi thọ thiết bị'],
    fit: ['Có máy móc giá trị cao, chạy liên tục'] },

  /* ---------- NỀN TẢNG LLM ---------- */
  { id: 'llmapi', cat: 'llm', code: 'L01', n: 'LLM trên Cloud công cộng', tag: 'Dùng GPT, Claude, Gemini qua API doanh nghiệp', tl: '1–2 tuần', cx: 1,
    easy: 'Như dùng điện lưới: không cần xây nhà máy, dùng bao nhiêu trả bấy nhiêu. "Bộ não" AI nằm ở trung tâm dữ liệu của nhà cung cấp lớn; ứng dụng của bạn gửi câu hỏi và nhận câu trả lời.',
    flow: [['Ứng dụng của bạn', 'Chatbot, agent, workflow gửi yêu cầu.'], ['Che dữ liệu nhạy cảm', 'Ẩn số CCCD, số điện thoại… trước khi gửi đi.'], ['Gửi tới LLM cloud', 'Qua kết nối mã hóa tới OpenAI, Anthropic, Google.'], ['Nhận kết quả', 'Mô hình trả lời trong vài giây.'], ['Theo dõi sử dụng', 'Ghi nhật ký lượng dùng theo phòng ban.']],
    ex: ['Khởi đầu nhanh cho mọi dự án AI', 'Doanh nghiệp vừa và nhỏ'],
    get: ['Triển khai ngay với mô hình mạnh nhất', 'Không cần máy chủ riêng'],
    fit: ['Dữ liệu không quá nhạy cảm', 'Muốn bắt đầu nhanh, linh hoạt'] },
  { id: 'llmprivate', cat: 'llm', code: 'L02', n: 'LLM trên Cloud riêng', tag: 'Mô hình AI chạy trong vùng cloud riêng của doanh nghiệp', tl: '4–8 tuần', cx: 2,
    easy: 'Như thuê nguyên một căn hộ có khóa riêng trong tòa nhà lớn: dùng hạ tầng cloud mạnh, nhưng mô hình AI và dữ liệu nằm trong "vùng riêng" chỉ doanh nghiệp bạn truy cập được.',
    flow: [['Tạo vùng cloud riêng', 'Vùng mạng riêng (VPC) trên AWS, Azure, Google Cloud hoặc cloud trong nước.'], ['Triển khai mô hình', 'Mô hình mã nguồn mở (Llama, Qwen…) hoặc dịch vụ LLM riêng.'], ['Kết nối bảo mật', 'Đường kết nối riêng từ văn phòng, không đi qua internet công cộng.'], ['Ứng dụng sử dụng', 'Chatbot, trợ lý tri thức, agent gọi vào mô hình riêng.'], ['Mở rộng linh hoạt', 'Tăng giảm máy chủ GPU theo nhu cầu.']],
    ex: ['Ngân hàng, bảo hiểm cần kiểm soát dữ liệu', 'Doanh nghiệp đa chi nhánh, nhiều người dùng'],
    get: ['Dữ liệu không rời vùng riêng', 'Không phải mua và quản lý máy chủ'],
    fit: ['Dữ liệu nhạy cảm nhưng muốn linh hoạt'] },
  { id: 'llmonprem', cat: 'llm', code: 'L03', n: 'LLM On-premise', tag: 'Máy chủ AI đặt ngay tại doanh nghiệp, dữ liệu không ra ngoài', tl: '6–12 tuần', cx: 3,
    easy: 'Như tự xây nhà máy điện riêng: máy chủ GPU đặt trong phòng server của bạn, AI chạy hoàn toàn nội bộ, ngắt internet vẫn chạy. Dữ liệu không bao giờ rời khỏi công ty.',
    flow: [['Tư vấn cấu hình', 'Tính số người dùng, chọn GPU và máy chủ phù hợp.'], ['Lắp đặt phần cứng', 'Máy chủ GPU tại phòng server của doanh nghiệp.'], ['Cài mô hình', 'Mô hình mã nguồn mở, tối ưu cho tiếng Việt và tốc độ.'], ['Tích hợp nội bộ', 'Kết nối tài khoản nhân viên, tài liệu, phần mềm nội bộ.'], ['Vận hành & cập nhật', 'Giám sát, nâng cấp mô hình mới định kỳ.']],
    ex: ['Cơ quan, doanh nghiệp nhà nước', 'Nhà máy, bệnh viện có dữ liệu mật'],
    get: ['Kiểm soát 100% dữ liệu', 'Vẫn hoạt động khi không có internet'],
    fit: ['Yêu cầu bảo mật cao nhất', 'Nhiều người dùng thường xuyên'] },
  { id: 'finetune', cat: 'llm', code: 'L04', n: 'Fine-tuning mô hình riêng', tag: 'Dạy AI nói đúng chuyên môn và văn phong doanh nghiệp', tl: '4–8 tuần', cx: 3,
    easy: 'Mô hình AI chung giống sinh viên giỏi mới ra trường. Fine-tuning là cho "thực tập chuyên sâu" tại công ty bạn để nói đúng thuật ngữ, đúng văn phong, đúng nghiệp vụ.',
    flow: [['Chuẩn bị dữ liệu', 'Hàng nghìn ví dụ hỏi–đáp, văn bản chuẩn.'], ['Làm sạch & gán nhãn', 'Loại dữ liệu sai, ẩn thông tin cá nhân.'], ['Huấn luyện', 'Tinh chỉnh mô hình trên máy chủ GPU.'], ['Đánh giá', 'So với mô hình gốc trên bộ câu hỏi kiểm tra.'], ['Triển khai', 'Đưa lên cloud riêng hoặc máy chủ on-premise.']],
    ex: ['Mô hình hiểu thuật ngữ y khoa, pháp lý', 'Mô hình viết đúng văn phong hành chính'],
    get: ['Chính xác hơn trên nghiệp vụ chuyên sâu', 'Mô hình nhỏ hơn, chạy nhanh hơn'],
    fit: ['Đã có nhiều dữ liệu mẫu chất lượng'] },
  { id: 'gateway', cat: 'llm', code: 'L05', n: 'AI Gateway & LLMOps', tag: 'Một cổng kiểm soát mọi AI trong công ty', tl: '3–5 tuần', cx: 2,
    easy: 'Như phòng bảo vệ kiêm điều phối cho AI: mọi yêu cầu đi qua một cổng duy nhất để chặn dữ liệu nhạy cảm, đổi mô hình khi cần, theo dõi mức sử dụng và chất lượng.',
    flow: [['Ứng dụng gọi AI', 'Mọi chatbot, agent, công cụ nội bộ.'], ['Xác thực', 'Kiểm tra ai đang dùng, được phép làm gì.'], ['Bảo vệ dữ liệu', 'Che thông tin nhạy cảm, chặn yêu cầu nguy hiểm.'], ['Chọn mô hình', 'Việc nhẹ dùng mô hình nhanh, việc khó dùng mô hình mạnh.'], ['Giám sát', 'Dashboard mức sử dụng, tốc độ, chất lượng, nhật ký kiểm toán.']],
    branch: [3, 'Nhà cung cấp AI gặp sự cố', 'tự chuyển sang mô hình dự phòng, người dùng không bị gián đoạn.'],
    ex: ['Doanh nghiệp dùng nhiều mô hình AI cùng lúc'],
    get: ['Dùng đúng mô hình cho đúng việc', 'Kiểm soát rủi ro tập trung'],
    fit: ['Có từ 3 ứng dụng AI trở lên'] },

  /* ---------- CHIẾN LƯỢC & QUẢN TRỊ ---------- */
  { id: 'strategy', cat: 'gov', code: 'S01', n: 'Tư vấn chiến lược & lộ trình AI', tag: 'Biết làm gì trước, cần nguồn lực gì, đo thế nào', tl: '2–6 tuần', cx: 1,
    easy: 'Xây nhà cần bản vẽ trước. Drabuff AI cùng ban lãnh đạo đánh giá hiện trạng, chọn những việc AI đáng làm nhất và vẽ lộ trình 3–12 tháng có KPI rõ ràng.',
    flow: [['Đánh giá hiện trạng', 'Phỏng vấn các phòng ban, đánh giá dữ liệu và hệ thống.'], ['Tìm cơ hội', 'Liệt kê 20–30 việc có thể ứng dụng AI.'], ['Chấm điểm ưu tiên', 'Xếp theo giá trị và độ khó, chọn việc thắng nhanh.'], ['Lộ trình & nguồn lực', 'Kế hoạch theo giai đoạn, nhân sự, KPI.'], ['Đồng hành thực thi', 'Theo dõi và điều chỉnh theo kết quả thực tế.']],
    ex: ['Doanh nghiệp chưa biết bắt đầu từ đâu', 'Tập đoàn cần chiến lược AI toàn diện'],
    get: ['Làm đúng việc, tránh thử nghiệm lan man', 'Lộ trình được ban lãnh đạo đồng thuận'],
    fit: ['Mọi doanh nghiệp trước khi triển khai lớn'] },
  { id: 'governance', cat: 'gov', code: 'S02', n: 'Quản trị AI & bảo mật dữ liệu', tag: 'Dùng AI an toàn, đúng luật bảo vệ dữ liệu cá nhân', tl: '3–6 tuần', cx: 2,
    easy: 'Bộ "luật chơi" cho AI trong công ty: dữ liệu nào được đưa vào AI, ai được dùng, kiểm tra kết quả thế nào. Phù hợp Nghị định 13/2023 về bảo vệ dữ liệu cá nhân.',
    flow: [['Rà soát rủi ro', 'Kiểm tra dữ liệu và công cụ AI nhân viên đang tự dùng.'], ['Phân loại dữ liệu', 'Công khai, nội bộ, mật, dữ liệu cá nhân.'], ['Ban hành quy chế', 'Chính sách sử dụng AI và quy trình phê duyệt.'], ['Kiểm soát kỹ thuật', 'Phân quyền, che dữ liệu, ghi nhật ký.'], ['Đào tạo & kiểm tra', 'Tập huấn nhân viên, kiểm tra định kỳ.']],
    ex: ['Doanh nghiệp xử lý nhiều dữ liệu khách hàng', 'Chuẩn bị làm việc với đối tác nước ngoài'],
    get: ['Giảm rủi ro lộ dữ liệu, vi phạm pháp luật'],
    fit: ['Doanh nghiệp đã hoặc sắp dùng AI'] },
  { id: 'training', cat: 'gov', code: 'S03', n: 'Đào tạo AI Inhouse', tag: 'Đội ngũ dùng thành thạo AI vào việc thật', tl: '1–3 tuần', cx: 1,
    easy: 'Công cụ tốt mà người không biết dùng thì cũng vô ích. Khóa học được may đo theo công việc của từng phòng ban, học xong là làm được ngay.',
    flow: [['Khảo sát năng lực', 'Kiểm tra đầu vào, phỏng vấn quản lý.'], ['Thiết kế giáo trình', 'Theo phòng ban, ngành và công cụ đang dùng.'], ['Đào tạo thực chiến', 'Mỗi buổi ra một sản phẩm dùng được.'], ['Dự án cuối khóa', 'Giải một bài toán thật của doanh nghiệp.'], ['Đồng hành 30 ngày', 'Hỗ trợ áp dụng và đo kết quả.']],
    ex: ['Phổ cập AI cho toàn công ty', 'AI Leadership cho ban giám đốc'],
    get: ['Văn hóa dùng AI lan tỏa', 'Số giờ tiết kiệm đo được'],
    fit: ['Đi kèm mọi dự án triển khai AI'] },
  { id: 'managed', cat: 'gov', code: 'S04', n: 'Vận hành & bảo trì AI trọn gói', tag: 'Drabuff AI chăm sóc hệ thống sau triển khai', tl: 'Hằng tháng', cx: 1,
    easy: 'AI không phải lắp xong là xong. Như bảo dưỡng xe định kỳ: theo dõi chất lượng câu trả lời, cập nhật kiến thức mới, nâng cấp mô hình, xử lý sự cố.',
    flow: [['Giám sát 24/7', 'Theo dõi hệ thống có chạy ổn, có lỗi, có chậm không.'], ['Chấm chất lượng', 'Đánh giá câu trả lời, phát hiện trả lời sai.'], ['Cập nhật tri thức', 'Thêm sản phẩm, chính sách mới.'], ['Tối ưu', 'Chuyển sang mô hình mới tốt hơn, nhanh hơn.'], ['Báo cáo tháng', 'KPI và đề xuất cải tiến.']],
    ex: ['Doanh nghiệp không có đội AI riêng'],
    get: ['Hệ thống ổn định và ngày càng tốt hơn'],
    fit: ['Sau khi triển khai bất kỳ giải pháp nào'] }
];

/* layered architecture, top (người dùng) → bottom (hạ tầng) */
window.LAYERS = [
  { n: 'Điểm chạm', d: 'Nơi khách hàng và nhân viên gặp AI', ids: ['chatbot', 'voice', 'salesagent', 'avatar', 'copilot'] },
  { n: 'Ứng dụng & tự động hóa', d: 'Các dây chuyền làm việc thay con người', ids: ['workflow', 'rpa', 'idp', 'inbox', 'content', 'creative', 'listening'] },
  { n: 'Agent · bộ não hành động', d: 'AI tự lên kế hoạch và điều phối công việc', ids: ['agent', 'multiagent', 'computeruse'] },
  { n: 'Tri thức & dữ liệu', d: 'Thứ AI cần biết để trả lời đúng về công ty bạn', ids: ['rag', 'bi', 'predict', 'personalize'] },
  { n: 'Thế giới thật', d: 'Camera, cảm biến, robot đưa AI ra khỏi màn hình', ids: ['vision', 'robotics', 'iot'] },
  { n: 'Nền tảng mô hình AI', d: 'Nơi đặt "bộ não": cloud công cộng, cloud riêng, on-premise', ids: ['llmapi', 'llmprivate', 'llmonprem', 'finetune', 'gateway'] }
];
