/* Drabuff AI — catalogue v2: new services, per-service specs, finder, maturity, scenarios, glossary */
(function () {
  var CATS = window.CATS, SV = window.SERVICES;
  CATS.splice(5, 0, { id: 'dept', n: 'Giải pháp theo phòng ban', d: 'Gói AI may sẵn cho từng phòng ban: nhân sự, tài chính, pháp chế, mua hàng.' });

  var NEW = [
    { id: 'journey', cat: 'cx', code: 'C05', n: 'Chăm sóc khách tự động', tag: 'Gửi đúng tin, đúng người, đúng lúc qua Zalo ZNS, email, SMS', tl: '3–5 tuần', cx: 2,
      easy: 'Như có người nhớ từng khách: hôm nay sinh nhật ai, ai mua đã 30 ngày cần nhắc, ai bỏ giỏ hàng. AI tự soạn lời nhắn riêng cho từng người và gửi đúng lúc.',
      flow: [['Khách có hành động', 'Mua hàng, bỏ giỏ, đăng ký, lâu không quay lại.'], ['Phân nhóm khách', 'AI xếp khách vào nhóm theo hành vi và mức độ gắn bó.'], ['Chọn kịch bản', 'Cảm ơn, nhắc lịch, ưu đãi riêng cho từng nhóm.'], ['AI viết lời nhắn', 'Cá nhân hóa theo tên, sản phẩm đã mua, sở thích.'], ['Gửi & đo', 'Gửi qua Zalo ZNS, email, SMS; đo tỷ lệ mở và mua lại.']],
      ex: ['Nhắc tái khám, nhắc thay lõi lọc nước định kỳ', 'Chuỗi tin chào mừng khách mới trong 7 ngày', 'Kéo khách lâu không mua quay lại'],
      get: ['Tăng tỷ lệ mua lại', 'Không bỏ quên khách cũ', 'Chăm sóc hàng nghìn khách không cần thêm người'],
      fit: ['Tệp khách từ vài nghìn người trở lên', 'Sản phẩm, dịch vụ được mua lặp lại'] },
    { id: 'translate', cat: 'cx', code: 'C06', n: 'AI Phiên dịch đa ngôn ngữ', tag: 'Trò chuyện, họp, tư vấn với người nước ngoài theo thời gian thực', tl: '2–4 tuần', cx: 2,
      easy: 'Như có phiên dịch viên ngồi cạnh mọi lúc: khách nhắn tiếng Hàn, nhân viên đọc và trả lời bằng tiếng Việt, khách nhận lại bằng tiếng Hàn.',
      flow: [['Khách nhắn hoặc nói', 'Bằng tiếng Anh, Trung, Hàn, Nhật…'], ['Nhận dạng ngôn ngữ', 'AI tự biết khách đang dùng ngôn ngữ nào.'], ['Dịch theo ngữ cảnh', 'Đúng thuật ngữ ngành, đúng văn phong lịch sự.'], ['Nhân viên trả lời', 'Bằng tiếng Việt như bình thường.'], ['Dịch ngược cho khách', 'Khách nhận câu trả lời bằng ngôn ngữ của mình.']],
      ex: ['Khách sạn, spa phục vụ khách quốc tế', 'Nhà máy làm việc với chuyên gia nước ngoài', 'Doanh nghiệp xuất khẩu trao đổi với đối tác'],
      get: ['Phục vụ khách quốc tế không cần tuyển phiên dịch', 'Giao tiếp nhanh, đúng thuật ngữ'],
      fit: ['Có khách hoặc đối tác nước ngoài thường xuyên'] },
    { id: 'integration', cat: 'agent', code: 'G05', n: 'Tích hợp AI vào hệ thống (API & MCP)', tag: 'Cho AI kết nối an toàn với CRM, ERP, kho và phần mềm nội bộ', tl: '3–6 tuần', cx: 2,
      easy: 'AI giỏi đến đâu mà không chạm được vào dữ liệu công ty thì cũng chỉ nói chung chung. Tích hợp là lắp "ổ cắm" chuẩn để AI đọc tồn kho, tạo đơn, cập nhật khách hàng, đúng quyền được cấp.',
      flow: [['Liệt kê hệ thống', 'CRM, ERP, phần mềm bán hàng, kho, Google Workspace.'], ['Thiết kế "ổ cắm"', 'Tạo kết nối chuẩn (API, MCP server) cho từng chức năng.'], ['Phân quyền', 'AI chỉ được đọc/ghi đúng phần được cho phép.'], ['Kết nối AI', 'Chatbot, agent, trợ lý dùng chung các ổ cắm này.'], ['Giám sát', 'Ghi lại mọi lần AI truy cập dữ liệu.']],
      ex: ['Chatbot tra tồn kho thật từ phần mềm kho', 'Agent tạo đơn trực tiếp trên CRM', 'Trợ lý đọc công nợ từ ERP'],
      get: ['AI trả lời bằng dữ liệu thật, cập nhật từng phút', 'Tích hợp một lần, nhiều ứng dụng AI dùng chung'],
      fit: ['Đã có phần mềm quản lý và muốn AI dùng được'] },
    { id: 'dataplatform', cat: 'know', code: 'K05', n: 'Dữ liệu sẵn sàng cho AI', tag: 'Gom, làm sạch và chuẩn hóa dữ liệu để AI dùng được', tl: '4–8 tuần', cx: 2,
      easy: 'AI giống đầu bếp: nguyên liệu bẩn thì món ăn dở. Bước này dọn "kho nguyên liệu": gom dữ liệu rải rác về một nơi, làm sạch, đặt tên thống nhất.',
      flow: [['Kiểm kê dữ liệu', 'Dữ liệu đang nằm ở đâu: Excel, phần mềm, giấy tờ.'], ['Thu thập tự động', 'Kết nối để dữ liệu tự chảy về kho chung.'], ['Làm sạch', 'Xóa trùng, sửa sai, thống nhất định dạng.'], ['Chuẩn hóa', 'Định nghĩa thống nhất: thế nào là "khách mới", "doanh thu".'], ['Sẵn sàng phục vụ', 'Báo cáo, dự báo, chatbot, agent cùng dùng một nguồn đúng.']],
      ex: ['Gom dữ liệu bán hàng từ 10 chi nhánh', 'Hợp nhất khách hàng trùng giữa các kênh'],
      get: ['Một nguồn số liệu đúng cho cả công ty', 'Nền móng cho mọi dự án AI sau này'],
      fit: ['Dữ liệu nằm rải rác ở nhiều nơi'] },
    { id: 'meeting', cat: 'know', code: 'K06', n: 'AI biên bản & phân tích hội thoại', tag: 'Biên bản họp tự động, phân tích cuộc gọi bán hàng và CSKH', tl: '2–3 tuần', cx: 1,
      easy: 'Như có thư ký ngồi trong mọi cuộc họp và cuộc gọi: ghi lại, tóm tắt, liệt kê việc cần làm, và chỉ ra cuộc gọi nào sales xử lý tốt, cuộc nào chưa.',
      flow: [['Ghi âm', 'Cuộc họp online/offline, cuộc gọi tổng đài.'], ['Chuyển thành chữ', 'Nhận dạng giọng nói tiếng Việt, phân biệt người nói.'], ['Tóm tắt', 'Ý chính, quyết định, việc cần làm, người phụ trách.'], ['Phân tích', 'Chấm điểm cuộc gọi theo kịch bản, cảm xúc khách.'], ['Gửi & lưu', 'Gửi biên bản cho người dự; lưu vào CRM hoặc Drive.']],
      ex: ['Biên bản giao ban tự động', 'Chấm điểm 100% cuộc gọi sales', 'Phát hiện khách không hài lòng qua cuộc gọi'],
      get: ['Không còn quên việc sau cuộc họp', 'Huấn luyện sales dựa trên cuộc gọi thật'],
      fit: ['Họp nhiều, có tổng đài hoặc đội telesales'] },
    { id: 'seo', cat: 'mkt', code: 'M04', n: 'AI SEO & GEO', tag: 'Xuất hiện trên Google và trong câu trả lời của ChatGPT, Gemini', tl: '4–8 tuần', cx: 2,
      easy: 'Khách hàng giờ không chỉ tìm trên Google mà còn hỏi chatbot AI. GEO giúp thương hiệu của bạn được AI nhắc tên khi khách hỏi "nên chọn ở đâu".',
      flow: [['Nghiên cứu câu hỏi', 'Khách thường hỏi gì trên Google và chatbot AI.'], ['Kiểm tra hiện diện', 'Thương hiệu đang được AI nhắc tới thế nào.'], ['Sản xuất nội dung chuẩn', 'Bài chuyên sâu, có dữ liệu, cấu trúc rõ ràng.'], ['Tối ưu kỹ thuật', 'Schema, tốc độ, liên kết, hồ sơ doanh nghiệp.'], ['Theo dõi thứ hạng', 'Thứ hạng Google và tần suất được AI trích dẫn.']],
      ex: ['Phòng khám được AI gợi ý khi khách hỏi "khám da ở đâu uy tín"', 'Website B2B lên top từ khóa ngành'],
      get: ['Tăng khách tự tìm đến', 'Có mặt ở kênh tìm kiếm mới'],
      fit: ['Có website, muốn giảm phụ thuộc vào quảng cáo'] },
    { id: 'ads', cat: 'mkt', code: 'M05', n: 'AI tối ưu quảng cáo', tag: 'Phân tích, thử nghiệm và tối ưu quảng cáo Facebook, Google, TikTok', tl: '2–4 tuần', cx: 2,
      easy: 'Như có chuyên viên quảng cáo theo dõi số liệu từng giờ: mẫu nào hiệu quả thì đề xuất tăng, mẫu nào kém thì đề xuất dừng, liên tục tạo mẫu mới để thử.',
      flow: [['Kết nối tài khoản', 'Facebook, Google, TikTok Ads và dữ liệu đơn hàng thật.'], ['Phân tích hiệu quả', 'Mẫu, đối tượng, khung giờ nào mang lại khách thật.'], ['Tạo mẫu mới', 'AI viết tiêu đề, nội dung, gợi ý hình ảnh để thử.'], ['Đề xuất điều chỉnh', 'Tăng, giảm, dừng nhóm quảng cáo theo quy tắc.'], ['Báo cáo', 'Tổng hợp hằng ngày, giải thích bằng lời dễ hiểu.']],
      ex: ['Shop TMĐT thử 30 mẫu quảng cáo mỗi tuần', 'Doanh nghiệp B2B lọc lead chất lượng từ Google Ads'],
      get: ['Ra quyết định quảng cáo nhanh hơn', 'Thử nhiều mẫu hơn, tìm ra mẫu tốt sớm hơn'],
      fit: ['Chạy quảng cáo thường xuyên trên nhiều nền tảng'] },
    { id: 'hr', cat: 'dept', code: 'D01', n: 'AI cho Nhân sự (HR)', tag: 'Tuyển dụng, onboarding và hỏi đáp chính sách nhân sự', tl: '3–5 tuần', cx: 2,
      easy: 'Một bộ trợ lý cho phòng nhân sự: viết tin tuyển dụng, lọc CV, hẹn phỏng vấn, đón nhân viên mới và trả lời câu hỏi về nghỉ phép, bảo hiểm, quy định.',
      flow: [['Viết JD & đăng tuyển', 'AI viết tin tuyển dụng hấp dẫn, đăng nhiều kênh.'], ['Lọc CV', 'Chấm điểm hồ sơ theo tiêu chí vị trí, có giải thích.'], ['Hẹn phỏng vấn', 'Tự gửi lịch, nhắc ứng viên, chuẩn bị câu hỏi.'], ['Onboarding', 'Lộ trình 30 ngày, tài liệu, trợ lý hỏi đáp cho người mới.'], ['Hỏi đáp chính sách', 'Nhân viên hỏi về nghỉ phép, bảo hiểm, quy định 24/7.']],
      ex: ['Tuyển 200 công nhân mùa cao điểm', 'Hỏi đáp chính sách cho 1.000 nhân viên'],
      get: ['Rút ngắn thời gian tuyển dụng', 'HR tập trung vào con người thay vì giấy tờ'],
      fit: ['Tuyển dụng thường xuyên, nhiều nhân sự'] },
    { id: 'finance', cat: 'dept', code: 'D02', n: 'AI cho Tài chính – Kế toán', tag: 'Nhập chứng từ, đối soát, nhắc công nợ, báo cáo và dự báo dòng tiền', tl: '4–8 tuần', cx: 2,
      easy: 'Phòng kế toán có thêm "đồng nghiệp số" làm phần việc nặng: nhập hóa đơn, đối soát ngân hàng, nhắc công nợ, lập báo cáo và cảnh báo dòng tiền.',
      flow: [['Thu chứng từ', 'Hóa đơn điện tử, sao kê, chứng từ giấy.'], ['Đọc & nhập liệu', 'AI trích xuất và nhập vào phần mềm kế toán.'], ['Đối soát', 'So khớp hóa đơn, thanh toán, sao kê; đánh dấu chênh lệch.'], ['Nhắc công nợ', 'Tự gửi nhắc thanh toán theo lịch và lịch sử khách.'], ['Báo cáo & dự báo', 'Báo cáo nhanh, dự báo dòng tiền các tuần tới.']],
      branch: [2, 'Có khoản chênh lệch không tự giải thích được', 'đưa vào danh sách chờ kế toán trưởng duyệt.'],
      ex: ['Đối soát sao kê hằng ngày', 'Nhắc công nợ đại lý tự động', 'Báo cáo quản trị đầu tháng'],
      get: ['Khóa sổ cuối tháng nhanh hơn', 'Phát hiện chênh lệch sớm', 'Chủ động dòng tiền'],
      fit: ['Nhiều chứng từ, nhiều đối tác, nhiều tài khoản ngân hàng'] },
    { id: 'legal', cat: 'dept', code: 'D03', n: 'AI cho Pháp chế & Hợp đồng', tag: 'Rà soát hợp đồng, so sánh phiên bản, tra cứu quy định', tl: '3–6 tuần', cx: 2,
      easy: 'AI đọc hợp đồng trong vài phút, chỉ ra điều khoản bất lợi, thiếu sót hoặc khác mẫu chuẩn của công ty, để pháp chế tập trung vào phần cần chuyên môn.',
      flow: [['Tải hợp đồng', 'File Word/PDF từ đối tác.'], ['So với mẫu chuẩn', 'Đối chiếu với bộ điều khoản chuẩn của công ty.'], ['Đánh dấu rủi ro', 'Điều khoản bất lợi, mơ hồ, thiếu; xếp theo mức độ.'], ['Đề xuất sửa', 'Gợi ý câu chữ thay thế kèm giải thích.'], ['Pháp chế duyệt', 'Luật sư/pháp chế xem lại và quyết định.']],
      ex: ['Rà soát hợp đồng mua bán hàng loạt', 'Tra cứu quy định mới liên quan đến ngành'],
      get: ['Rà soát nhanh hơn nhiều lần', 'Không bỏ sót điều khoản quan trọng'],
      fit: ['Ký nhiều hợp đồng mỗi tháng'] },
    { id: 'supply', cat: 'dept', code: 'D04', n: 'AI cho Mua hàng & Chuỗi cung ứng', tag: 'Dự báo nhu cầu, gợi ý đặt hàng, theo dõi nhà cung cấp', tl: '6–10 tuần', cx: 3,
      easy: 'AI theo dõi tồn kho, dự báo bán hàng, gợi ý đặt hàng đúng lúc đúng lượng, và cảnh báo khi nhà cung cấp giao chậm.',
      flow: [['Gom dữ liệu', 'Tồn kho, bán hàng, đơn mua, nhà cung cấp.'], ['Dự báo nhu cầu', 'Dự đoán lượng bán từng mã hàng theo tuần.'], ['Gợi ý đặt hàng', 'Đề xuất số lượng, thời điểm, nhà cung cấp.'], ['Theo dõi giao hàng', 'Cảnh báo chậm trễ, sai số lượng.'], ['Đánh giá nhà cung cấp', 'Chấm điểm chất lượng, mức đúng hạn.']],
      ex: ['Chuỗi bán lẻ đặt hàng cho 50 cửa hàng', 'Nhà máy lập kế hoạch nguyên vật liệu'],
      get: ['Giảm tồn kho dư thừa', 'Giảm tình trạng hết hàng', 'Quan hệ nhà cung cấp minh bạch'],
      fit: ['Nhiều mã hàng, nhiều điểm bán hoặc nhà cung cấp'] },
    { id: 'face', cat: 'phys', code: 'P04', n: 'Nhận diện khuôn mặt & ra vào', tag: 'Chấm công, kiểm soát ra vào, nhận diện khách VIP', tl: '3–6 tuần', cx: 2,
      easy: 'Camera nhận ra nhân viên để chấm công không cần quẹt thẻ, mở cửa đúng người, và báo lễ tân khi khách VIP bước vào.',
      flow: [['Đăng ký khuôn mặt', 'Nhân viên/khách đồng ý đăng ký ảnh mẫu.'], ['Camera nhận diện', 'Nhận ra người trong chưa tới một giây.'], ['Kiểm tra quyền', 'Người này được vào khu vực nào, ca làm nào.'], ['Hành động', 'Mở cửa, ghi chấm công, báo lễ tân.'], ['Báo cáo', 'Bảng công, lịch sử ra vào, cảnh báo người lạ.']],
      branch: [2, 'Người lạ hoặc không đủ quyền', 'không mở cửa và gửi cảnh báo cho bảo vệ.'],
      ex: ['Chấm công nhà máy hàng nghìn công nhân', 'Kiểm soát ra vào kho, phòng server', 'Nhận diện khách VIP tại showroom'],
      get: ['Chấm công chính xác, không chấm hộ', 'An ninh chặt chẽ hơn'],
      fit: ['Nhiều nhân sự, nhiều khu vực cần kiểm soát'] },
    { id: 'edge', cat: 'llm', code: 'L06', n: 'Edge AI · AI chạy tại thiết bị', tag: 'AI xử lý ngay tại camera, máy tính, thiết bị tại chỗ', tl: '6–10 tuần', cx: 3,
      easy: 'Thay vì gửi mọi thứ lên cloud, AI được đặt ngay trong thiết bị nhỏ tại cửa hàng hay nhà máy. Phản hồi tức thì, chạy cả khi mất mạng, dữ liệu không đi xa.',
      flow: [['Chọn bài toán', 'Việc cần phản ứng tức thì hoặc nơi mạng yếu.'], ['Thu gọn mô hình', 'Nén mô hình AI để chạy trên thiết bị nhỏ.'], ['Cài lên thiết bị', 'Máy tính nhúng, camera AI, máy chủ mini tại chỗ.'], ['Xử lý tại chỗ', 'Phân tích ngay, chỉ gửi kết quả về trung tâm.'], ['Cập nhật từ xa', 'Nâng cấp mô hình cho hàng loạt thiết bị.']],
      ex: ['Camera kiểm lỗi trên dây chuyền tốc độ cao', 'Kiosk tư vấn tại cửa hàng', 'Công trường không có internet ổn định'],
      get: ['Phản hồi tính bằng mili giây', 'Hoạt động khi mất mạng', 'Giảm lượng dữ liệu phải truyền đi'],
      fit: ['Nhiều điểm bán, nhà máy, nơi mạng không ổn định'] },
    { id: 'eval', cat: 'gov', code: 'S05', n: 'Kiểm thử & đánh giá AI', tag: 'Đo AI trả lời đúng bao nhiêu trước khi đưa ra phục vụ khách', tl: '2–4 tuần', cx: 2,
      easy: 'Như kiểm định xe trước khi lăn bánh: cho AI làm bài kiểm tra với hàng trăm câu hỏi thật, thử cả câu hỏi "gài bẫy", chấm điểm rồi mới cho phục vụ khách.',
      flow: [['Xây bộ đề', 'Câu hỏi thật của khách, tình huống khó, câu gài bẫy.'], ['Chạy kiểm tra', 'AI trả lời toàn bộ bộ đề một cách tự động.'], ['Chấm điểm', 'Đúng/sai, đầy đủ, an toàn, đúng giọng thương hiệu.'], ['Tấn công thử', 'Thử khiến AI nói sai, lộ dữ liệu, vượt quy định.'], ['Báo cáo & sửa', 'Chỉ ra lỗi, sửa, rồi kiểm tra lại.']],
      ex: ['Kiểm tra chatbot trước ngày ra mắt', 'Đánh giá lại sau mỗi lần cập nhật mô hình'],
      get: ['Biết rõ AI trả lời đúng bao nhiêu phần trăm', 'Giảm rủi ro AI nói sai với khách'],
      fit: ['Trước khi đưa bất kỳ AI nào ra phục vụ khách'] }
  ];
  // insert each new service after the last one of its category
  NEW.forEach(function (s) {
    var last = -1; SV.forEach(function (x, i) { if (x.cat === s.cat) last = i; });
    if (last < 0) { var ci = CATS.map(function (c) { return c.id; }).indexOf(s.cat); last = -1; SV.forEach(function (x, i) { if (CATS.map(function (c) { return c.id; }).indexOf(x.cat) < ci) last = i; }); }
    SV.splice(last + 1, 0, s);
  });

  /* ---- per-service specs: sz (quy mô), need (cần chuẩn bị), kpi, tech, ba (trước/sau), human (con người kiểm soát) ---- */
  var X = {
    chatbot: { sz: 'Mọi quy mô', need: ['Bộ câu hỏi thường gặp, chính sách, thông tin sản phẩm', 'Tài khoản Zalo OA, Fanpage, website', 'Kịch bản chuyển cho nhân viên'], kpi: ['Tỷ lệ AI tự xử lý', 'Thời gian phản hồi trung bình', 'Số lead thu được ngoài giờ'], tech: ['Zalo OA', 'Messenger', 'Web chat', 'LLM + RAG', 'CRM'], ba: [['Thời gian phản hồi', 'Vài phút đến vài giờ', 'Dưới 10 giây'], ['Ngoài giờ hành chính', 'Không ai trực', 'Tư vấn 24/7'], ['Thông tin khách', 'Ghi tay, dễ thất lạc', 'Tự lưu vào CRM']], human: 'Nhân viên nhận lại mọi cuộc hội thoại khó và có thể chen vào trả lời bất cứ lúc nào.' },
    voice: { sz: 'Vừa & lớn', need: ['Kịch bản cuộc gọi mẫu', 'Tổng đài, đầu số (SIP)', 'Danh sách khách & quy tắc gọi'], kpi: ['Số cuộc gọi xử lý/ngày', 'Tỷ lệ gọi thành công', 'Tỷ lệ chuyển nhân viên'], tech: ['Speech-to-Text tiếng Việt', 'Text-to-Speech', 'LLM', 'Tổng đài SIP', 'CRM'], ba: [['Năng lực gọi', 'Vài trăm cuộc/ngày cho cả đội', 'Hàng nghìn cuộc/ngày'], ['Ghi chép cuộc gọi', 'Ghi tay, thiếu sót', 'Tóm tắt tự động 100%']], human: 'Nhân viên tiếp nhận ngay khi khách cần, nghe lại và chấm điểm cuộc gọi của AI.' },
    salesagent: { sz: 'Mọi quy mô', need: ['Danh mục sản phẩm & điểm khác biệt', 'Kịch bản tư vấn của sales giỏi nhất', 'Bộ câu xử lý từ chối'], kpi: ['Tỷ lệ chuyển đổi tin nhắn → đơn', 'Giá trị đơn trung bình', 'Thời gian từ lead đến chốt'], tech: ['Zalo OA', 'Messenger', 'Website', 'LLM', 'CRM'], ba: [['Chất lượng tư vấn', 'Phụ thuộc từng người', 'Đồng đều theo kịch bản chuẩn'], ['Lead nóng', 'Lẫn trong hàng trăm tin nhắn', 'Được lọc và chuyển ngay cho sales']], human: 'Sales chốt các khách giá trị cao; AI không tự đưa cam kết ngoài chính sách.' },
    avatar: { sz: 'Mọi quy mô', need: ['Kịch bản hoặc tài liệu nguồn', 'Ảnh/video mẫu nếu muốn avatar giống người thật (có đồng ý)', 'Bộ nhận diện thương hiệu'], kpi: ['Số video/tháng', 'Thời gian ra 1 video', 'Tỷ lệ xem hết video'], tech: ['Digital human', 'Voice cloning', 'LLM biên tập', 'Dịch đa ngôn ngữ'], ba: [['Làm 1 video', 'Vài ngày quay dựng', 'Vài phút'], ['Đa ngôn ngữ', 'Thuê người đọc từng thứ tiếng', 'Một kịch bản, nhiều ngôn ngữ']], human: 'Mọi video được duyệt trước khi phát hành; chỉ dùng hình ảnh, giọng nói khi có sự đồng ý.' },
    journey: { sz: 'Mọi quy mô', need: ['Dữ liệu khách & lịch sử mua', 'Tài khoản Zalo OA/ZNS, email', 'Các mốc chăm sóc mong muốn'], kpi: ['Tỷ lệ mở tin', 'Tỷ lệ mua lại', 'Số khách cũ quay lại'], tech: ['Zalo ZNS', 'Email', 'SMS', 'CDP', 'LLM'], ba: [['Chăm sóc sau bán', 'Khi nhớ ra', 'Tự động theo hành trình'], ['Nội dung tin nhắn', 'Một mẫu cho tất cả', 'Riêng cho từng khách']], human: 'Đội marketing duyệt kịch bản và giới hạn tần suất gửi để không làm phiền khách.' },
    translate: { sz: 'Mọi quy mô', need: ['Danh sách ngôn ngữ cần hỗ trợ', 'Bảng thuật ngữ ngành', 'Kênh giao tiếp: chat, họp, điện thoại'], kpi: ['Độ chính xác bản dịch', 'Thời gian phản hồi', 'Số hội thoại đa ngôn ngữ'], tech: ['LLM đa ngôn ngữ', 'Speech-to-Text', 'Text-to-Speech', 'Bảng thuật ngữ'], ba: [['Khách nước ngoài nhắn tin', 'Chờ người biết tiếng', 'Trả lời ngay'], ['Họp với đối tác', 'Thuê phiên dịch', 'Phụ đề dịch trực tiếp']], human: 'Nội dung quan trọng như hợp đồng được người có chuyên môn kiểm tra lại.' },
    workflow: { sz: 'Mọi quy mô', need: ['Danh sách phần mềm đang dùng', 'Mô tả quy trình hiện tại', 'Tài khoản/API của các phần mềm'], kpi: ['Số thao tác thủ công loại bỏ', 'Số lần chạy/tháng', 'Tỷ lệ lỗi'], tech: ['n8n', 'Make', 'Zapier', 'Google Workspace', 'Zalo/Email', 'API'], ba: [['Chuyển thông tin giữa phần mềm', 'Copy–dán bằng tay', 'Tự động trong vài giây'], ['Nhắc việc', 'Nhớ thì làm', 'Tự nhắc đúng người, đúng lúc']], human: 'Các bước phê duyệt vẫn do người quyết định; mọi lần chạy đều có nhật ký.' },
    rpa: { sz: 'Vừa & lớn', need: ['Quy trình thao tác chi tiết từng bước', 'Tài khoản phần mềm cho robot', 'Bộ dữ liệu mẫu để kiểm thử'], kpi: ['Số giao dịch robot xử lý', 'Tỷ lệ chạy thành công', 'Số giờ công được giải phóng'], tech: ['UiPath', 'Power Automate', 'Python', 'Playwright'], ba: [['Nhập 500 hóa đơn', '2–3 ngày công', 'Vài giờ, chạy ban đêm'], ['Sai sót gõ phím', 'Khó tránh khi làm nhiều', 'Gần như không có']], human: 'Robot dừng ở trường hợp ngoại lệ và chờ người xử lý.' },
    idp: { sz: 'Vừa & lớn', need: ['50–100 mẫu chứng từ thường gặp', 'Danh sách trường dữ liệu cần lấy', 'Quy tắc kiểm tra hợp lệ'], kpi: ['Độ chính xác trích xuất', 'Số chứng từ/ngày', 'Thời gian xử lý/chứng từ'], tech: ['OCR tiếng Việt', 'Vision LLM', 'ERP/MISA', 'Google Drive'], ba: [['Nhập 1 hóa đơn', '3–5 phút', 'Vài giây'], ['Phát hiện sai lệch', 'Khi đối soát cuối tháng', 'Ngay khi nhận chứng từ']], human: 'Chứng từ có độ tin cậy thấp được đưa vào hàng chờ để người duyệt.' },
    inbox: { sz: 'Mọi quy mô', need: ['Quyền truy cập hộp thư chung', 'Danh mục loại yêu cầu & người phụ trách', 'Mẫu trả lời chuẩn'], kpi: ['Thời gian phản hồi đầu tiên', 'Tỷ lệ xử lý đúng hạn', 'Số email tồn đọng'], tech: ['Gmail/Outlook', 'Helpdesk', 'LLM', 'Workflow'], ba: [['Phân loại email', 'Đọc từng thư', 'Tự gắn nhãn, chia việc'], ['Soạn trả lời', 'Viết từ đầu', 'Có sẵn bản nháp']], human: 'AI chỉ soạn nháp; nhân viên đọc lại và bấm gửi.' },
    agent: { sz: 'Vừa & lớn', need: ['Mục tiêu & tiêu chí "xong việc" rõ ràng', 'Quyền truy cập công cụ, dữ liệu cần thiết', 'Danh sách hành động cần người duyệt'], kpi: ['Số nhiệm vụ hoàn thành', 'Tỷ lệ cần người can thiệp', 'Thời gian hoàn thành'], tech: ['LLM có tool-use', 'API nội bộ', 'MCP', 'Tìm kiếm web', 'Nhật ký kiểm toán'], ba: [['Báo cáo đối thủ hằng tuần', '1 ngày công', 'Có sẵn mỗi sáng thứ Hai'], ['Việc nhiều bước', 'Người làm từng bước', 'Agent làm, người duyệt kết quả']], human: 'Agent hỏi ý kiến trước mọi hành động có rủi ro: thanh toán, gửi khách, xóa dữ liệu.' },
    multiagent: { sz: 'Doanh nghiệp lớn', need: ['Quy trình liên phòng ban được mô tả', 'Agent đơn lẻ đã chạy ổn định', 'Tiêu chí chất lượng đầu ra'], kpi: ['Thời gian hoàn thành dự án', 'Tỷ lệ đạt ở lần duyệt đầu', 'Số vòng chỉnh sửa'], tech: ['Điều phối agent', 'Nhiều mô hình LLM', 'MCP', 'Hàng đợi tác vụ'], ba: [['Hồ sơ dự thầu', '1–2 tuần, nhiều phòng ban', 'Bản nháp đầy đủ trong vài giờ'], ['Kiểm soát chất lượng', 'Phụ thuộc người soát', 'Agent kiểm duyệt chéo + người duyệt cuối']], human: 'Người phụ trách duyệt kết quả cuối và có thể dừng bất kỳ agent nào.' },
    computeruse: { sz: 'Vừa & lớn', need: ['Danh sách hệ thống, cổng web cần thao tác', 'Tài khoản riêng cho agent', 'Ví dụ kết quả mong muốn'], kpi: ['Tỷ lệ hoàn thành', 'Thời gian mỗi lượt', 'Số lần cần hỗ trợ'], tech: ['Computer-use agent', 'Trình duyệt tự động', 'Máy ảo cô lập'], ba: [['Lấy dữ liệu từ 3 cổng web', 'Đăng nhập, tải tay từng nơi', 'Agent tự làm theo lịch'], ['Khi giao diện thay đổi', 'Robot cũ bị kẹt', 'Agent tự nhận biết và thích nghi']], human: 'Agent chạy trong máy ảo riêng, quyền hạn giới hạn, mọi thao tác được ghi lại.' },
    copilot: { sz: 'Mọi quy mô', need: ['Danh sách vị trí ưu tiên', 'Quy trình, mẫu biểu từng vị trí', 'Quy định dữ liệu được phép dùng'], kpi: ['Số người dùng hằng tuần', 'Số giờ tiết kiệm/người', 'Mức hài lòng nhân viên'], tech: ['ChatGPT Enterprise', 'Claude', 'Gemini', 'Microsoft Copilot', 'Zalo/Teams'], ba: [['Soạn văn bản theo mẫu', '30 phút', '3 phút'], ['Nhân viên mới', 'Hỏi người cũ liên tục', 'Hỏi trợ lý, có câu trả lời ngay']], human: 'Nhân viên chịu trách nhiệm kiểm tra kết quả; dữ liệu nhạy cảm bị chặn tự động.' },
    integration: { sz: 'Vừa & lớn', need: ['Tài liệu API của phần mềm (nếu có)', 'Danh sách chức năng AI cần dùng', 'Đầu mối IT hoặc nhà cung cấp phần mềm'], kpi: ['Số hệ thống đã kết nối', 'Tỷ lệ truy cập thành công', 'Số yêu cầu bị chặn vì sai quyền'], tech: ['REST API', 'MCP server', 'Webhook', 'OAuth/SSO', 'Nhật ký truy cập'], ba: [['AI trả lời về tồn kho', 'Theo tài liệu cũ', 'Theo số liệu thực tế'], ['Mỗi ứng dụng AI mới', 'Tích hợp lại từ đầu', 'Dùng lại kết nối có sẵn']], human: 'IT quyết định AI được truy cập gì; quyền có thể thu hồi bất cứ lúc nào.' },
    rag: { sz: 'Mọi quy mô', need: ['Tài liệu nội bộ: quy trình, chính sách, hướng dẫn', 'Phân quyền ai được xem tài liệu nào', 'Người phụ trách cập nhật tài liệu'], kpi: ['Tỷ lệ câu trả lời đúng', 'Số câu hỏi/tháng', 'Thời gian onboarding'], tech: ['Vector database', 'Embedding', 'LLM', 'Google Drive/SharePoint', 'Zalo/Web'], ba: [['Tìm 1 quy định', 'Lục thư mục, hỏi người', 'Hỏi và có câu trả lời kèm nguồn'], ['Khi người cũ nghỉ việc', 'Kiến thức mất theo', 'Kiến thức ở lại trong hệ thống']], human: 'Câu trả lời luôn kèm nguồn để người dùng tự kiểm chứng.' },
    bi: { sz: 'Vừa & lớn', need: ['Quyền truy cập nguồn dữ liệu', 'Danh sách chỉ số quan trọng (KPI)', 'Định nghĩa thống nhất cho từng chỉ số'], kpi: ['Thời gian làm báo cáo', 'Số câu hỏi dữ liệu/tuần', 'Độ chính xác truy vấn'], tech: ['Data warehouse', 'Text-to-SQL', 'Looker Studio', 'Power BI', 'LLM'], ba: [['Báo cáo tuần', '1–2 ngày tổng hợp', 'Tự gửi 8h sáng thứ Hai'], ['Câu hỏi bất chợt của sếp', 'Chờ nhân viên làm', 'Có câu trả lời trong 1 phút']], human: 'Chỉ số quan trọng có định nghĩa được duyệt; AI hiển thị cả câu truy vấn để đối chiếu.' },
    predict: { sz: 'Vừa & lớn', need: ['1–2 năm dữ liệu bán hàng/vận hành', 'Lịch khuyến mãi, sự kiện', 'Mục tiêu dự báo cụ thể'], kpi: ['Sai số dự báo', 'Tỷ lệ hết hàng', 'Vòng quay tồn kho'], tech: ['Machine Learning', 'Dự báo chuỗi thời gian', 'Python', 'Data warehouse', 'Dashboard'], ba: [['Lên kế hoạch nhập hàng', 'Dựa vào kinh nghiệm', 'Dựa trên dự báo có số liệu'], ['Khách sắp rời bỏ', 'Biết khi đã mất', 'Cảnh báo trước để giữ chân']], human: 'Người quản lý quyết định cuối cùng; AI đưa con số và lý do.' },
    personalize: { sz: 'Vừa & lớn', need: ['Dữ liệu mua hàng & hành vi', 'Danh mục sản phẩm có thuộc tính', 'Kênh tiếp cận khách: web, app, ZNS'], kpi: ['Tỷ lệ bấm vào gợi ý', 'Giá trị đơn trung bình', 'Tỷ lệ mua lại'], tech: ['Hệ gợi ý', 'CDP', 'Zalo ZNS', 'Email', 'A/B testing'], ba: [['Thông điệp gửi khách', 'Giống nhau cho tất cả', 'Riêng cho từng người'], ['Gợi ý sản phẩm', 'Hàng bán chạy chung', 'Theo sở thích từng khách']], human: 'Đội marketing đặt luật: tần suất gửi, sản phẩm ưu tiên, đối tượng loại trừ.' },
    dataplatform: { sz: 'Vừa & lớn', need: ['Danh sách nguồn dữ liệu', 'Quyền truy cập các hệ thống', 'Người nắm nghiệp vụ để định nghĩa chỉ số'], kpi: ['Số nguồn dữ liệu đã kết nối', 'Tỷ lệ dữ liệu sạch', 'Độ trễ cập nhật'], tech: ['Data warehouse', 'ETL/ELT', 'BigQuery', 'PostgreSQL', 'dbt'], ba: [['Số liệu giữa các phòng', 'Mỗi nơi một con số', 'Một con số thống nhất'], ['Chuẩn bị dữ liệu cho dự án AI', 'Làm lại mỗi lần', 'Có sẵn, cập nhật tự động']], human: 'Mỗi nhóm dữ liệu có người chịu trách nhiệm về chất lượng.' },
    meeting: { sz: 'Mọi quy mô', need: ['Nguồn ghi âm: Zoom, Meet, tổng đài', 'Mẫu biên bản mong muốn', 'Tiêu chí chấm điểm cuộc gọi'], kpi: ['Thời gian ra biên bản', 'Tỷ lệ cuộc gọi được chấm', 'Điểm chất lượng trung bình'], tech: ['Speech-to-Text tiếng Việt', 'LLM', 'Zoom/Meet', 'Tổng đài', 'CRM'], ba: [['Biên bản họp', 'Viết tay sau 1–2 ngày', 'Có ngay sau cuộc họp'], ['Kiểm tra chất lượng cuộc gọi', 'Nghe ngẫu nhiên vài cuộc', 'Phân tích 100% cuộc gọi']], human: 'Người dự họp xác nhận biên bản; chỉ ghi âm khi đã thông báo.' },
    content: { sz: 'Mọi quy mô', need: ['Bộ nhận diện & giọng thương hiệu', 'Bài viết mẫu tốt nhất', 'Lịch chiến dịch'], kpi: ['Số bài/tháng', 'Thời gian sản xuất 1 bài', 'Tương tác trung bình'], tech: ['LLM', 'Google Sheets', 'Canva', 'Meta Business Suite', 'Workflow'], ba: [['Viết 1 bài chất lượng', '2–3 giờ', '20–30 phút gồm cả duyệt'], ['Lịch đăng', 'Lúc có lúc không', 'Đều đặn theo kế hoạch']], human: 'Mọi bài viết đều qua người duyệt trước khi đăng.' },
    creative: { sz: 'Mọi quy mô', need: ['Ảnh sản phẩm gốc', 'Bộ nhận diện thương hiệu', 'Quy định quảng cáo của ngành'], kpi: ['Số ấn phẩm/tháng', 'Thời gian ra 1 ấn phẩm', 'Hiệu quả theo từng mẫu'], tech: ['Tạo ảnh AI', 'Video AI', 'Canva AI', 'CapCut', 'Giọng đọc AI'], ba: [['Ảnh studio cho 1 sản phẩm', 'Thuê chụp, chờ vài ngày', 'Vài phút từ ảnh điện thoại'], ['Mẫu quảng cáo để thử', '2–3 mẫu', 'Hàng chục mẫu']], human: 'Thiết kế viên duyệt cuối, đảm bảo đúng thương hiệu và bản quyền.' },
    listening: { sz: 'Vừa & lớn', need: ['Danh sách thương hiệu, sản phẩm, đối thủ', 'Các kênh cần theo dõi', 'Người nhận cảnh báo'], kpi: ['Tỷ lệ đánh giá tích cực', 'Thời gian phát hiện vấn đề', 'Số chủ đề nổi bật'], tech: ['Thu thập dữ liệu mạng xã hội', 'Phân tích cảm xúc', 'LLM', 'Dashboard'], ba: [['Biết khách phàn nàn', 'Khi đã lan rộng', 'Ngay khi bắt đầu'], ['Đọc đánh giá', 'Thủ công vài chục cái', 'Tổng hợp hàng nghìn tự động']], human: 'Đội truyền thông quyết định cách phản hồi; AI chỉ phát hiện và đề xuất.' },
    seo: { sz: 'Mọi quy mô', need: ['Website & quyền quản trị', 'Chuyên môn, dữ liệu riêng để viết', 'Danh sách sản phẩm trọng tâm'], kpi: ['Lượt truy cập tự nhiên', 'Số từ khóa top 10', 'Tần suất được AI trích dẫn'], tech: ['Google Search Console', 'Schema markup', 'LLM', 'Theo dõi AI search'], ba: [['Khách tìm thấy bạn', 'Chủ yếu nhờ quảng cáo', 'Tự tìm đến qua tìm kiếm'], ['Khi khách hỏi chatbot AI', 'Không nhắc tới bạn', 'Được gợi ý kèm nguồn']], human: 'Chuyên gia nội dung đảm bảo thông tin chính xác, không spam.' },
    ads: { sz: 'Mọi quy mô', need: ['Quyền xem tài khoản quảng cáo', 'Dữ liệu đơn hàng, lead thực tế', 'Mục tiêu chiến dịch'], kpi: ['Tỷ lệ chuyển đổi', 'Số mẫu được thử/tuần', 'Tỷ lệ lead chất lượng'], tech: ['Meta Ads', 'Google Ads', 'TikTok Ads', 'LLM', 'Dashboard'], ba: [['Đọc số liệu quảng cáo', 'Cuối ngày, thủ công', 'Liên tục, có cảnh báo'], ['Mẫu quảng cáo mới', 'Vài mẫu mỗi tháng', 'Hàng chục mẫu mỗi tuần']], human: 'Người phụ trách duyệt mọi thay đổi lớn trên tài khoản quảng cáo trước khi áp dụng.' },
    hr: { sz: 'Vừa & lớn', need: ['Mô tả vị trí & tiêu chí tuyển', 'Sổ tay nhân viên, chính sách', 'Phần mềm HR, email tuyển dụng'], kpi: ['Thời gian tuyển 1 vị trí', 'Số CV xử lý/ngày', 'Số câu hỏi HR tự động trả lời'], tech: ['LLM', 'RAG chính sách', 'Workflow', 'Phần mềm HR', 'Zalo'], ba: [['Lọc 300 CV', '2–3 ngày', 'Vài giờ, có shortlist'], ['Câu hỏi về nghỉ phép', 'Hỏi HR, chờ trả lời', 'Trợ lý trả lời ngay']], human: 'HR quyết định tuyển ai; tiêu chí lọc minh bạch, không phân biệt đối xử.' },
    finance: { sz: 'Vừa & lớn', need: ['Phần mềm kế toán (MISA, Fast, ERP…)', 'Mẫu chứng từ & quy trình đối soát', 'Quyền truy cập sao kê'], kpi: ['Thời gian khóa sổ', 'Số chứng từ xử lý tự động', 'Số ngày thu hồi công nợ'], tech: ['OCR/IDP', 'RPA', 'MISA/ERP', 'Hóa đơn điện tử', 'Dashboard'], ba: [['Đối soát ngân hàng', 'Làm tay cuối tháng', 'Tự động mỗi ngày'], ['Nhắc công nợ', 'Khi nhớ ra', 'Theo lịch, cá nhân hóa']], human: 'Kế toán trưởng duyệt bút toán điều chỉnh và các khoản chênh lệch.' },
    legal: { sz: 'Vừa & lớn', need: ['Bộ hợp đồng mẫu chuẩn', 'Danh sách điều khoản cần kiểm tra', 'Quy trình phê duyệt hợp đồng'], kpi: ['Thời gian rà soát 1 hợp đồng', 'Số rủi ro phát hiện', 'Số hợp đồng/tháng'], tech: ['LLM', 'RAG văn bản pháp luật', 'So sánh văn bản', 'Quản lý hợp đồng'], ba: [['Rà soát 1 hợp đồng', 'Vài giờ', 'Vài phút + thời gian duyệt'], ['So sánh phiên bản', 'Đọc đối chiếu từng dòng', 'Tự đánh dấu thay đổi']], human: 'AI chỉ hỗ trợ; ý kiến pháp lý cuối cùng do luật sư hoặc pháp chế đưa ra.' },
    supply: { sz: 'Vừa & lớn', need: ['Dữ liệu tồn kho & bán hàng', 'Danh sách nhà cung cấp, thời gian giao', 'Quy tắc tồn kho tối thiểu'], kpi: ['Tỷ lệ hết hàng', 'Số ngày tồn kho', 'Tỷ lệ giao đúng hạn'], tech: ['Dự báo ML', 'ERP/WMS', 'Workflow', 'Dashboard', 'Agent'], ba: [['Đặt hàng', 'Theo kinh nghiệm', 'Theo dự báo có số liệu'], ['Nhà cung cấp giao chậm', 'Biết khi đã thiếu hàng', 'Cảnh báo sớm']], human: 'Bộ phận mua hàng duyệt mọi đơn đặt hàng trước khi gửi.' },
    vision: { sz: 'Vừa & lớn', need: ['Vị trí camera & điều kiện ánh sáng', 'Ảnh mẫu lỗi/đối tượng cần nhận diện', 'Quy tắc cảnh báo'], kpi: ['Độ chính xác phát hiện', 'Tỷ lệ báo nhầm', 'Thời gian phản ứng'], tech: ['Camera IP', 'Computer Vision', 'Edge AI', 'Dashboard', 'Cảnh báo Zalo'], ba: [['Kiểm tra chất lượng', 'Lấy mẫu ngẫu nhiên', 'Kiểm tra 100% sản phẩm'], ['Phát hiện vi phạm an toàn', 'Khi đã có sự cố', 'Ngay lập tức']], human: 'Người phụ trách xác nhận cảnh báo; hình ảnh được bảo vệ theo quy định.' },
    face: { sz: 'Vừa & lớn', need: ['Danh sách người & sự đồng ý xử lý dữ liệu', 'Vị trí lắp camera, cửa', 'Phần mềm chấm công/nhân sự'], kpi: ['Độ chính xác nhận diện', 'Thời gian nhận diện', 'Số cảnh báo người lạ'], tech: ['Camera AI', 'Nhận diện khuôn mặt', 'Kiểm soát cửa', 'Phần mềm HR'], ba: [['Chấm công', 'Quẹt thẻ, có thể chấm hộ', 'Nhận diện khuôn mặt, chính xác'], ['Người lạ vào khu vực cấm', 'Phát hiện muộn', 'Cảnh báo ngay']], human: 'Dữ liệu sinh trắc học được bảo vệ theo Nghị định 13/2023 và chỉ dùng khi có đồng ý.' },
    robotics: { sz: 'Doanh nghiệp lớn', need: ['Sơ đồ mặt bằng', 'Mô tả công việc lặp lại', 'Hạ tầng mạng, điểm sạc'], kpi: ['Số chuyến/ca', 'Thời gian hoạt động', 'Số sự cố'], tech: ['Robot phục vụ', 'AMR', 'Cánh tay robot', 'Lidar', 'WMS/POS'], ba: [['Chạy món giờ cao điểm', 'Thiếu người', 'Robot chạy liên tục'], ['Chở hàng trong kho', 'Đi bộ nhiều km mỗi ca', 'Robot tự chở tới vị trí']], human: 'Nhân viên giám sát, xử lý tình huống và làm phần việc cần sự khéo léo.' },
    iot: { sz: 'Doanh nghiệp lớn', need: ['Danh sách máy móc quan trọng', 'Lịch sử hỏng hóc', 'Hạ tầng mạng tại xưởng'], kpi: ['Số lần dừng máy đột xuất', 'Thời gian sửa chữa', 'Tuổi thọ thiết bị'], tech: ['Cảm biến IoT', 'Gateway', 'Phát hiện bất thường', 'CMMS', 'Dashboard'], ba: [['Bảo trì', 'Định kỳ hoặc khi đã hỏng', 'Đúng lúc máy có dấu hiệu'], ['Dừng dây chuyền', 'Bất ngờ', 'Được báo trước nhiều ngày']], human: 'Kỹ thuật viên kiểm tra thực tế trước khi thay linh kiện.' },
    llmapi: { sz: 'Mọi quy mô', need: ['Tài khoản doanh nghiệp của nhà cung cấp AI', 'Quy định dữ liệu được gửi đi', 'Ứng dụng cần dùng AI'], kpi: ['Tốc độ phản hồi', 'Mức sử dụng theo phòng ban', 'Tỷ lệ lỗi'], tech: ['OpenAI', 'Anthropic Claude', 'Google Gemini', 'Azure OpenAI', 'AWS Bedrock'], ba: [['Thời gian bắt đầu', 'Vài tháng dựng hạ tầng', 'Vài ngày'], ['Chất lượng mô hình', 'Tự huấn luyện, khó theo kịp', 'Dùng ngay mô hình mạnh nhất']], human: 'Dữ liệu nhạy cảm được che trước khi gửi; quản trị viên kiểm soát ai được dùng.' },
    llmprivate: { sz: 'Vừa & lớn', need: ['Tài khoản cloud doanh nghiệp', 'Yêu cầu bảo mật, vị trí lưu dữ liệu', 'Số người dùng dự kiến'], kpi: ['Thời gian hoạt động', 'Tốc độ phản hồi', 'Số người dùng đồng thời'], tech: ['VPC', 'GPU cloud', 'vLLM', 'Llama / Qwen', 'VPN riêng'], ba: [['Dữ liệu', 'Đi qua hạ tầng dùng chung', 'Nằm trong vùng riêng'], ['Mở rộng', 'Phụ thuộc gói dịch vụ', 'Tăng GPU khi cần']], human: 'Bộ phận IT nắm toàn quyền truy cập vùng cloud và nhật ký.' },
    llmonprem: { sz: 'Doanh nghiệp lớn', need: ['Phòng server: điện, làm mát, mạng', 'Số người dùng & tác vụ chính', 'Đội IT phối hợp vận hành'], kpi: ['Thời gian hoạt động', 'Tốc độ phản hồi', 'Mức sử dụng GPU'], tech: ['Máy chủ GPU', 'vLLM / Ollama', 'Llama / Qwen', 'Kubernetes', 'LDAP/AD'], ba: [['Dữ liệu ra khỏi công ty', 'Có', 'Không bao giờ'], ['Khi mất internet', 'AI ngừng hoạt động', 'Vẫn hoạt động']], human: 'Toàn bộ hệ thống nằm trong quyền kiểm soát của doanh nghiệp.' },
    finetune: { sz: 'Vừa & lớn', need: ['1.000+ ví dụ chất lượng', 'Chuyên gia nghiệp vụ để đánh giá', 'Bộ câu hỏi kiểm tra'], kpi: ['Độ chính xác trên bộ kiểm tra', 'Tốc độ phản hồi', 'Tỷ lệ đúng văn phong'], tech: ['LoRA / QLoRA', 'GPU', 'Mô hình mã nguồn mở', 'Bộ đánh giá tự động'], ba: [['Thuật ngữ chuyên ngành', 'Hay dùng sai', 'Dùng đúng, nhất quán'], ['Kích thước mô hình', 'Cần mô hình rất lớn', 'Mô hình nhỏ hơn vẫn đạt chất lượng']], human: 'Chuyên gia nghiệp vụ duyệt dữ liệu và chấm điểm mô hình trước khi dùng.' },
    gateway: { sz: 'Vừa & lớn', need: ['Danh sách ứng dụng AI đang dùng', 'Quy tắc phân quyền', 'Danh sách dữ liệu cần che'], kpi: ['Số yêu cầu bị chặn', 'Mức sử dụng theo phòng ban', 'Thời gian phản hồi'], tech: ['LiteLLM', 'API Gateway', 'Che dữ liệu cá nhân', 'Giám sát', 'SSO'], ba: [['Kiểm soát AI', 'Mỗi ứng dụng một kiểu', 'Một cổng tập trung'], ['Khi nhà cung cấp gặp lỗi', 'Ứng dụng ngừng', 'Tự chuyển mô hình dự phòng']], human: 'Quản trị viên đặt chính sách và xem nhật ký kiểm toán bất cứ lúc nào.' },
    edge: { sz: 'Vừa & lớn', need: ['Bài toán & yêu cầu tốc độ', 'Vị trí lắp đặt thiết bị', 'Dữ liệu mẫu để huấn luyện'], kpi: ['Độ trễ xử lý', 'Độ chính xác', 'Thời gian hoạt động thiết bị'], tech: ['NVIDIA Jetson', 'Mô hình nén', 'Camera AI', 'Quản lý thiết bị từ xa'], ba: [['Thời gian phản hồi', 'Phụ thuộc đường mạng', 'Gần như tức thì'], ['Khi mất internet', 'Ngừng hoạt động', 'Vẫn chạy bình thường']], human: 'Kết quả quan trọng được gửi về trung tâm để người phụ trách giám sát.' },
    strategy: { sz: 'Mọi quy mô', need: ['Thời gian của ban lãnh đạo (2–3 buổi)', 'Đầu mối từng phòng ban', 'Mục tiêu kinh doanh 1–3 năm'], kpi: ['Số use-case được duyệt', 'Tỷ lệ use-case đạt KPI', 'Bậc trưởng thành AI'], tech: ['Đánh giá mức sẵn sàng AI', 'Ma trận ưu tiên', 'Lộ trình 30–60–90'], ba: [['Triển khai AI', 'Thử nghiệm rời rạc', 'Theo lộ trình có KPI'], ['Đồng thuận nội bộ', 'Mỗi phòng một ý', 'Cùng một kế hoạch']], human: 'Ban lãnh đạo quyết định ưu tiên; Drabuff AI cung cấp phân tích và phương án.' },
    governance: { sz: 'Mọi quy mô', need: ['Danh sách công cụ AI đang dùng', 'Danh mục dữ liệu cá nhân đang xử lý', 'Đầu mối pháp chế/IT'], kpi: ['Tỷ lệ nhân viên được tập huấn', 'Số sự cố dữ liệu', 'Mức tuân thủ quy chế'], tech: ['Nghị định 13/2023', 'Phân loại dữ liệu', 'Chống rò rỉ dữ liệu', 'Nhật ký kiểm toán'], ba: [['Dùng AI', 'Tự phát, khó kiểm soát', 'Có quy chế, có phân quyền'], ['Dữ liệu khách hàng', 'Có thể bị dán vào AI công cộng', 'Được che hoặc chặn tự động']], human: 'Đầu mối AI của công ty phê duyệt công cụ và trường hợp sử dụng mới.' },
    eval: { sz: 'Mọi quy mô', need: ['Câu hỏi thật từ khách hàng', 'Đáp án chuẩn do chuyên gia duyệt', 'Danh sách điều AI không được làm'], kpi: ['Tỷ lệ trả lời đúng', 'Số lỗ hổng phát hiện', 'Điểm an toàn'], tech: ['Bộ đánh giá tự động', 'LLM chấm điểm', 'Red-teaming', 'Báo cáo chất lượng'], ba: [['Ra mắt AI', 'Dựa vào cảm giác "có vẻ ổn"', 'Dựa trên điểm kiểm tra rõ ràng'], ['Lỗi của AI', 'Khách phát hiện trước', 'Phát hiện trong phòng thử nghiệm']], human: 'Chuyên gia nghiệp vụ duyệt đáp án chuẩn và quyết định ngưỡng đạt.' },
    training: { sz: 'Mọi quy mô', need: ['Danh sách học viên & vị trí', 'Bài toán thực tế của từng phòng', 'Thời gian học phù hợp'], kpi: ['Điểm kiểm tra đầu vào – đầu ra', 'Số sản phẩm AI tạo ra sau khóa', 'Số giờ tiết kiệm/tuần'], tech: ['ChatGPT', 'Claude', 'Gemini', 'NotebookLM', 'Make / n8n'], ba: [['Nhân viên dùng AI', 'Tự mày mò, kết quả chung chung', 'Thành thạo, có quy trình chuẩn'], ['Sau khóa học', 'Quên dần', 'Đồng hành 30 ngày để áp dụng']], human: 'Quản lý theo dõi việc áp dụng; Drabuff AI hỗ trợ sau khóa.' },
    managed: { sz: 'Mọi quy mô', need: ['Quyền giám sát hệ thống', 'Đầu mối tiếp nhận báo cáo', 'Kênh báo sự cố'], kpi: ['Thời gian hoạt động', 'Thời gian xử lý sự cố', 'Điểm chất lượng câu trả lời'], tech: ['Giám sát 24/7', 'Đánh giá tự động', 'Cập nhật mô hình', 'Báo cáo tháng'], ba: [['Sau triển khai', 'Tự xoay xở khi lỗi', 'Có đội chăm sóc'], ['Chất lượng AI', 'Giảm dần theo thời gian', 'Được đo và cải thiện hằng tháng']], human: 'Doanh nghiệp nhận báo cáo hằng tháng và quyết định các thay đổi lớn.' }
  };
  SV.forEach(function (s) { var x = X[s.id] || {}; for (var k in x) s[k] = x[k]; });

  window.LAYERS = [
    { n: 'Điểm chạm', d: 'Nơi khách hàng và nhân viên gặp AI', ids: ['chatbot', 'voice', 'salesagent', 'translate', 'avatar', 'copilot'] },
    { n: 'Ứng dụng & tự động hóa', d: 'Các dây chuyền làm việc thay con người, theo từng phòng ban', ids: ['workflow', 'rpa', 'idp', 'inbox', 'journey', 'content', 'creative', 'seo', 'ads', 'listening', 'hr', 'finance', 'legal', 'supply'] },
    { n: 'Agent · bộ não hành động', d: 'AI tự lên kế hoạch, dùng công cụ và điều phối công việc', ids: ['agent', 'multiagent', 'computeruse', 'integration'] },
    { n: 'Tri thức & dữ liệu', d: 'Thứ AI cần biết để trả lời đúng về công ty bạn', ids: ['rag', 'meeting', 'bi', 'predict', 'personalize', 'dataplatform'] },
    { n: 'Thế giới thật', d: 'Camera, cảm biến, robot đưa AI ra khỏi màn hình', ids: ['vision', 'face', 'robotics', 'iot'] },
    { n: 'Nền tảng mô hình AI', d: 'Nơi đặt "bộ não": cloud công cộng, cloud riêng, on-premise, thiết bị', ids: ['llmapi', 'llmprivate', 'llmonprem', 'finetune', 'gateway', 'edge'] }
  ];

  window.PAINS = [
    { t: 'Khách nhắn nhiều, trả lời không kịp', ids: ['chatbot', 'salesagent', 'journey', 'inbox'] },
    { t: 'Tổng đài quá tải cuộc gọi', ids: ['voice', 'meeting', 'chatbot'] },
    { t: 'Lead nhiều nhưng chốt ít', ids: ['salesagent', 'journey', 'personalize', 'ads', 'meeting'] },
    { t: 'Nhân viên mất nhiều giờ nhập liệu', ids: ['rpa', 'idp', 'workflow', 'computeruse', 'finance'] },
    { t: 'Hóa đơn, hợp đồng xử lý thủ công', ids: ['idp', 'finance', 'legal', 'rpa'] },
    { t: 'Báo cáo chậm, số liệu rời rạc', ids: ['bi', 'dataplatform', 'agent', 'integration'] },
    { t: 'Không dự đoán được nhu cầu, tồn kho', ids: ['predict', 'supply', 'dataplatform'] },
    { t: 'Nội dung marketing không đều', ids: ['content', 'creative', 'seo', 'avatar'] },
    { t: 'Quảng cáo kém hiệu quả', ids: ['ads', 'listening', 'personalize', 'seo'] },
    { t: 'Kiến thức nằm trong đầu vài người', ids: ['rag', 'copilot', 'meeting', 'hr'] },
    { t: 'Tuyển dụng, đào tạo mất thời gian', ids: ['hr', 'training', 'avatar', 'rag'] },
    { t: 'Lo ngại lộ dữ liệu khi dùng AI', ids: ['llmonprem', 'llmprivate', 'governance', 'gateway', 'eval'] },
    { t: 'Kiểm soát chất lượng, an toàn tại xưởng/kho', ids: ['vision', 'iot', 'face', 'edge', 'robotics'] },
    { t: 'Thiếu lao động cho việc chân tay lặp lại', ids: ['robotics', 'vision', 'rpa'] },
    { t: 'Phục vụ khách, đối tác nước ngoài', ids: ['translate', 'avatar', 'chatbot'] },
    { t: 'Chưa biết bắt đầu từ đâu', ids: ['strategy', 'training', 'copilot', 'governance'] }
  ];

  window.MATURITY = [
    { n: 'Thử nghiệm tự phát', d: 'Vài người tự dùng ChatGPT, chưa có quy chuẩn, dữ liệu có thể bị dán vào công cụ công cộng.', sign: ['Mỗi người dùng một kiểu', 'Chưa có quy chế dùng AI', 'Lãnh đạo chưa thấy kết quả rõ'], next: 'Đặt nền móng: quy chế, đào tạo, chọn việc làm trước.', ids: ['strategy', 'governance', 'training'] },
    { n: 'Chuẩn hóa & phổ cập', d: 'Có quy chế, đội ngũ được đào tạo, mỗi vị trí có trợ lý AI riêng.', sign: ['Nhân viên dùng AI hằng ngày', 'Có thư viện prompt chung', 'Dữ liệu nhạy cảm được kiểm soát'], next: 'Đưa AI vào dây chuyền công việc.', ids: ['copilot', 'training', 'llmapi', 'meeting'] },
    { n: 'Tự động hóa quy trình', d: 'AI chạy trong quy trình: trả lời khách, xử lý chứng từ, nối các phần mềm.', sign: ['Chatbot phục vụ khách 24/7', 'Ít thao tác copy–dán', 'Đo được giờ tiết kiệm'], next: 'Cho AI hiểu dữ liệu công ty và tự làm việc nhiều bước.', ids: ['chatbot', 'workflow', 'idp', 'rpa', 'content', 'journey'] },
    { n: 'Tri thức & Agent', d: 'AI hiểu dữ liệu riêng, trả lời có nguồn, agent làm trọn việc nhiều bước.', sign: ['Hỏi đáp tài liệu nội bộ', 'Báo cáo tự động', 'Agent xử lý việc định kỳ'], next: 'Mở rộng toàn doanh nghiệp, làm chủ hạ tầng.', ids: ['rag', 'bi', 'dataplatform', 'agent', 'integration', 'salesagent'] },
    { n: 'Doanh nghiệp AI-native', d: 'Đội agent phối hợp, mô hình riêng, dự báo và AI trong thế giới thật.', sign: ['AI tham gia ra quyết định', 'Hạ tầng AI riêng', 'AI trong sản xuất, kho, cửa hàng'], next: 'Liên tục đo lường, kiểm thử và tối ưu.', ids: ['multiagent', 'llmprivate', 'llmonprem', 'finetune', 'predict', 'eval'] }
  ];

  // a request travelling through the layers; d = direction of travel
  window.SCENARIOS = [
    { n: 'Khách nhắn Zalo lúc 23h', steps: [
      ['chatbot', 'down', 'Khách nhắn Zalo OA: "Liệu trình này có hợp với da dầu không em?"'],
      ['rag', 'down', 'Tra kho tri thức: thông tin liệu trình, chống chỉ định, chính sách.'],
      ['gateway', 'down', 'AI Gateway che số điện thoại khách trước khi gửi tới mô hình.'],
      ['llmapi', 'down', 'Mô hình ngôn ngữ soạn câu trả lời theo giọng thương hiệu.'],
      ['workflow', 'up', 'Workflow lưu khách vào CRM và hẹn sales gọi lúc 9h sáng.'],
      ['chatbot', 'up', 'Khách nhận câu tư vấn đầy đủ sau khoảng 6 giây.']] },
    { n: 'Kế toán nhận 300 hóa đơn cuối tháng', steps: [
      ['idp', 'down', 'AI đọc 300 hóa đơn PDF, lấy mã số thuế, ngày, số tiền.'],
      ['llmonprem', 'down', 'Dữ liệu tài chính được xử lý trên máy chủ nội bộ, không ra internet.'],
      ['finance', 'up', 'Đối soát với đơn mua và sao kê: phát hiện 4 hóa đơn lệch.'],
      ['rpa', 'up', 'Robot nhập 296 hóa đơn hợp lệ vào phần mềm kế toán.'],
      ['bi', 'down', 'Báo cáo tài chính tháng tự cập nhật.'],
      ['copilot', 'up', 'Kế toán trưởng nhận thông báo và duyệt 4 hóa đơn lệch.']] },
    { n: 'Giám đốc hỏi: "Vì sao doanh số tháng này giảm?"', steps: [
      ['copilot', 'down', 'Giám đốc hỏi trợ lý AI ngay trên Zalo.'],
      ['agent', 'down', 'Agent lập kế hoạch: lấy số theo chi nhánh, so cùng kỳ, tìm nguyên nhân.'],
      ['integration', 'down', 'Kết nối an toàn vào phần mềm bán hàng và CRM.'],
      ['dataplatform', 'down', 'Lấy số liệu đã làm sạch từ kho dữ liệu chung.'],
      ['bi', 'up', 'Phân tích (ví dụ): chi nhánh B giảm do thiếu 2 mã hàng chủ lực.'],
      ['llmprivate', 'down', 'Mô hình trên cloud riêng tổng hợp thành câu trả lời dễ hiểu.'],
      ['copilot', 'up', 'Giám đốc nhận câu trả lời kèm biểu đồ trong chưa đầy một phút.']] },
    { n: 'Camera phát hiện sản phẩm lỗi', steps: [
      ['vision', 'down', 'Camera chụp từng sản phẩm trên băng chuyền.'],
      ['edge', 'down', 'AI tại chỗ phát hiện vết nứt trong vài chục mili giây.'],
      ['workflow', 'up', 'Gửi lệnh loại sản phẩm và báo trưởng ca qua Zalo.'],
      ['iot', 'down', 'Đối chiếu cảm biến: máy ép số 3 đang rung bất thường.'],
      ['bi', 'up', 'Dashboard cập nhật tỷ lệ lỗi theo ca.'],
      ['copilot', 'up', 'Quản đốc nhận đề xuất lên lịch bảo trì máy số 3.']] }
  ];

  window.GLOSSARY = [
    ['AI tạo sinh', 'AI có thể tạo ra nội dung mới: văn bản, hình ảnh, giọng nói, video.', 'Như một người viết, vẽ, nói theo yêu cầu của bạn.'],
    ['LLM', 'Mô hình ngôn ngữ lớn, "bộ não" đứng sau ChatGPT, Claude, Gemini.', 'Như người đã đọc gần hết sách trên đời và biết diễn đạt lại.'],
    ['Prompt', 'Câu lệnh, yêu cầu bạn đưa cho AI.', 'Như bản giao việc cho nhân viên: càng rõ, kết quả càng tốt.'],
    ['Token', 'Đơn vị nhỏ AI dùng để đọc và viết chữ, khoảng một phần của từ.', 'Như những viên gạch nhỏ ghép thành câu.'],
    ['"AI bịa" (Hallucination)', 'AI trả lời tự tin nhưng sai sự thật.', 'Như người không biết nhưng ngại nói "không biết".'],
    ['RAG', 'Cho AI tra tài liệu của bạn trước khi trả lời.', 'Như làm bài thi được mở sách: trả lời đúng theo tài liệu.'],
    ['Embedding / Vector', 'Cách biến chữ thành dãy số để máy tìm theo ý nghĩa, không chỉ theo từ khóa.', 'Như xếp sách theo nội dung thay vì theo tên.'],
    ['AI Agent', 'AI tự lên kế hoạch và dùng công cụ để làm trọn một việc.', 'Như nhân viên được giao mục tiêu, tự tìm cách hoàn thành.'],
    ['MCP', 'Chuẩn kết nối giúp AI dùng các phần mềm, dữ liệu một cách thống nhất.', 'Như cổng USB: một chuẩn cắm được nhiều thiết bị.'],
    ['RPA', 'Robot phần mềm bắt chước thao tác chuột, bàn phím của người.', 'Như nhân viên ảo ngồi gõ máy tính theo đúng hướng dẫn.'],
    ['OCR', 'Nhận dạng chữ trong ảnh hoặc file scan.', 'Như đôi mắt đọc giấy tờ và gõ lại thành chữ.'],
    ['Fine-tuning', 'Huấn luyện thêm một mô hình có sẵn bằng dữ liệu riêng.', 'Như cho sinh viên giỏi đi thực tập chuyên sâu tại công ty.'],
    ['API', 'Cửa giao tiếp để các phần mềm nói chuyện với nhau.', 'Như quầy giao dịch: đưa yêu cầu vào, nhận kết quả ra.'],
    ['On-premise', 'Máy chủ và phần mềm đặt ngay tại doanh nghiệp.', 'Như tự xây nhà máy điện riêng.'],
    ['Cloud riêng (VPC)', 'Vùng mạng riêng trên hạ tầng cloud, chỉ doanh nghiệp truy cập.', 'Như căn hộ có khóa riêng trong tòa nhà lớn.'],
    ['Edge AI', 'AI chạy ngay trên thiết bị tại chỗ, không cần gửi lên cloud.', 'Như có chuyên gia đứng ngay tại hiện trường.'],
    ['Computer Vision', 'AI hiểu hình ảnh và video.', 'Như cho camera một đôi mắt biết suy nghĩ.'],
    ['Human-in-the-loop', 'Con người duyệt hoặc can thiệp ở những bước quan trọng.', 'Như tự lái có tài xế ngồi sẵn sau vô lăng.']
  ];
})();
